### ISSUE TITLE
Lint Tests as part of Presubmit

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#100]
Lint tests for style and formatting

**Comment by advayDev1** [comment]
if you do this, make it a gradle task so that it is also part of the continuous build

**Comment by brunobowden** [comment]
There's techniques for this on Android, I couldn't see the same for Groovy.

**Comment by advayDev1** [comment]
Same, I have looked for Groovy lint and couldn't find any.
Iceboxing for now.
