### ISSUE TITLE
Beta-compatible usage documentation

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#111]
README.md and groovydoc for J2objcPlugin class need to be updated with proper usage docs after we're all done refactoring.  Should be compatible with the summit slides.

**Comment by brunobowden** [comment]
@richburdon, @confile - please take a look, particularly the new build instructions:

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/README.md#usage

There are some known issues, particularly on the large few steps with Xcode. I'll be presenting the plugin tomorrow as an alpha version. Here's the immediate pressing issues:

https://github.com/j2objc-contrib/j2objc-gradle/milestones/Gradle%20Summit
