### ISSUE TITLE
Split translation of main & test sourceSets

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#112]
It is more correct to translate & compile main, then translate & compile test as depending on main, in 2 separate phases.  This ensures that the production library has *only* the files needed by main.

At the moment, if tests rely on libraryB, the production library will contain libraryB for no reason.

**Comment by advayDev1** [comment]
Not for summit milestone.

**Comment by advayDev1** [comment]
i will not have a chance to do this any time soon, but it is pretty important.

**Comment by advayDev1** [comment]
with auto-config, your production libraries could be linking with test libraries.

**Comment by advayDev1** [comment]
This is currently my top correctness concern (there are other usability ones though); it also requires a large refactor of the plugin.

Many projects' test files don't end with the word Test, or their *Test classes have support classes that aren't similarly.  All such files are erroneously ending up in the production static library, and also all such tests aren't being run.

Example: https://github.com/JodaOrg/joda-convert/tree/master/src/test/java/org/joda/convert

**Comment by brunobowden** [comment]
I agree on that. It's a big assumption we're making there that's nolonger relevant.
