### ISSUE TITLE
Copy task needs to support incrementality

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#115]
Because it lacks @outputs or @outputDirectories, J2objcCopy task will always be executed.

**Comment by advayDev1** [comment]
will fix in #114 as well

**Comment by brunobowden** [comment]
I fixed this a while ago but this is a better fix.

**Comment by advayDev1** [comment]
I don't see how you fixed it?  No @Output is marked in CopyTask, therefore the task will always be xecuted.

**Comment by brunobowden** [comment]
I had something working before... maybe it was just a local fix that never
got pushed. Either wya, this is a much better way of doing it.
