### ISSUE TITLE
Exported header directory that skips internal header files

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#117]
This is for Xcode HEADER_SEARCH_PATH, so that it doesn't include any header files that aren't exposed. This directory should also update the bridging header file contents.

**Comment by confile** [comment]
@brunobowden Since the bridging header file is outside the pod a pod cannot update it.

**Comment by brunobowden** [comment]
Confile - I think we can develop our own system to manipulate the bridging
header within the j2objc gradle plugin. You're welcome to try it, or I can
help you out later this week.

**Comment by confile** [comment]
I guess we could do it like this: 

- configure the name of the bridging header in the Extensions
- create a task to update the bridging header
  - check if gradle-j2objc bridging header section exist if so delete it
  - append a gradle-j2objc bridging header section with a list of imports

@brunobowden Is this what you have in mind?

How do we decide which imports to use?

**Comment by brunobowden** [comment]
We'd need to export a separate set of headers through a Gradle file pattern.

**Comment by advayDev1** [comment]
I don't think we should do this.  Remember that the headers you care about and specify may sometimes also themselves #import other headers - they may not be in this surface you define.  I think that is complexity the user should not have to worry about - all your headers should be available for use in Xcode just like in a dependent Java project.

Please reopen if you disagree @brunobowden
