### ISSUE TITLE
Support more iOS flavors

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#123]
Support at least:
iPad {2, Air, Retina}, iPhone {4s, 5, 5s, 6 Plus, 6}, Resizable iPad, Resizable iPhone

**Comment by advayDev1** [comment]
After the simulators work with PR #124, I'll need to assign this to one of you @j2objc-contrib/j2objc-gradle-devs to do {armv7, armv7s, arm64} for real iOS devices, since I could guess at the code, but would not be able to verify that it works.  Who would like to get this working on real devices?

**Comment by advayDev1** [comment]
I suspect that other than the -arch param, you will also need to use an isysroot of:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`

**Comment by advayDev1** [comment]
@brunobowden is finishing the device side.

**Comment by brunobowden** [comment]
Fixed in issue #126
