### ISSUE TITLE
Clean up source repo branching

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#125]
Now that brunobowden/j2objc-gradle is symmetric to all the other contributors, do you want to delete your personal branches from this repo?  I don't think any of them represent real product branches that we want people to work on, they're just your dev branches, correct?

**Comment by brunobowden** [comment]
All cleaned up

**Comment by advayDev1** [comment]
is your remote setup correctly?  you are still pushing your dev branches to the source repo.
see ex. branch brunobowden-new-usage - that should exist only in brunobowden/j2objc-gradle not j2objc-contrib/j2objc-gradle

**Comment by brunobowden** [comment]
I was experimenting editing it in the source repo and it said it could create a pull request. I won't be doing that again but instead do everything my separate repo and then the normal PR process.

I can't see the branch now... not sure if it was automatically removed?

**Comment by advayDev1** [comment]
yeah i just cleaned that one up right now that's all
