### ISSUE TITLE
Pods-PROJECT-j2objc-base erroneously added by j2objcXcode

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#128]
The "Pods-XCODE_PROJECT" library seems to be created under "Frameworks" and added to the linker flags. This causes the build to fail... when it's removed then the build works fine.

@confile - I'd appreciate your insights on this

![screen shot 2015-06-11 at 3 20 50 am](https://cloud.githubusercontent.com/assets/679339/8104949/9fef4dde-0fe9-11e5-986e-595105a22775.png)

**Comment by confile** [comment]
Not sure maybe it is cauesd by this line: 
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcXcodeTask.groovy#L110

What is your ``'${project.name}-j2objc``? I guess it is ``base-j2objc`` from your screenshot. IT is really strange let me test this I give you feedback.

**Comment by brunobowden** [comment]
The `${project.name}-j2objc` is for the library `base-j2objc` which you can see in the xcconfig above and is correct. The problem is the `Pods-PROJECT-j2objc-base` which shouldn't be there.

**Comment by confile** [comment]
I keep looking at this as soon as I get the new plugin running which is currently not the case.

**Comment by advayDev1** [comment]
@confile, the main thing preventing you from building your plugin is this issue and #129.  if you have any potential fixes, this is the issue to look at.
