### ISSUE TITLE
Xcode task copies header files when it should leave them in place

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#129]
The "${project.buildDir}j2objcOutputs/src/main/objc" is what Xcode should link to the sources files rather than copying the header files elsewhere. The xcconfig currently is configured as follow: 

HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/j2objc-base"...

Instead it should have a single reference to "${project.buildDir}j2objcOutputs/src/main/objc"

@confile - I'd appreciate your help here

**Comment by confile** [comment]
@brunobowden Should be fixed with this: https://github.com/j2objc-contrib/j2objc-gradle/pull/192

**Comment by advayDev1** [comment]
Current Xcode podspec tasks no longer copy headers.
