### ISSUE TITLE
fix plugins {} syntax - java plugin ordering

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#130]
The plugins syntax for loading the j2objc plugin prevents you from loading the java plugin beforehand. That means that the j2objc plugin needs to operate assuming that the java plugin is loaded afterwards.

    // plugins prevent applying java plugin beforehand
    plugins {
      id "com.github.j2objccontrib.j2objcgradle" version "0.2.0-alpha"
    }
    apply plugin: 'java'

**Comment by advayDev1** [comment]
wait, can we do:
```
plugins {
  id "java"
  id id "com.github.j2objccontrib.j2objcgradle" version "0.2.0-alpha"
}
```

breaking lateDependsOn is a lot to lose...

**Comment by brunobowden** [comment]
That doesn't work unfortunately. I've figured out another workaround which is to use the old buildscript syntax which allows you to specify the ordering of the plugin load.

I'll talk with some of the Gradle people over the next day or two to see if there's a way to use it with the `plugins {}` syntax.

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.j2objccontrib.j2objcgradle:j2objc-gradle:0.2.0-alpha"
    }
}

apply plugin: 'java'
apply plugin: "com.github.j2objccontrib.j2objcgradle"
```

**Comment by advayDev1** [comment]
i think we should go with this for now and revert the commenting out of lateDependsOn.

**Comment by brunobowden** [comment]
Agreed. Working on that now.

**Comment by brunobowden** [comment]
#131 is a workaround but not a fix, reopening...

**Comment by brunobowden** [comment]
Still needs verification...
