### ISSUE TITLE
J2OBJC_HOME environment setup for Eclipse documentation

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#133]
In my ``~/.bash_profile`` I have: 

```
export J2OBJC_HOME=/Applications/J2Objc/j2objc-0.9.7b
export PATH=$PATH:$J2OBJC_HOME
```

I checked from the command line I check if the env variable is set correctly: ``echo $J2OBJC_HOME``: 

```
/Applications/J2Objc/j2objc-0.9.7b
```:
I can also call ``j2objc`` from anywhere so it is set correctly. Using the latest plugin from 2015-06-11 I get the errorr: 

```
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
org.gradle.api.InvalidUserDataException: j2objc home not set, this should be configured either:
1) in a 'local.properties' file in the project root directory as:
   j2objc.home=/PATH/TO/J2OBJC/DISTRIBUTION
2) as the J2OBJC_HOME system environment variable
```

This is strange since J2OBJC_HOME is available as I proved from the command line.

**Comment by confile** [comment]
It seems to work with the first option the local.properties file but the system env option is buggy.

**Comment by confile** [comment]
I am not sure if [this line](https://github.com/j2objc-contrib/j2objc-gradle/blob/56393a3b7c5c37fd2b8355cdba0804ad048efdde/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcUtils.groovy#L69) must be: 

```
result = System.getenv('$J2OBJC_HOME')
```

**Comment by brunobowden** [comment]
Please test this @Confile and send a PR if it works. Thanks for catching
that one.

**Comment by confile** [comment]
I have tested it with the $ sign this was not the problem. The problem is that ``System.getenv`` does not look into variables defined in ``bash_profile``, i.e., from the PATH variable.

**Comment by advayDev1** [comment]
btw, this System.getenv is how Android SDK does it:
https://android.googlesource.com/platform/tools/base/+/c8b776289ace4189406b59a9a9c8c9de63271cb0/build-system/gradle/src/main/groovy/com/android/build/gradle/internal/SdkHandler.java

So can you see if the Android gradle plugin works for you if you put the sdk location ONLY in your .bash_profile and not in local.properties.

**Comment by confile** [comment]
@advayDev1 I checked it out SDK location is only in .bash_profile and not in local.properties. Does not find the variable. 

Does it work for you?

**Comment by brunobowden** [comment]
I'll try this as well...

**Comment by advayDev1** [comment]
@confile - this makes sense.  I don't think OS X runs your .bash_profile when starting apps from the desktop.  If you started your IDE from a bash shell it should be fine.

**Comment by confile** [comment]
@advayDev1 Where should I put my system variables when I start an app from IDE?

**Comment by advayDev1** [comment]
a quick search gives this:
http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x

but it applies to all users not just user user.  not sure if that matters to you.

**Comment by advayDev1** [comment]
Also if you use eclipse, this may be useful to you:
http://stackoverflow.com/questions/7501678/set-environment-variables-on-mac-os-x-lion/23481458#23481458

**Comment by brunobowden** [comment]
@confile - were you able to get this working by setting the OS X environment variables? If so, then please send a PR for the FAQ on how to do this.

**Comment by confile** [comment]
@advayDev1 @brunobowden No it does not solve the problem.

**Comment by brunobowden** [comment]
Can you try configuring the local.properties file instead. Here's my line
from the file:

j2objc.home=/Users/brunobowden/dev/j2objc-versions/j2objc-0.9.6.1

**Comment by confile** [comment]
@brunobowden I still have it running for a long time with ``local.properties`` and j2objc.home. The goal here war to get the other version running as well.

**Comment by brunobowden** [comment]
So this works for running Geadle on the command line?

But there's an issue with running Gradle from Eclipse? If so, then this
means that the plugin is fine but you need a better way of documenting this
for Eclipse. If that's the case, then change the issue title "J2OBJC_HOME
environment setup for Eclipse documentation".

Given that Android has moved all the development to Android Studio, either
that or IntelliJ is the preferred way to do development.

There's another issue I created

**Comment by confile** [comment]
Yes it runs perfect from command line. But from eclipse it does not find the correct path. I am moving to Android Studio!

**Comment by brunobowden** [comment]
Closing as this isn't a plugin issue
