### ISSUE TITLE
Convert J2objcPluginExtension comments to groovydoc

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#141]
@brunobowden we should be able to convert our comments to groovydoc and then publish a description of our DSL automatically.  Or do you want to duplicate all this info in README.md and/or in J2objcPlugin.groovy?  I prefer not duplicating.  When we publish a new version, one of the steps would be publishing the groovydoc to the github.com project site.  How does that sound?

**Comment by brunobowden** [comment]
I'm open to this. Particularly the more automated it is. I've had issues in
the project site before that it's difficult to do PRs and make changes. So
I'm concerned that this change might make it painful to work with.

**Comment by advayDev1** [comment]
Either way we should do the groovydoc.  I agree that maybe the site won't be easy to use.
