### ISSUE TITLE
Add description for settings.gradle to docs

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#150]
The readme should contain at least a short note what to do when using ``settings.gradle``. You need it when shared uses other subprojects. The problem is that Android Studio does not work properly when you have at least two ``settings.gradle`` on your included gradle projects.

Since Android Studio uses a ``settings.gradle`` you cannot use a second one in the share project. But, you need the ``settings.gradle`` in the shared project when translating to Xcode (with dependent projects).

Any idea how to solve this?

**Comment by advayDev1** [comment]
Can you provide a concrete example?  As a gradle rule, your entire multi-project setup can only have one settings.gradle that is a peer of the top-most (root) build.gradle.

**Comment by confile** [comment]
Yes the problem is that in Android Studio the android project is the top most which has the settings.gradle. 

When you are in the iOS gradle world the shared project is the top most. Thus, it contains the settings.gradle. 

Do you see my point?

**Comment by advayDev1** [comment]
Ah yes you can't have two top-most (root) projects that are peers.
You should have:
```
repo/
  settings.gradle
  build.gradle
  android/
     build.gradle
  otherLib/

```

**Comment by confile** [comment]
Are these
```
/repo
  settings.gradle
  build.gradle
```
generated by Android Studio when you create a new project? Is this the one where you put the j2objc plugin as well. You see I am struggling with this. Maybe a short docu would help a lot.

**Comment by advayDev1** [comment]
Ah yes I setup my multi-project build manually, not using Android Studio.  I don't know if/how it supports *creating* that kind of build with the GUI.  It definitely supports building such a project though.  @brunobowden, did you make your multi-project build manually too?

**Comment by confile** [comment]
@advayDev1 What is in your /repo/build.gradle? Could you please share an example?

**Comment by advayDev1** [comment]
my build.gradle won't help you much.  it has a ton of extra complexity because it builds its own toolchain and then builds itself.

**Comment by confile** [comment]
Where do you put the j2objc plugin in which build.gradle?

**Comment by advayDev1** [comment]
Say I have the following:
```
repo/
  settings.gradle
  build.gradle
  androidApp/
     build.gradle
  onePureJavaLib/
     build.gradle   (A)
  otherPureJavaLib/
     build.gradle   (B)
```

then j2objc plugin should be applied in A and B and nowhere else.

**Comment by confile** [comment]
j2objc plugin is in two gradle projects? That sounds strange. Which is your main project for iOS translation I mean the one which includes all the others?

**Comment by advayDev1** [comment]
None is the 'main' project.  I have many shared projects with interdependencies.

**Comment by advayDev1** [comment]
@confile 
Btw, is any of your code open-source?  I might be able to help if you can point me to a github repo and I can look at it.

**Comment by confile** [comment]
@advayDev1 As you wish I created a demo project: https://github.com/confile/Demo-Shared-iOS-Android-Project

It contains the build.gradle files and the project structure I am using. I appreciate your help.

**Comment by advayDev1** [comment]
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/systemTests/allPlatforms/settings.gradle
