### ISSUE TITLE
Could not compile Source project with compileIos_arm64Debug...

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#151]
I'm still struggling to use the new Plugin with my code. What I did is replacing the single file plugin we started with, with the new real gradle plugin. The code is unchanged. 

Running ``gralde j2objcXcode`` leads to the following error: 
```
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:j2objcPreBuild UP-TO-DATE
:j2objcCycleFinder SKIPPED
:j2objcTranslate
:compileIos_arm64DebugBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-main/build/j2objcSrcGen/ActionSheetOptions.m:50:16: error: assigning instance variable to itself [-Werror,-Wself-assign-field]
  self->title_ = title_;
               ^
1 error generated.

/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-main/build/j2objcSrcGen/BPlaceManagerImpl.m:246:3: error: implicit declaration of function 'JreRelease' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  JreRelease(this$0_);
  ^
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-main/build/j2objcSrcGen/BPlaceManagerImpl.m:246:3: note: did you mean 'CFRelease'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:569:6: note: 'CFRelease' declared here
void CFRelease(CFTypeRef cf);
     ^
1 error generated.
``` 
There are a lot more errors but I skip them here.

**Comment by advayDev1** [comment]
Have you previously successfully built your app for arm64?

Do you disable warnings in your xcode project?

**Comment by confile** [comment]
I don't know what you mean sorry. What I did was just using the pod task to generate the pod which links the source files to my Xcode project. I did not do external compile. 

Could you give me a little help what to do here? Since the code compiles without problems in Xcode I see no problem here.

**Comment by advayDev1** [comment]
compiles for which architecture(s), with what build settings?  i don't know what you mean when you say compiles without problems.

have you tried running clean and rebuilding?

it is hard to help not knowing the state of your workspace at the moment.

**Comment by confile** [comment]
I compile for iPhone5,6 and iPad Air using the default Xcode settings. Which architecture is that?

**Comment by confile** [comment]
I still don't get why compiling in Xcode works and with the plugin it does not.

**Comment by advayDev1** [comment]
We have to eliminate reasons in order to figure that out.  First we need to eliminate:
- stale files (did you run clean?)
- different set of files in j2objc than Xcode (compare the files in build/j2objcSrcGen to the ones you see in Xcode.  Is for example ActionSheetOptions.m in your working xcode build?)
- different architectures (you need to look up the ld flags in xcode yourself, I don't know which architectures you are using)

**Comment by confile** [comment]
- yes I run clean all the time first ``gradle clean`` then ``gradle j2objcXcode```
- I compared the ActionSheetOptions.m files from both versions they are identical
- just created an Xcode project and did not change the architecture. Do you mean this: 

![majestella_xcodeproj](https://cloud.githubusercontent.com/assets/64265/8123546/d38d7ebc-10cb-11e5-888a-528b9c7f608f.png)

**Comment by advayDev1** [comment]
Awesome, we're making progress then.  Can you find the corresponding line of Java source in ActionSheetOptions.java that's erroring out?  Is it in fact self-assigning the value?

**Comment by advayDev1** [comment]
Also can you indicate what your j2objcConfig for the build.gradle is (if it is not private).

**Comment by confile** [comment]
j2objcConfig:
```
j2objcConfig {
generatedSourceDirs "build/source/apt", "build/source/base"
  xcodeProjectDir "${projectDir}/../Buddyis"
  xcodeTarget "Buddyis"
  translateFlags "--no-package-directories --prefixes prefixes.properties -use-arc --doc-comments --build-closure --generate-deprecated --static-accessor-methods"
  
  translateClassPaths "json-20140107.jar", "javax.inject-1.jar", "auto-factory-1.0-beta2.jar", "auto-service-1.0-rc2.jar", "javawriter-2.5.1.jar" //, "guava-18.0.jar" //, "dagger-1.2.0.jar"
  translateSourcepaths "${projectDir}/libSrc/dagger-2.0.1-sources.jar"
translateJ2objcLibs "j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"
filenameCollisionCheck = true
cycleFinderExpectedCycles 0
  cycleFinderFlags "--whitelist /Applications/J2Objc/j2objc-sorce/jre_emul/cycle_whitelist.txt --sourcefilelist /Applications/J2Objc/j2objc-sorce/jre_emul/build_result/java_sources.mf"
  
}
```

**Comment by confile** [comment]
Here is the Java file ActionSheetOptions:

```
package buddyis.core.plugins.actionSheet;

import com.google.common.base.Strings;

public final class ActionSheetOptions {

  private String title;
  private String[] buttonLabels;
  private String addCancelButtonWithLabel;
  private String addDestructiveButtonWithLabel;
  private boolean androidEnableCancelButton;
  private boolean winphoneEnableCancelButton;

  public ActionSheetOptions() {
  }

  public boolean hasTitle() {
    if (Strings.isNullOrEmpty(title)) {
      return false;
    }
    return true;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String text) {
    this.title = title;
  }

  public void unsetTitle() {
    this.title = null;
  }

  public void addButtonLabels(String[] labels) {
    this.buttonLabels = labels;
  }
  
  public String[] getButtonLabels() {
    return buttonLabels;
  }

  public void addCancelButtonWithText(String text) {
    this.addCancelButtonWithLabel = text;
  }
  
  public String getCancelButtonWithText() {
    return addCancelButtonWithLabel;
  }
  
  public void addDestructiveButtonWithLabel(String text) {
    this.addDestructiveButtonWithLabel = text;
  }
  
  public String getDestructiveButtonWithLabel() {
    return addDestructiveButtonWithLabel;
  }

  public void androidEnableCancelButton(boolean value) {
    this.androidEnableCancelButton = value;
  }
  
  public boolean getAndroidEnableCancelButton() {
    return androidEnableCancelButton;
  }

  public void winphoneEnableCancelButton(boolean value) {
    this.winphoneEnableCancelButton = value;
  }

}
```

**Comment by advayDev1** [comment]
Your Java code definitely has a bug:
public void setTitle(String text) {
    this.title = title;
  }

that should be this.title = text.

It is correct that j2objc fails in this case.  I'm worried that you have disabled some of your java compilation warnings because your java compile should have also failed.

**Comment by confile** [comment]
I have not disabled anything. I use ``gradle build`` for the java compilation. How do I enable the warnings you set?

**Comment by advayDev1** [comment]
let's figure that out separately... what happens after you fix that bug?  what are the errors now?
I'm guessing the next thing causing an issue is '-use-arc'

**Comment by confile** [comment]
Can't I use ``-use-arc``?

**Comment by advayDev1** [comment]
I'm not saying you can't, but we need to root-cause the issue.  In order to do that, we need to see what the error messages look like after fixing the title bug.

**Comment by confile** [comment]
I will go to bed now give you feedback tomorrow. Could you please send me an email if there is a quick fix to turn on the java check with gradle build. Thank you for your help @advayDev1 .

**Comment by advayDev1** [comment]
Aside for @confile , here is one way to turn on warnings as errors.  This is a guess though.  Put the following in your top-level build.gradle:
```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            // Warnings as errors
            options.compilerArgs <<  '-Werror'
        }
    }
}
```

**Comment by confile** [comment]
@advayDev1 This does not work. I tried ``gradle build`` build there are no errors reported. I also tried this: 
```
compileJava {
 options.compilerArgs << "-Werror"
}
```
It also does not show any warnings as errors.

**Comment by brunobowden** [comment]
If you learn certain tricks for debugging either using the plugin or
development, then consider adding them to the documentation if you think
they'll be useful for others.

**Comment by confile** [comment]
@brunobowden Ok I will do that.

**Comment by confile** [comment]
@advayDev1 @brunobowden Do you treat warnings always as kind of errors and do you tried to make them disappear?

**Comment by confile** [comment]
@advayDev1 I fixed most of the warnings. Now I got this when running the Xcode task: 

```
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-main/build/j2objcSrcGen/BPlaceManagerImpl.m:246:3: error: implicit declaration of function 'JreRelease' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  JreRelease(this$0_);
  ^
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-main/build/j2objcSrcGen/BPlaceManagerImpl.m:246:3: note: did you mean 'CFRelease'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:569:6: note: 'CFRelease' declared here
void CFRelease(CFTypeRef cf);
     ^
1 error generated.
```

**Comment by advayDev1** [comment]
@confile:
- yes, i try to use warnings as errors when possible.  if the issue really isn't a problem, you can use @SuppressWarnings and the like.  a good explanation of warnings as errors (for Clang, but still useful) is here: http://programmers.stackexchange.com/questions/122608/clang-warning-flags-for-objective-c-development/124574#124574
- not sure what BPlaceManagerImpl.java looks like, so it is hard to comment on that error.

**Comment by advayDev1** [comment]
if you aren't comfortable making BPlaceManagerImpl public, feel free to share an isolated repro case that you are comfortable sharing.

**Comment by confile** [comment]
BPlaceManagerImpl.java is:
```
package majestella.core.prototype.navigation;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import majestella.core.prototype.eventBus.AbstractBEvent;
import majestella.core.prototype.eventBus.BEventBus;

import com.google.j2objc.annotations.WeakOuter;

import core.helper.timer.BTimer;
import core.helper.timer.BTimerCallback;

public class BPlaceManagerImpl implements BPlaceManager {

  private boolean hasRunningNavigation = false;
  private BTimer releaseLokedNavigationTimer;
  
  private final BEventBus eventBus;
  private final BTokenFormatter tokenFormatter;
  
  private List<BPlaceRequest> placeHierarchy = new ArrayList<BPlaceRequest>();
  
  public BPlaceManagerImpl(BEventBus eventBus, BTokenFormatter tokenFormatter) {
    this.eventBus = eventBus;
    this.tokenFormatter = tokenFormatter;
    
  }
  
  
  @Override
  public String buildHistoryToken(BPlaceRequest request) {
    return tokenFormatter.toPlaceToken(request);
  }
  
  
  @Override
  public void revealPlace(BPlaceRequest request) {
    revealPlace(request, true);
  }
  
  @Override
  public void revealPlace(BPlaceRequest request, boolean updateBrowserUrl) {    
    // TODO not implemented code here

    if (!hasRunningNavigation) {
      hasRunningNavigation = true; // MG
      startReleaseTimer(); // MG
      
      placeHierarchy.clear();
      placeHierarchy.add(request);
      doRevealPlace(request, updateBrowserUrl);
    }
  }
  
  
  @WeakOuter
  private class TmpTimer implements BTimerCallback {
    @Override
    public void run() {
      Logger logger = Logger.getLogger("TEST");
      logger.info("------------- release: hasRunningNavigation: !!!!!");
      hasRunningNavigation = false;
    }    
  }
  
  private void startReleaseTimer() {
    if (releaseLokedNavigationTimer != null) {
      releaseLokedNavigationTimer.cancel();
    }
    releaseLokedNavigationTimer = new BTimer();
    releaseLokedNavigationTimer.setRun(new TmpTimer());
    releaseLokedNavigationTimer.schedule(500);
  }
  
  
  protected void doRevealPlace(BPlaceRequest request, boolean updateBrowserUrl) {
    BPlaceRequestInternalEvent requestEvent = new BPlaceRequestInternalEvent(request,
        updateBrowserUrl);
    
    fireEvent(requestEvent);
  }
  
  
  @Override
  public void fireEvent(AbstractBEvent<?> event) {
    getEventBus().fireEventFromSource(event, this);
  }
  
  
  public BEventBus getEventBus() {
    return eventBus;
  }
  
  
  @Override
  public BPlaceRequest getCurrentPlaceRequest() {
    if (placeHierarchy.size() > 0) {
      return placeHierarchy.get(placeHierarchy.size() - 1);
    } else {
        return new BPlaceRequest.Builder().build();
    }
  }

  
  @Override
  public void updateHistory(BPlaceRequest request, boolean updateBrowserUrl) {
    try {
      // Make sure the request match
      assert request.hasSameNameToken(getCurrentPlaceRequest()) : "Internal error, PlaceRequest passed to" +
              "updateHistory doesn't match the tail of the place hierarchy.";
      placeHierarchy.set(placeHierarchy.size() - 1, request);
      if (updateBrowserUrl) {
          String historyToken = tokenFormatter.toHistoryToken(placeHierarchy);
          // only infor the history stack if the historyToken is different than the current one
            setBrowserHistoryToken(historyToken, false);  
      }
    } catch (TokenFormatException e) {
        // Do nothing.
    }
  }
  
  
  /**
   * Update the history stack with the history token.
   * @param historyToken
   * @param issueEvent
   */
  private void setBrowserHistoryToken(String historyToken, boolean issueEvent) {
    BHistoryUpdateEvent event = new BHistoryUpdateEvent(historyToken);
    fireEvent(event);
  }
 
  @Override
  public void navigateBack() {
    BBackNavigationEvent backEvent = new BBackNavigationEvent();
    fireEvent(backEvent);
  }
  
  
  @Override
  public void navigationComplete() {
    Logger logger = Logger.getLogger("TEST");
    logger.info("------------- navigationComplete");
    
    hasRunningNavigation = false;
  }
  
}

```

**Comment by advayDev1** [comment]
did you have any compileFlags in your old plugin setup? @confile

**Comment by confile** [comment]
These are my old plugin compile flags: 

```
compileFlags "-ObjC -lguava -ljavax_inject -ljre_emul -ljsr305 -ljunit -lmockito"
```

**Comment by advayDev1** [comment]
ok all of those are already being used in J2objcNativeCompilation.groovy.  
I also just tried --use-arc for own project and it is working for me...

can you share BPlaceManagerImpl.m and .h?
and what version of j2objc are you using?

**Comment by advayDev1** [comment]
Ah @WeakOuter - I don't use those yet, that is the only difference I see between your source and mine.   @brunobowden - do you use this annotation?

**Comment by confile** [comment]
j2objc version: I build from code latest version from github master last build 11 days ago. 

How can you not use ``@WeakOuter``? You need this when creating anonymous functions and access variables from the outer class.

**Comment by advayDev1** [comment]
As a general practice, I don't use non-static inner classes, ex: http://stackoverflow.com/questions/3106912/why-does-android-prefer-static-classes
I also minimize anonymous functions (I assume you mean anonymous inner classes) for the same reason.

If you are willing, do share the generated .m and .h files.

**Comment by confile** [comment]
@advayDev1 Okay here are the files: 

[BPlaceManagerImpl.h](https://gist.github.com/confile/a45897508aacc70d05d8)

[BPlaceManagerImpl.m](https://gist.github.com/confile/9673bed1d6f7746d2ab1)

**Comment by confile** [comment]
I need the latest snapshot in order to use the ``--static-accessor-methods`` flag.

**Comment by advayDev1** [comment]
aha!  we are getting somewhere:
https://github.com/google/j2objc/blame/b08a8336a1f037df1b9e9f6b711e3820efc27cfe/jre_emul/Classes/J2ObjC_source.h#L33

JreRelease is only exposed when __has_feature(objc_arc) is on.
Also, the reason my code is working fine even with --use-arc is that only implementations of clone() use this, see: https://github.com/google/j2objc/commit/f2ab39adf877c8c1cd107f0b3cf6ed21b42beeae

You have clone here:
https://gist.github.com/confile/9673bed1d6f7746d2ab1#file-gistfile1-txt-L244

I think the solution is adding '-fobjc-arc' - with PR #158 you will be able to do that:
https://github.com/j2objc-contrib/j2objc-gradle/pull/158/files#diff-23b065485f3cb4fcc56efe23f0010b01R278

**Comment by advayDev1** [comment]
i suggest patching in #158 and adding '-fobjc-arc' as an extraObjcCompilerArgs OR if just change your local J2objcNativeCompilation.groovy to have '-fobjc-arc' .  add:
    
    objcCompiler.args '-fobjc-arc'
below 
    
    objcCompiler.args '-std=c11'

**Comment by advayDev1** [comment]
IFF this works for you, the solution is to finish #158 and also #85 (@brunobowden) so that flags like this are symbolic, not just strings in the translateFlags, and then automatically add '-fobjc-arc' to the native compilation when j2objcConfig.useArc is also enabled.

**Comment by confile** [comment]
@advayDev1 I don't get it. Should I make the pull request or you?

**Comment by advayDev1** [comment]
you need to see if this fixes the issue for your first locally.

if it does, then you need to wait until #158 goes in, and then you can do:
```
j2objcConfig {
   extraObjcCompilerArgs += '-fobjc-arc'
}
```

**Comment by confile** [comment]
@advayDev1 Hope this get merged soon.

**Comment by advayDev1** [comment]
So it worked for you?

**Comment by confile** [comment]
I get an error when using: ``extraObjcCompilerArgs += '-fobjc-arc'`` in my j2objcConfig. The extra property extraObjcCompilerArgs is not in the master yet.

**Comment by advayDev1** [comment]
try the other option I gave:
"
just change your local J2objcNativeCompilation.groovy to have '-fobjc-arc' . add:

    objcCompiler.args '-fobjc-arc'
below

    objcCompiler.args '-std=c11'
"

make sure you are using the locally built plugin jar (see README.MD section Interim development).

**Comment by confile** [comment]
@advayDev1 Not sure if it works but I am a sep further. The latest error is: 

```
buddyis-main/build/j2objcSrcGen/CameraManagerImpl.m:146:17: error: method 'ALLOW_EDIT' in protocol 'BuddyisCoreAppPhotoEditorCameraManagerCameraManager' not implemented [-Werror,-Wprotocol]
@implementation BuddyisCoreAppPhotoEditorCameraManagerCameraManagerImpl
```
and here is ``CameraManager.java``: 
```
public interface CameraManager {

  public enum SourceType {
    CAMERA_IMAGE, ALBUM_IMAGE
  }

  public static final boolean ALLOW_EDIT = true;
  public static final boolean SAVE_TO_PHOTO_ALBUM = true;

  void getPhotoWorkaround();

}
``` 

It seems that the problem is with the static variables.

**Comment by advayDev1** [comment]
What about the .h and .m files?

**Comment by confile** [comment]
[CameraManager.h](https://gist.github.com/confile/2ade8d00cbddb76fea45)

[CameraManager.m](https://gist.github.com/confile/54905109b8419b51c5d5)

**Comment by advayDev1** [comment]
that is CameraManager ... it has no Line 146.  we need CameraManagerImpl.java, .h, and .m

**Comment by confile** [comment]
[CameraManagerImpl.java](https://gist.github.com/confile/fe32f7b6035660f72571)

[CameraManagerImpl.h](https://gist.github.com/confile/b1f34103dbf12e52c740)

[CameraManagerImpl.m](https://gist.github.com/confile/956ab282dc1b479610c6)

**Comment by confile** [comment]
@advayDev1 Here is Line 164 https://gist.github.com/confile/956ab282dc1b479610c6#file-gistfile1-txt-L146

**Comment by advayDev1** [comment]
can you turn off static-accessor-methods?  i'm guessing it doesn't yet support the new Java functionality of an interface declaring a public static final variable?

**Comment by confile** [comment]
Okay. should I also delete this line: objcCompiler.args '-fobjc-arc'

**Comment by advayDev1** [comment]
no.  you need that.  but static-accessor-methods must be the culprit: interfaces can't have implemented methods.

**Comment by confile** [comment]
@advayDev1 by the way is incremental compile working?

**Comment by advayDev1** [comment]
please let's get through one thing at a time.  at 3pm I will unfortunately no longer be able to help on this issue until ~Tuesday.

incremental *compile* is working AFAIK.  incremental translation has had a bug since it was first written, which i fixed in #160 (not yet merged).

**Comment by confile** [comment]
@advayDev1 Thanks for your help compilation is still running it seems to work. 

```
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:j2objcPreBuild UP-TO-DATE
:j2objcCycleFinder SKIPPED
:j2objcTranslate
:compileIos_arm64DebugBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
:linkIos_arm64DebugBuddyis-main-j2objcSharedLibrary
:ios_arm64DebugBuddyis-main-j2objcSharedLibrary
:compileIos_arm64DebugBuddyis-main-j2objcStaticLibraryBuddyis-main-j2objcObjc
:createIos_arm64DebugBuddyis-main-j2objcStaticLibrary
:ios_arm64DebugBuddyis-main-j2objcStaticLibrary
:compileIos_arm64ReleaseBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
:linkIos_arm64ReleaseBuddyis-main-j2objcSharedLibrary
:ios_arm64ReleaseBuddyis-main-j2objcSharedLibrary
:compileIos_arm64ReleaseBuddyis-main-j2objcStaticLibraryBuddyis-main-j2objcObjc
:createIos_arm64ReleaseBuddyis-main-j2objcStaticLibrary
:ios_arm64ReleaseBuddyis-main-j2objcStaticLibrary
:compileIos_armv7DebugBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
:linkIos_armv7DebugBuddyis-main-j2objcSharedLibrary
:ios_armv7DebugBuddyis-main-j2objcSharedLibrary
:compileIos_armv7DebugBuddyis-main-j2objcStaticLibraryBuddyis-main-j2objcObjc
:createIos_armv7DebugBuddyis-main-j2objcStaticLibrary
:ios_armv7DebugBuddyis-main-j2objcStaticLibrary
:compileIos_armv7ReleaseBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
:linkIos_armv7ReleaseBuddyis-main-j2objcSharedLibrary
:ios_armv7ReleaseBuddyis-main-j2objcSharedLibrary
:compileIos_armv7ReleaseBuddyis-main-j2objcStaticLibraryBuddyis-main-j2objcObjc
:createIos_armv7ReleaseBuddyis-main-j2objcStaticLibrary
:ios_armv7ReleaseBuddyis-main-j2objcStaticLibrary
:compileIos_armv7sDebugBuddyis-main-j2objcSharedLibraryBuddyis-main-j2objcObjc
```

Thank you so much.

**Comment by advayDev1** [comment]
great.  hopefully by next week you've also gotten your main Xcode app working with the new prebuilt libraries and such.

i will close this bug as norepro (errors in user code, unsupported flags) and dupe to #164 (for the arc flag).

also i recommend we create a policy of never supporting not-yet-mature flags or features of j2objc, @brunobowden

**Comment by advayDev1** [comment]
also @confile , please file a detailed bug with source to @tomball over in j2objc about the issue with using --static-accessor-methods (namely a constant in a Java interface that is then implemented in a concrete class causes a -Wprotocol error)

**Comment by confile** [comment]
@advayDev1 Okay I file an issue.
