### ISSUE TITLE
tasks.findByName magically *creates* tasks, preventing future mutation (!!)

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#156]
after hours of debugging the entirely unhelpful message:
```
Caused by: java.lang.IllegalStateException: Cannot add Mutate rule 
'org.gradle.language.base.plugins.ComponentModelBasePlugin$Rules#closeSourcesForBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.language.base.ProjectSourceSet)'
for model element 'binaries' when element is in state GraphClosed.
```

the issue is the use of findByName('assemble').  This cause Gradle to *create* the assembly task, preventing modification of say the binaries later.

Pulpit:
This is why I hate things that have too much magic.  Only a line by line binary search caused to me find this, since the stack trace is thrown much later when the project's tasks have to be resolved, and nowhere near either the mutation or the findByName.  SHEESH!

@brunobowden I'm fixing this to allow native dependencies, hopefully you can rollback your workaround for plugin syntax once I merge this in.

**Comment by brunobowden** [comment]
This'll be something else I ask about tomorrow.

**Comment by brunobowden** [comment]
Wow, that's an amazing find Advay

**Comment by brunobowden** [comment]
@bigguy - explained that this happened for certain tasks, I can understand why it's surprising

**Comment by advayDev1** [comment]
good to know i'm not imagining things =)  thanks for checking.
