### ISSUE TITLE
Set Warnings as Errors to dev style guide

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#165]
Setting Java warnings as error should be in a dev style guide for this plugin. I tried: 
```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            // Warnings as errors
            options.compilerArgs <<  '-Werror'
        }
    }
}
```
and 
```
compileJava {
 options.compilerArgs << "-Werror"
}
```
None of them break java compile when there are warnings.

**Comment by advayDev1** [comment]
I don't think this should be in a j2objc-gradle doc, it is a general java/gradle thing.  A particular user's choice of which warnings to set as errors is IMO related to their project, org, etc.
