### ISSUE TITLE
Spin 0.3.0-alpha release

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#166]
My last four PRs (in progress) will make some breaking changes to our API, namely:
- translateClassPaths are no longer relative to project/lib, but instead just project.  clients that used this param must add the 'lib/' themselves.
- j2objcConfig must end with a call to configureNativeBuild()
- shared .dylib libraries are disabled by default

Can I request a 0.3.0-alpha spin after these all go through?

**Comment by brunobowden** [comment]
Sure, I've got some other changes too

**Comment by advayDev1** [comment]
Great, shall we make it a standard to have a release spin issue like this where we document the known changes?  That way we can make sure README.md in the version is good?

**Comment by brunobowden** [comment]
Busy for a while now. I'll get through all of this later tonight.

**Comment by advayDev1** [comment]
All pending bugfixes for 0.3 should be PR/merged into release_v0.3.0-alpha not master

**Comment by brunobowden** [comment]
Plugin published, release created. Have a look @advayDev1 and let me know if everything is order. Then shall I go ahead and delete the release branch?
