### ISSUE TITLE
Pure Gradle build including iOS project

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#170]
Maybe this is just for curiosity sake for others, but at this point I've got a gradle-only build for the ios-side of things too.  A './gradlew build' from my repo root now builds the tools, libs, Android App, and the iOS app.

https://gist.github.com/advayDev1/0ef4ef455b010ba5d2ad

Not sure if this falls within the scope of this plugin though.  Feedback welcome on whether or not we should incorporate this!

**Comment by brunobowden** [comment]
I think this does come in the scope of the plugin. It's very useful for
your continuous build server, or test pipeline, where you obviously can't
run any steps manually.

The question to my mind is what the defaults are? Should it try by default
to build everything or default to configuring Xcode then provide the option
to also do the build through Gradle? My vote is for the latter but
certainly this should be in the plugin.

**Comment by advayDev1** [comment]
Configuring xcode automatically happens rarely - once a project config change (i.e. the pod task), or never for people like me who don't use pods.
Building xcode project happens well on every build.

However, I believe building xcode project should be a separate Plugin class (even if it is within the same Plugin jar).  That plugin could be applied on a separate gradle build file, which for example has UI Objc code or partially migrated Objc libraries (like I do).

**Comment by brunobowden** [comment]
Given the new plugins syntax, I'm not sure if you can have two different classes within the same plugin... not sure if you'll be forced to do a distinct task instead:

```
plugins {
  id "com.github.j2objccontrib.j2objcgradle" version "0.2.2-alpha"
}
```

**Comment by advayDev1** [comment]
@brunobowden, I open-sourced (part of) my internal Xcode build plugin here:
https://github.com/madvay/mixc-build/

Note that it uses the Gradle 3.0 "model-based" plugin design instead of the Gradle 2.4 "extension-based" plugin design:
https://github.com/madvay/mixc-build/blob/master/src/main/groovy/com/madvay/tools/build/mixc/MixcPlugin.groovy
see https://docs.gradle.org/current/userguide/new_model.html

**Comment by advayDev1** [comment]
I think we decided that we would not integrate this into this project.  Either way it wouldn't be possible until j2objc-gradle upgraded to Gradle 2.5 at least.

**Comment by brunobowden** [comment]
I'd like to use Gradle 2.6 when it stabilizes for plugin testing. At that
point, I presume we can also test against multiple versions of Gradle for
builds which will aid the maintenance. I think we should continue to
support 2.4 but I'm fine with adding features limited to later versions.

**Comment by advayDev1** [comment]
that seems quite complicated from a support perspective.
i think it is warranted only if the quantity of users on the multiple versions is sufficient.

still, a pure gradle build of iOS inherently requires a 2nd gradle project (for the user, I'm not talking about our plugin code).  our plugin cannot at runtime create that project.

**Comment by brunobowden** [comment]
If people need an older version of Gradle, they can just refrain from using
an updated version of the plugin.

**Comment by advayDev1** [comment]
ah yes, i see.  i thought you meant support at vX versions Y and Z of gradle.

**Comment by brunobowden** [comment]
I did mean that but now I'm changing my mind to agree with you. We may need
a crossover point if we're doing a big transition like Gradle 3.0.

**Comment by advayDev1** [comment]
sure.  i think updating our gradle version is independent of this though and we may still want to do it.

(see the issue re: creating a 2nd project within a plugin)
