### ISSUE TITLE
Output some Stats when running the plugin

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#171]
Output the number of files translated and the number of input files used by the plugin. This might give an indication if everything was included which is needed.

**Comment by brunobowden** [comment]
I'm not sure exactly what the gradle style is for this. Generally I don't
see any output unless something has failed. A setting for some optional
would seem more reasonable.

**Comment by advayDev1** [comment]
Please let's not add more settings for this. We have too many settings as is I think.

Use logger.debug or similar for 'spew' output like this; many other plugins do.

**Comment by advayDev1** [comment]
I don't see any other plugins doing this.
A number is much less helpful than the actual list of files and can easily miss an error: let's say it translated an extra spurious file and skipped one needed file, you'll see the correct number. 
The actual list of files you will already get on a build with --info or --debug.
