### ISSUE TITLE
Xcode does not find source when translateFlags "--no-package-directories" is omitted

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#173]
When I don't use the ``--no-package-directories`` flag Xcode does not find the correct sources.

![sharedclass_m](https://cloud.githubusercontent.com/assets/64265/8149741/22ab01f4-12cf-11e5-811e-ff2293e817a6.png)

**Comment by advayDev1** [comment]
Again this is #128 and #129 - Xcode should NOT be building the j2objc .m and .h files.  They are already built.
