### ISSUE TITLE
Settings and documentation for choosing native platforms to build

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#177]
As a side note it is very hard to understand why the j2objc gradle plugin adds a lot of new tasks for different platforms. When running the Xcode task all platforms where compiled. I suppose that incremental compilation will do the incremental compile for each platform. This tasks a lot of time. You can be sure that not all platforms are used by the plugin user. So it might be better to have a flag in the plugin's extensions to specify the used platforms. A comment should make clear where to find them in Xcode settings.

**Comment by advayDev1** [comment]
Definitely; I tried implementing this earlier but it was impossible before.  I will do this in PR #158.  
Not just documentation but a setting that lets you control the architectures you need/want.

I do want to clarify: this has nothing to do with /xcode/ settings.  It is a configuration of our plugin.

**Comment by confile** [comment]
But, you have to check in your Xcode project for which platform you develop. Am I right?

**Comment by advayDev1** [comment]
No you will have to specify in j2objcConfig which platform(s) you want if you don't want all of them.  (simple list flag).

Most large projects develop universal binaries and simulator binaries and have unit tests.  Which means by default they need all possible platforms that we already have.

**Comment by confile** [comment]
@advayDev1 Sorry for my stupid questions I started ios developent 2 months ago. Can you please explain how do I know which platform I have to choose. Usually I create an Xcode project and it might does it for me. So I have no idea what to choose and what not.

**Comment by advayDev1** [comment]
By default, I believe Xcode iOS projects are for all platforms.  So you do indeed need to build all platforms if you use these defaults.  Btw, why do you believe you do not need to build for all platforms?  If you want to use all of: iPhone 4s through 6 plus, iPads, simulators, etc.?

**Comment by confile** [comment]
@advayDev1 I am not sure about what I meant here. :-) So when I build form iPhone 5, 5s,5c,6,6Plus, iPad Air 1,2 then you say I just need all platforms right?

**Comment by advayDev1** [comment]
yep, because I assume you need simulators for testing as well.  i believe that covers all the platforms.

but if someone only needed iPhone 6plus or something, they could set supportedArchs, per #158

**Comment by confile** [comment]
@advayDev1 Thanks now I get it.
