### ISSUE TITLE
Setup Travis continuous testing

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#178]

**Comment by brunobowden** [comment]
Absolutely agreed on this. Along with a sample project, this will get a lot
of test coverage.

**Comment by advayDev1** [comment]
As long as Travis can run j2objc and clang, yep =)

**Comment by advayDev1** [comment]
This should be much more valuable now that we have hermetic unit tests.

**Comment by advayDev1** [comment]
I just got this done for one of my other open-source projects.  I also have a dedicated account 

It will be done in two steps:
1. A direct commit from the API account that just enables travis.
2. A second commit (that will go through normal PR to @brunobowden) that configures our travis tests.
