### ISSUE TITLE
Xcode: Reference source files

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#194]
re: #192 
We should remember that we could manipulate the Xcode project file with our own java code to support browsing of source files (by adding 'referenced files'). I don't think we have to give up on it just b/c cocoapods doesn't want to support this. This is one of the issues using an intermediary between Gradle and Xcode, we are at the mercy of that intermediary.

@confile

**Comment by confile** [comment]
+1

**Comment by advayDev1** [comment]
The podspec is correctly referencing the files and no longer copying them.
