### ISSUE TITLE
Error: "ld can't map file, errno=22 file" -bundle_loader /../Debug-iphoneSimulator/MyApp.app/MyApp

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#200]
``gradle j2objcXcode`` task works without problems but when I compile my xcode project I get the following error: 

![majestella_xcworkspace](https://cloud.githubusercontent.com/assets/64265/8268202/a67cb890-177c-11e5-964e-64e3cbca9a58.png)

Here is the image as text:

```
Ld /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator/MajestellaTests.xctest/MajestellaTests normal x86_64
    cd /Users/mg/Documents/Android/Android-Studio/Majestella/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.4
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator -F/Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/Developer/Library/Frameworks -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/Developer/Library/Frameworks -filelist /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Intermediates/Majestella.build/Debug-iphonesimulator/MajestellaTests.build/Objects-normal/x86_64/MajestellaTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -bundle_loader /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator/Majestella.app/Majestella -Xlinker -objc_abi_version -Xlinker 2 -framework XCTest -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Intermediates/Majestella.build/Debug-iphonesimulator/MajestellaTests.build/Objects-normal/x86_64/MajestellaTests.swiftmodule -mios-simulator-version-min=8.4 -Xlinker -dependency_info -Xlinker /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Intermediates/Majestella.build/Debug-iphonesimulator/MajestellaTests.build/Objects-normal/x86_64/MajestellaTests_dependency_info.dat -o /Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator/MajestellaTests.xctest/MajestellaTests

ld: can't map file, errno=22 file '/Users/mg/Library/Developer/Xcode/DerivedData/Majestella-grakkgsgamubapejewabyyvcxynu/Build/Products/Debug-iphonesimulator/Majestella.app/Majestella' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by confile** [comment]
@brunobowden Do you have an idea on this. It happens after some of your latest commits?

**Comment by confile** [comment]
@brunobowden May be it helps to post my config: 

```
j2objcConfig {

    generatedSourceDirs "build/source/apt", "build/source/base"

    xcodeProjectDir "${projectDir}/../ios"   // Xcode workspace directory
    xcodeTarget "ios" 

   translateArgs "--no-package-directories"
    translateArgs "--prefixes", "prefixes.properties"
    translateArgs "-use-arc"
    translateArgs "--doc-comments"
    translateArgs "--build-closure"
    translateArgs "--generate-deprecated"

    extraObjcCompilerArgs '-fobjc-arc'

    translateClassPaths "libs/json-20140107.jar", "libs/javax.inject-1.jar", "libs/auto-factory-1.0-beta2.jar", "libs/auto-service-1.0-rc2.jar", "libs/javawriter-2.5.1.jar", "libs/guava-18.0.jar"
    translateSourcepaths "${projectDir}/libs/dagger-2.0.1-sources.jar"

    translateJ2objcLibs "j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"

    filenameCollisionCheck = true

    finalConfigure()
}
```

Anything that looks strange?

**Comment by brunobowden** [comment]
Nothing I can easily see. I'd suggest commenting on this public StackOverflow bug which seems connected to yours to see if they figured anything out:

http://stackoverflow.com/questions/30266451/xcode-compile-error-errno-22

Note the same error message and that it was for the -bundle_loader parameter.

Please in future, always copy and paste the contents of the error rather than just the screenshot. When I was searching for the `../Majastella.app/Majastella` error message within the command line, it took me a long time to read through each line and find that it was the `-bundle_loader` flag. When you copy and paste the text, then it's very fast and simple to do a search within the text. Ultimately making it easier for me (or others), is a good way to make it easier to help you... which make you more likely to get an answer ;-)

If StackOverflow doesn't work, then can you share a copy of the full project with me as that may be a better way for me to work with the issue. If you can reproduce it with a smaller test case, that would obviously be even better.

**Comment by brunobowden** [comment]
Another possibility is a binary search within the j2objc plugin commits. If you notice it broke between before and after a specific commit, then that also makes it much easier to track down. If you're building the plugin locally, reset to specific commits historically. Assuming you get a commit that works, then advance until you find one that fails... then step backwards until you find something that works. Then iterate like that until you find the point where it changed. Here's the command to do this:

    git reset --hard c14809fa

This is a time consuming process but I've done this many times before when nothing else worked.

**Comment by brunobowden** [comment]
Also, change the title to what's most distinctive. In this case it's the following:

    Error: "ld can't map file, errno=22 file" -bundle_loader /../Debug-iphoneSimulator/MyApp.app/MyApp

The important parts are the linker error, `errno=22` and the `-bundle_loader` flag. The `linker command failed with exit code 1` is for any general error with the linker, so it's very vague. The more specific error is much more helpful in diagnosing the problem. It's kinda like someone saying "I can't start my car", compared to someone saying "I can't start my car because the key wouldn't fit". The latter example, is much more helpful in me thinking "maybe it's the wrong key" or "maybe the key is broken". Whilst with the former, I really don't know.

**Comment by brunobowden** [comment]
I believe you should be able to drop this line:

    translateSourcepaths "${projectDir}/libs/dagger-2.0.1-sources.jar"

The dagger source doesn't need translation. It's only use is to generated more java source files - those generated files need translation. After the generation, dagger isn't used during runtime. It's only a compile time activity.

**Comment by confile** [comment]
@brunobowden Thanks for the advice. I copied in the error as text. The project is still to big to share I tried to create a smaller version.

**Comment by brunobowden** [comment]
Any update on this @confile? I've added it to the 0.3 release. Any other bugs that we still need to work out?

**Comment by confile** [comment]
@brunobowden No updates on this issue. This is the last one before I can use the new plugin. 

Yes please add the following issues to the 0.3 release:

https://github.com/j2objc-contrib/j2objc-gradle/issues/191
https://github.com/j2objc-contrib/j2objc-gradle/issues/133

**Comment by brunobowden** [comment]
Added #191 and #133

**Comment by confile** [comment]
@brunobowden I was wrong. The error does not depend on your commits. I couldn't figure out what this error causes.

**Comment by brunobowden** [comment]
@Confile - is this still an issue? Anything else major preventing you from using HEAD?

**Comment by confile** [comment]
Yes it is still an issue. What do you mean by HEAD? I suppose you mean the latest master.

**Comment by brunobowden** [comment]
Does it work against an old version like 0.2.2? If so then it's a commit between then and now that caused the problem. If not, then it's more likely to be an Xcode configuration issue.

Try it against master and see if you can learn anything more about what's happening. Also, see the following notes about your j2objcConfig:

    // You're including "javax.inject-1.jar" in both translateClassPaths AND translateJ2objcLibs
    // It's best that you use the same version of Guava as J2objc: version 14.0.1
    translateClassPaths "libs/json-20140107.jar", "libs/javax.inject-1.jar", "libs/auto-factory-1.0-beta2.jar", "libs/auto-service-1.0-rc2.jar", "libs/javawriter-2.5.1.jar", "libs/guava-18.0.jar"

    // Glad this is working for you:
    translateSourcepaths "${projectDir}/libs/dagger-2.0.1-sources.jar"

    // This should be translateJ2objcLibs = 
    translateJ2objcLibs "j2objc_annotations.jar", "j2objc_guava.jar", "javax.inject-1.jar", "jsr305-3.0.0.jar"

    // This is enabled by default so you can drop this line:
    filenameCollisionCheck = true

**Comment by confile** [comment]
@brunobowden the latest j2objc source now uses guava 18.

**Comment by brunobowden** [comment]
Great - I should be paying better attention to that then ;-)

Does the same problem occur with version 0.2.2? If so, then it's a problem
with your Xcode configuration.

If it works with 0.2.2. Then try building it at version 0.2.2 and see if
that works. If the old built version works, then build against 0.3.0
release and see if it fails. If you get one build that works and another
that fails, you can do a binary search in between to find the problem.

Please add comments as you try out these steps.

**Comment by confile** [comment]
@brunobowden I cannot tell you the answer because this error https://github.com/j2objc-contrib/j2objc-gradle/issues/261 is blocking the way to the Xcode error.

**Comment by advayDev1** [comment]
it appears we cannot reproduce this at the moment.  removing from 0.4

**Comment by advayDev1** [comment]
i see this occasionally with xcode in a non-j2objc setting.  without further repro details or any updates, i think we should close for now.  please re-open if/when you can reproduce with details.

**Comment by fferri** [comment]
@brunobowden never heard of `git bisect`? :P
