### ISSUE TITLE
Improvement: Parallel native build

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#202]
Is it possible to build paralel to speed up compilation. When you build j2objc from source you can do that as well.

**Comment by confile** [comment]
@advayDev1 I think your are the expert on native build. Is this possible?

**Comment by advayDev1** [comment]
Already supported in Gradle 2.4.  Make sure you are using this configuration:
https://docs.gradle.org/current/release-notes#parallel-native-compilation

**Comment by confile** [comment]
@advayDev1 Should we add this to the docs?

**Comment by confile** [comment]
@advayDev1 Okay this means you do not have to configure anything in Gradle 2.4 because the default is the number of cores on your computer right?

**Comment by advayDev1** [comment]
Yep
