### ISSUE TITLE
def => explicit types

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#205]
Goal is to replace all uses of `def` with explicit types:

    // Before
    def count = 4
    def method() {
        return "string"
    }

    // After
    int count = 4
    String method() {
        return "string"
    }

The Groovy style guide indicates that it's a choice of using `def` or explicit types:

    So make a choice, either use def or a type.

Though `def` is more of the idiom for Groovy, explicit types help with correctness, catching errors in the IDE as a def isn't as constrained:

    When using def in Groovy, the actual type holder is Object (so you can assign any
    object to variables defined with def, and return any kind of object if a method is
    declared returning def).

Thus, a def is less restrictive on types. According to the following link in the Style Guide, it can be thought of as an alias to `Object` and the programmer indicating that they don't care about the type: http://www.groovy-lang.org/semantics.html#_variable_definition

**Comment by brunobowden** [comment]
@confile - this is something where it would be useful to get your help. The changes are relatively straight forward and it'll help you get familiar with the new architecture.

I fixed up J2objcUtils in PR #198.

**Comment by confile** [comment]
@brunobowden Okay I will do that.

**Comment by brunobowden** [comment]
Still needs a little more work

**Comment by brunobowden** [comment]
@confile - please comment here now

**Comment by brunobowden** [comment]
Still not fixed but only a few left
