### ISSUE TITLE
Remove "J2objc" prefix from all filenames (kept for config and tasks)

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#210]
The `J2objc` was useful when it was a single file. Since moving in to the new Plugin architecture, it obscures the purpose of classes and files, as you have to look in more detail to parse it. Since the plugin is in an isolated GitHub repository and doesn't have to interact with other code except as a plugin, I don't believe there's any concerns about collisions.

My plan is to remove `J2objc` from all files and classes.

The `j2objcConfig` config and all tasks will retain the `j2objc` prefix.

**Comment by brunobowden** [comment]
@advayDev1, @confile - please comment.

**Comment by confile** [comment]
I strongly support this.

**Comment by brunobowden** [comment]
Thanks @confile.

@advayDev1 - please give your sign off and then I'll go ahead.

If there's any other suggestions you have for moving around code or renaming files, this would be a good time to suggest it.

**Comment by advayDev1** [comment]
I'm fine either way.  The only loss is annoying blame history.  But if this makes your development lives easier, go for it.

**Comment by brunobowden** [comment]
It appears that the file history, including blame is still preserved:

https://git.wiki.kernel.org/index.php/GitFaq#Why_does_Git_not_.22track.22_renames.3F

The two tools for assigning blame, git-blame(1) and git-annotate(1) both use the automatic rename detection code to track renames.

Great Linus rant on tracking renames if you'd care to read it:

http://permalink.gmane.org/gmane.comp.version-control.git/217

**Comment by advayDev1** [comment]
Oh I understand that git keeps track of the content vs. the file, it is just that in github.com's GUI 'blame' view at least for my own repos it only sometimes tracks the lines across renames.

**Comment by brunobowden** [comment]
It seems to vary with the use of the --follow flag. I'm wondering if it
should be done in two commits in a single PR... first to do only a rename.
Then secondly to rename all the classes.

**Comment by advayDev1** [comment]
sgtm, and then a single PR to merge both those commits?
we'd violate the always-builds rule, but i think it makes sense

**Comment by brunobowden** [comment]
I'll do it a slightly weird way...
1) Do the `git mv`, changing only the file names and then commit
2) From a separate copy, do the rename within the IDE, replace the src/
contents and then make that the second commit

...in many ways I trust the IDE rename better than my own changes. At
least, I'll experiment.

**Comment by advayDev1** [comment]
Actually this should work fine because it is Groovy.  No rule that the class name == filename right?

**Comment by brunobowden** [comment]
Android Studio complains if they're different... and it would make sense
for them to be same.

**Comment by advayDev1** [comment]
:)  i was agreeing with your steps.  in that doing (1) and committing it seems should build just fine

**Comment by advayDev1** [comment]
@brunobowden - please keep the J2objc prefix on the plugin class itself.  Avoids collision with `Plugin<>`

**Comment by brunobowden** [comment]
Agreed.

I won't be able to do this until this evening, along with the
translateXXXpath changes. Please feel free to go ahead with testing if you
think it's worthwhile. I will be including some better testing around the
different tasks.

**Comment by advayDev1** [comment]
@brunobowden - went ahead and did this already because I had other pending work.  See PR
