### ISSUE TITLE
def => explicit types fixes 

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#212]
Switching to Java types from Groovy missing types:  

- J2objcNativeCompilation L45 task
- J2objcPlugin L44 evaluatedProject
- J2objcPluginExtension L183, L199, 218, 219

**Comment by brunobowden** [comment]
@confile - I didn't understand what this issue is for? Is it just a duplicate for #205? Can you give an example or two?

**Comment by confile** [comment]
You have to look at the line numbers in the files there you see that explicit types are missing.

**Comment by advayDev1** [comment]
Right: So we should just reopen #205 , and still close this as dupe.

**Comment by brunobowden** [comment]
@confile - good point on this

Please close this and reopen #205. If you'd ever like to link to specific
line numbers, then here's an example for the hyperlinks:

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy#L45

**Comment by confile** [comment]
@brunobowden I am no author here on github so I cannot reopen issues.

**Comment by brunobowden** [comment]
Not finished yet...

**Comment by brunobowden** [comment]
Fixed by PR #232
