### ISSUE TITLE
unset xcodeProjectDir throws exception: Ambiguous method overloading

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#226]
For the following line, when `xcodeProjectDir == null`, it could match either File(File, String) or File(String, String), so it throws an exception as it's ambiguous. Even though xcodeProjectDir is explicitly type to String.

```
    @OutputFile
    File getPodFile() { new File(project.j2objcConfig.xcodeProjectDir, "Podfile") }
```

Here's the exception:
```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
	[class java.lang.String, class java.lang.String]
	[class java.io.File, class java.lang.String]
	at com.github.j2objccontrib.j2objcgradle.tasks.J2objcXcodeTask.getPodFile(J2objcXcodeTask.groovy:53)
```

**Comment by advayDev1** [comment]
groovyness:
doesn't matter that xcodeProjectDir is of type String.  We are using Groovy in its (default) dynamic typing scheme, so method resolution is strictly at runtime.  At runtime, null can have any non-primitive type.

we should probably just have an explicit validation step before that that also throws a meaningful message like if using the xcode task, you must set that config flag.

**Comment by brunobowden** [comment]
PR #227 has that validation step when the action is called
