### ISSUE TITLE
Multi-project integration testing

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#230]
This is a caricature of my internal projects that use this plugin.
![image](https://cloud.githubusercontent.com/assets/11729521/8337843/36d4a230-1a62-11e5-9952-04529b664134.png)

You'll note it exercises many features:

- Simple java Project dependencies
- Duplicate dependencies (i.e. X depends on C directly but also on C transitively through Y)
- Build-closure translation of an external source jar
- Migrating JNI code to pure objective c
- Combining hand-written objective c code with j2objc translated objective c code
What else should we be testing for a 'complex' project?

**Comment by confile** [comment]
@advayDev1 could you please post some more details of the build.gradle files. That would at least help me with the sample branch I am pushing.

**Comment by brunobowden** [comment]
- Generated code, e.g. Dagger2 and AutoValue, not sure if we should just ignore Dagger1
- The incremental build after files are deleted or added in various different ways

**Comment by brunobowden** [comment]
@advayDev1 - I've taken to modifying your original comment

**Comment by advayDev1** [comment]
@brunobowden - please let's not edit comments from other authors in the future.  i know both of us /can/ but it is really confusing since there is no edit history AFAICT.  nor indication that someone else touched the comment.  scary for github really :P

I unedited the comment (as close as i could).

**Comment by advayDev1** [comment]
@brunobowden , this is I think what I removed.  Also those aren't already in the current test project, but are things we'd like to also have:

- Generated code, e.g. Dagger2 and AutoValue, not sure if we should just ignore Dagger1
- The incremental build after files are deleted or added in various different ways
- Cycle Finder task, this involves creating two intentional memory cycles, marking one invalid and checking the other is counted

**Comment by confile** [comment]
@brunobowden We should not support Dagger1. As far as I remember you cannot translate it because it uses reflection which is not available in objective-c. So forget about Dagger1.

**Comment by confile** [comment]
@advayDev1 I do not understand you drawings. The legend shows symbols which occurs in every box. Does not help. Better to tell where the j2objc plugin is located.

**Comment by brunobowden** [comment]
@advayDev1 - apologies Advay, I'll refrain in the future from modifying comments

**Comment by advayDev1** [comment]
@confile - every dashed box is a distinct application of the j2objc plugin.

**Comment by advayDev1** [comment]
@brunobowden or @confile - can someone explain to me what it means to 'support dagger1' or any other system that generates code?  what is specific about these systems that our plugin needs to know anything about them or interact with them in anyway?

**Comment by brunobowden** [comment]
Dagger is a dependency injection framework from Square. It is supported by
J2ObjC but uses reflection and runtime reflection. Google reworked this to
make Dagger 2... which uses compile time code generation and dependency
graph evaluation... then does nothing at runtime. Both will likely be a
common use cases, particularly dagger 2.

Here's a thread on this:
https://groups.google.com/forum/#!topic/j2objc-discuss/RpDOjyJQD_o

**Comment by advayDev1** [comment]
@brunobowden - Sorry for not being clear.  I know and understand dagger.  I don't understand why our plugin needs to be aware of dagger at all.

**Comment by brunobowden** [comment]
It shouldn't do... but they're good common test cases.

**Comment by advayDev1** [comment]
got it

**Comment by confile** [comment]
I agree with @advayDev1 Our plugin does not needs to be aware of Dagger. This has nothing to do with the plugin.

**Comment by brunobowden** [comment]
This is just something for the tests, not the plugin itself.

**Comment by advayDev1** [comment]
So multi-project integration tests have been in the build for a while now.
What we've described above is an exhaustive system test, which I think requires #370 and can be tracked separately.
