### ISSUE TITLE
Accurate up-to-date checks for prefixes files

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#248]
If you change the contents of prefixes properties file basically everything needs to be redone.  Any prefixes files on the translateArgs should be InputFiles to all tasks.

**Comment by brunobowden** [comment]
I can take this on... it'll be a little tricky though as it's affected by both the prefixes file and command line arguments.

**Comment by advayDev1** [comment]
true.  instead of using @InputFiles, you could have an @Input that is the result of j2objcUtils' getPrefixes method.  might be much elegant.

also would not pollute the InputFile set for incremental tasks...

**Comment by brunobowden** [comment]
I was thinking abou this already. I was little concerned about the time for calling that commend multiple times, including the multiple file reads... but I think with caching, it should be fine.

**Comment by brunobowden** [comment]
When that happens, it should skip any kind of incremental compile? I'm not sure how to detect that change though.

**Comment by advayDev1** [comment]
@brunobowden :
1) yeah i think we should have each task have an @Input with getPrefixes.  Then in the task action we can have a variable for it ('cache').  Better to be slower and correct.

2) When an `@Input` input that is not an `@InputFiles` input changes, incremental tasks are treated as if all input files changed (see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.incremental.IncrementalTaskInputs.html, bullet 3, section 1).  So by making sure we use getPrefixes instead of making the prefixes.properties file an @InputFile, incremental tasks (namely translation) should work correctly out of the box.

**Comment by brunobowden** [comment]
Perfect. Thanks for the pointers.

**Comment by advayDev1** [comment]
doing this since it has bitten me :)
