### ISSUE TITLE
Best practice settings, e.g. "--static-accessor-methods"

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#260]
Add support for translateArgs "--static-accessor-methods" to generate accessor methods for static variables and enum constants.

**Comment by brunobowden** [comment]
If you do translateArgs '--static-accessor-methods', then does it work as
you expect it to?

**Comment by confile** [comment]
@brunobowden It does work fine with the old one file plugin. I still cannot work with the new plugin so I currently does not use it. As soon as it works I can give more input.

**Comment by brunobowden** [comment]
@advayDev1 - I think we should turn this in to a general discussion on suggested flags that people should use, allowing them to configure them all in one go. Let's discuss this more when J2ObjC gets close to their final release.

**Comment by advayDev1** [comment]
I think if such a flag should be introduced it should be at the j2objc level.  For example, they recently introduced --swift-friendly to do exactly what you asked and some other swift-friendly things:
https://github.com/google/j2objc/pull/644
