### ISSUE TITLE
Output stderr, stdout and cmd line for projectExec failures

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#267]
When cycleFinderTask or translateTask fails with the command line call. The internal error is obscured, making it harder to debug. The output should be captured and then output as part of the thrown exception. It should also show the full command line and perhaps the suggestion of trying to run it with javac to test that it works correctly. This is a lesson from issue #261 by @confile.

Currently a user will have to enable --debug mode and then dig through the debug output to see what command is run and then try debugging it.

Example of the current output which doesn't show any helpful messages:

```
:j2objcTranslate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':j2objcTranslate'.
> Process 'command '/Applications/J2Objc/j2objc-0.9.7b/j2objc'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.
```

**Comment by confile** [comment]
This is a great idea!

**Comment by brunobowden** [comment]
I've been testing this by adding `--nonsense` flags to each of the tasks. My feeling is that this is going to be a great change for tracking down tricky build issues.

Previously it would say:

    Process 'command '/Users/brunobowden/dev/j2objc-versions/j2objc-0.9.7/j2objc'' finished with non-zero exit value 1

Now it produces some very helpful error messages as follows:

    ...
    :base:j2objcCycleFinder UP-TO-DATE
    :base:j2objcTranslate
    Standard Output:

    Error Output:
    j2objc: invalid flag: --nonsense
    Usage: j2objc <options> <source files>
    use --help for a list of possible options

    :base:j2objcTranslate FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':base:j2objcTranslate'.
    > Error Output:
      j2objc: invalid flag: --nonsense
      Usage: j2objc <options> <source files>
      use --help for a list of possible options

      Command Line:
      /Users/brunobowden/dev/j2objc-versions/j2objc-0.9.6.1/j2objc -d ...
      Caused by:
      org.gradle.process.internal.ExecException: Process 'command ...

**Comment by brunobowden** [comment]
@advayDev1 - see example above for how the error output has changed. This is going to be a great help for tricky issues.

**Comment by advayDev1** [comment]
@brunobowden - totally agree.  waiting for you to merge it in :)
