### ISSUE TITLE
Automatic configuration of j2objcConfig

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#268]
Ideally the plugin would do all the configuration automatically, both to make it easier to use and reduce the chance of errors. Ideally it should derive all the config information it needs from the Java plugin and the only config it should need is pointers to the Xcode workspace and target.

1. `compile or testCompile` dependencies of standard libraries would link in the appropriate J2ObjC library or source jar. Warn if the version of the J2ObjC library is different.
1. Configure multi-project dependencies. Should it add the plugin automatically for dependencies? Certainly `dependsOnJ2objcLib` should be automatically configured based on project dependencies.
1. Can we infer the `generatedSourceDirs, translateClassPaths & translateSourcepaths` and possible eliminate them from general usage? Source sets have a `runtimeClasspath` output.

In general, I think we should push towards minimizing the need to use j2objcConfig. That'll make our own lives easier and other people as well.

**Comment by brunobowden** [comment]
@advayDev1, @confile - please add your thoughts on this

**Comment by confile** [comment]
I like you second idea very much. This was and still is a source of error for me. Automatically detect generatedSourceDirs would also be great but you still have to exclude things like annotation processors yourself.

**Comment by brunobowden** [comment]
Can you give an example of excluding the annotation processors?

**Comment by confile** [comment]
Sure, my annotation processors are in folders containing ``processor``. So I do: 

```
j2objcConfig {
  
  testMinExpectedTests 0

  translatePattern {  
    exclude '**/*processor*'
  }
  finalConfigure()
}
```

**Comment by advayDev1** [comment]
I think except for transitive dependencies, 1 (maven source jar translation), 2 (autoConfigureDeps for project dependencies), and 3 (new generated source support) are done for 'common' cases.  We can't handle everything though.

Please re-open @brunobowden if you think the remaining bug #503 is not sufficient.
