### ISSUE TITLE
Cocoapods use_frameworks! not building

### ISSUE THREAD

**Issue by hwchong** [j2objc-contrib/j2objc-gradle#269]
Hi, being new to Cocoapods, I'm trying to mix my J2OBJC project with some Swift and am requiring to use the `use_frameworks!` property in my Podfile. 

The problem is that while all my other pods are building and being turned into a framework, none of my shared translated code is being turned into a framework. 

Does anyone have any idea why this is doing that?

**Comment by confile** [comment]
I think that ``use_frameworks`` works only with Swift pod. Your shared code is in an Objective-C pod.

**Comment by hwchong** [comment]
It seems to work on other ObjC pods e.g. https://github.com/jdg/MBProgressHUD

**Comment by advayDev1** [comment]
Cleaning up untouched bugs - please re-open with more details if this is still an issue.

**Comment by maxbritto** [comment]
I seem to have the same problem : every other pod got packed as a framework but my shared code doesn't.
I end the compilation with a link error : 
```
ld: library not found for -lPods-TARGETNAME
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I don't know if that j2objc is the cause but it's  definitely the only pod that doesn't generate a framework

By the way I use XCode 7.

**Comment by maxbritto** [comment]
I finally found a way to build (and link), it was an issue with cocoapods which added the *Pods-TARGETNAME.a* and *Pods-TARGETNAME.framework* to the **Link binary with libraries** (in my target **Build Phases**).
I also found the way to generate the framework if you want it. I just added this to the j2objc podspec : 
```
  spec.platforms = {
    "ios" => "8.0"
  }
```
It didn't fix my issue since it was something else but maybe you can find it useful.

**Comment by brunobowden** [comment]
@hwchong - please have a look at the comments from @maxbritto.

@maxbritto - thanks for looking in to this. I don't understand Cocoapods enough to know what's the best answer. In the case of the translated code, it shouldn't have any platform dependency at all. So just the widest possible compatibility is preferred.

I was wondering if I should just use this suggestion embedded in the Podfile:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0' 
```

**Comment by maxbritto** [comment]
@brunobowden To be honest with you I'm just starting to use cocoapods myself so I probably don't understand it better. I'm not sure this would be useful too, it seem to work well without it. I just wanted to understand why would this pod got generated differently from all the others in my podfile.

**Comment by brunobowden** [comment]
@maxbritto - can you try "ios" => "6.0" to see if that also work? iOS 6 should allow the widest possible compatibility, so I'd prefer to do that rather than iOS 8.0. Please see if you can notice any side effects from that.

**Comment by brunobowden** [comment]
@maxbritto - REPEAT - we need to find this out for the 0.5 release. Can you try "ios" => "6.0" to see if that also work? iOS 6 should allow the widest possible compatibility. I'd prefer to do that rather than iOS 8.0. Please see if you can notice any side effects from that.

**Comment by maxbritto** [comment]
I've started to work on this but I'm stuck with issues when trying to use a local version of j2objc-gradle plugin. I followed the Contributing.md guide but I must have missed something.
I've been able to build the jar and on my project, when using *buildscript* instead of *plugins* a have a linker error : 
```
:rainbowapi:linkDebugTestJ2objcExecutable
ld: library not found for -lmockito
```
Did I miss something or are there any required steps that are not on the contributing guide ?

**Comment by advayDev1** [comment]
Which version of j2objc and Xcode are you using?

**Comment by maxbritto** [comment]
j2objc 0.9.8.2 and XCode 7.0

**Comment by brunobowden** [comment]
@maxbritto, our apologies but the plugin doesn't work on Xcode 7.0, which I can see being a blocker for you. We need to get Xcode 7.0 working and then ask you to test this again.

**Comment by maxbritto** [comment]
No problem, I'll keep this on stand by until you let me know.

**Comment by advayDev1** [comment]
(@maxbritto  - btw, please consider using j2objc 0.9.8.2.1 (regardless of this plugin) instead of 0.9.8.2 - the j2objc team released the extra patch due to a build error in the original 0.9.8.2)

**Comment by maxbritto** [comment]
Thanks for the tip @advayDev1 ! Actually I did have issues with guava with the 0.9.8.2 build (don't remember how I fixed those though). I've updated it now.

**Comment by advayDev1** [comment]
yes, guava was not built correctly in 0.9.8.2

**Comment by brunobowden** [comment]
@maxbritto - can you try this issue again. It should now be working fine with Xcode 7. I'd like to clarify if this is an easy fix as we need to push out 0.5 to get feedback.

The new podspecs specify the deployment_targets which should suffice instead of the platform entry:
```
Pod::Spec.new do |spec|",
  ...
  spec.ios.deployment_target = '8.3'
  spec.osx.deployment_target = '10.8'
  spec.watchos.deployment_target = '2.0'
end
```

**Comment by maxbritto** [comment]
@brunobowden : I am not sure this is the best way to do it as it will only work with projects that have at least a deployment target equal to the one you specified. As an example, in my iOS project I have a deployment target to 8.0 and I can't install the pod with the spec you gave :
```
[!] Unable to satisfy the following requirements:

- `j2objc-rainbowapi-debug (from `/Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build`)` required by `Podfile`
- `j2objc-rainbowapi-debug (from `/Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build`)` required by `Podfile`

Specs satisfying the `j2objc-rainbowapi-debug (from `/Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build`)` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `j2objc-rainbowapi-debug (from `/Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by brunobowden** [comment]
@maxbritto - this will be good test to have. Try setting the minIosVersion in the j2objcConfig to 8.0 as well. Does it make sense to have that as the default? That seems to make sense to me as it's not as if the generated library are using advanced features of iOS.

```
j2objcConfig {
    ...
    String minIosVersion = '8.0'
}
```

**Comment by maxbritto** [comment]
@brunobowden : even after adding **minIosVersion** to 8.0 as you said, it still generates the podspec with **spec.ios.deployment_target = '8.3'** so cocoapods refuses to include j2objc in my project. Since the generated library doesn't use advanced features it doesn't seem useful to make it require something as high as iOS 8.3 (or even iOS 8 for that matter). Is it really needed that our j2objc library be generated as a framework ? It works well without it

**Comment by advayDev1** [comment]
Punting to 0.6 per call.
