### ISSUE TITLE
Unit test check fails if project has only one unit test

### ISSUE THREAD

**Issue by alexmetcalfe** [j2objc-contrib/j2objc-gradle#270]
Relatively minor issue, but caused me a bit of grief getting started with the plugin :)

In the TestTask line 134 the regex checks for the following:
```
int testCount = Utils.matchNumberRegex(outputStr, /OK \((\d+) tests\)/)
```
However if you have only one unit test the success message would be:

OK (1 test)

Which in turn fails the build.

**Comment by brunobowden** [comment]
Good catch. I'll get out a fix soon.
