### ISSUE TITLE
library not found for -lguava" Xcode error

### ISSUE THREAD

**Issue by alexmetcalfe** [j2objc-contrib/j2objc-gradle#273]
Hi,

I am currently getting an error in xcode when trying to run the app after running the following gradle tasks:

```
./gradlew clean build j2objcXcode
```
Error:
![screen shot 2015-07-11 at 5 42 48 pm](https://cloud.githubusercontent.com/assets/734514/8632933/a649713c-27f4-11e5-8187-c42b652a1666.png)

Note I also performed a pod install in the ios project with no luck. 

Am I missing a task here to get this running? My shared library is pretty simple with only a couple of POJOs.

Machine details:
OSX 10.10.4
java version "1.8.0_40"
gradle 2.4
xcode 6.4
CocoaPods 0.34.2

**Comment by alexmetcalfe** [comment]
I have raised the same question on SO

https://stackoverflow.com/questions/31380348

**Comment by brunobowden** [comment]
This is an unresolved issue in the 0.3.0 plugin version. I've been struggling to get to know CocoaPods well enough to learn how to fix this. It's the main bug I want to resolve before sharing the plugin again more widely. If you, @confile or others have any insights on CocoaPods, then I would be grateful for the help on this.

For some reason, the plugin is causing CocoaPods to add a reference to a non-existent library: `libPods-TARGET` (reported by @brunobowden) or `libPods-TARGET-j2objc-shared` (reported by @alexmetcalfe).

Grep'ing through the directory, the only references to the library are in the Xcode app directory and not in the shared library output, including Podfile's or similar. Which leaves me a little stumped. Here's part of what I see in Xcode:

```
./Xcode/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-TapTap-j2objc-base.xcscheme:               BuildableName = "libPods-TapTap-j2objc-base.a"
./Xcode/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-TapTap-j2objc-base.xcscheme:               BlueprintName = "Pods-TapTap-j2objc-base"
```

WORKAROUND

1. Delete the library from the "Frameworks" folder in Xcode:

![screen shot 2015-07-15 at 12 55 25 am](https://cloud.githubusercontent.com/assets/679339/8693899/7d6698ba-2a8f-11e5-9e88-beb55e0597f3.png)

2. If this doesn't work, then open the Pods-TARGET.debug.xcconfig (and release version) then remove the library reference from the "OTHER_LDFLAGS" argument line.

**Comment by brunobowden** [comment]
@hwchong - please comment if you have any insight on this

**Comment by confile** [comment]
I have been looking for this but no idea why this happens.

**Comment by alexmetcalfe** [comment]
@brunobowden what should the .xcconfig look like? I tried deleting the library under Frameworks which had the same error, then after removing the reference from both .xcconfig files I receive errors around not finding the guava library. I tried removing that as well but it then complains about not finding the "jre_emul" library.

Here is the contents of my debug .xcconfig file:

```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/j2objc-shared" /Users/alex/dev/bin/j2objc//include
LIBRARY_SEARCH_PATHS = /Users/alex/dev/bin/j2objc//lib /Users/alex/dev/projects/j2objc-contributors/shared/build/j2objcOutputs/lib/iosDebug
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/j2objc-shared"
OTHER_LDFLAGS = -ObjC -l"ObjC" -l"icucore" -l"jre_emul" -l"jsr305" -l"shared-j2objc" -l"z"
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by brunobowden** [comment]
This looks correct to me. I only notice a couple of difference compared to my .xcconfig (copied below):

1. I additionally have $(inherited) in HEADER_SEARCH_PATHS and OTHER_LDFLAGS
1. I additional line: OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)

Neither of these seem like they should make a difference.

```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/j2objc-base" /Users/brunobowden/dev/j2objc-versions/j2objc-0.9.6.1/include
LIBRARY_SEARCH_PATHS = /Users/brunobowden/dev/j2objc-versions/j2objc-0.9.6.1/lib /Users/brunobowden/dev/taptap/base/build/j2objcOutputs/lib/iosDebug
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/j2objc-base"
OTHER_LDFLAGS = $(inherited) -ObjC -l"ObjC" -l"base-j2objc" -l"guava" -l"icucore" -l"javax_inject" -l"jre_emul" -l"jsr305" -l"z"
OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by brunobowden** [comment]
@alexmetcalfe - Guava isn't necessary unless some of your code is using it. Nonetheless, I'd suggest including guava, jre_emul and all the other standard libraries. They're included automatically so just leave them as is.

**Comment by brunobowden** [comment]
You should only remove the library I mentioned (likely replace 'base' with
'shared') in your case.

**Comment by advayDev1** [comment]
my hypothesis (as the sole non-pods user though) is that the missing library is the name of the library the pod itself is trying to create. it worked before Massive Refactor 1 because we used to have the pod compile at least one source file.  now the pod has no source files to compile and just links in the thing made in the native compilation phase.

maybe you all have already figured this out though.

**Comment by advayDev1** [comment]
EDIT: actually, i'm pretty certain of this, because it is the same behavior Xcode exhibits when you try to make a target with 0 source files too. still not sure this helps you fix anything though. @brunobowden - you can always try forcing my existing empty-source-file.m hack in the Pod to prove it though =)

**Comment by brunobowden** [comment]
A useful suggestion. I'll try this out...

**Comment by advayDev1** [comment]
@brunobowden  - Per our phone call, this line:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy#L102
only includes header files.  This will never generate an output target.  However, we cannot include the j2objc .m files, since that would cause double-definition of those symbols.

The solution is to have the source files as `${buildDir}/j2objcHackToForceCompilation/Empty.m` (with proper relativization)

**Comment by advayDev1** [comment]
@alexmetcalfe - per http://www.raywenderlich.com/64546/introduction-to-cocoapods-2 - are you opening the xcworkspace generated by cocoapods for you, or are you opening your original xcproj files?

**Comment by advayDev1** [comment]
final update - @brunobowden tested the step of opening the xcworkspace that cocoapods generates for you instead of the existing xcproj, and that solves the problem.  @confile , @alexmetcalfe  - please try this out.

**Comment by brunobowden** [comment]
@alexmetcalfe - opening the `.workspace` file instead of `.xcodeproj` should fix this issue. Please confirm that and reopen if it doesn't. I also wrote up an answer to your StackOverflow question: http://stackoverflow.com/a/31424751/1509221

**Comment by confile** [comment]
You alway have to open the file cocoapods generate. Otherwise your pod system will not work.

**Comment by alexmetcalfe** [comment]
Hey @brunobowden, yep I've been using the .xcworkspace and not the .xcodeproj file to open in xcode. Ive also just tried deleting my pod file and regenerating with no luck :(

Ive put what I have on github here:

https://github.com/alexmetcalfe/j2objc-contributors/tree/j2objc-gradle

Just to confirm that there are not any other build tasks I need to be doing other than the below?

```
./gradlew clean build j2objcXcode
```

**Comment by alexmetcalfe** [comment]
Hey @brunobowden , yep ive been using the .xcworkspace file and not the .xcodeproj 
Ive just tried deleing the Podfile and regenerating with no luck :(

Ive put what I have so far on github here:

https://github.com/alexmetcalfe/j2objc-contributors/tree/j2objc-gradle

**Comment by alexmetcalfe** [comment]
Here is the current error I am having:

![screen shot 2015-07-21 at 9 33 10 pm](https://cloud.githubusercontent.com/assets/734514/8799787/353427e0-2ff0-11e5-9b16-e250bddd280a.png)

And the Pods dependency seems to be coming up OK in xcode:

![screen shot 2015-07-21 at 9 35 21 pm](https://cloud.githubusercontent.com/assets/734514/8799806/6abbcbe8-2ff0-11e5-8b6f-17b02f3e42f2.png)

**Comment by advayDev1** [comment]
@alexmetcalfe:
1.  please run `ls -al /Users/alex/dev/bin/j2objc`
2.  please provide the contents of your local.properties file or the value of J2OBJC_HOME in your environment.

**Comment by brunobowden** [comment]
@alexmetcalfe - can you try opening the `.xcworkspace` file in Xcode and see if that fixes the problem. If it works, please upvote and mark the fix on StackOverflow.

I have a pending PR in #303 to warn users about opening the correct file. That'll have to suffice for a fix.

**Comment by advayDev1** [comment]
@brunobowden - @alexmetcalfe indicates at https://github.com/j2objc-contrib/j2objc-gradle/issues/273#issuecomment-123272301 that he is using the .xcworkspace, and the pod target issue is fixed.  the new error is that `-lguava` is not detected.  note he has `-L/Users/alex/dev/bin/j2objc` in the LD arguments.  which is why I asked him to follow these steps: https://github.com/j2objc-contrib/j2objc-gradle/issues/273#issuecomment-123455756

**Comment by alexmetcalfe** [comment]
@advayDev1 here you go:

![screen shot 2015-07-22 at 7 54 54 am](https://cloud.githubusercontent.com/assets/734514/8813456/05e36710-3047-11e5-96f1-27539fd69328.png)

**Comment by alexmetcalfe** [comment]
And the lib directory:

![screen shot 2015-07-22 at 8 00 56 am](https://cloud.githubusercontent.com/assets/734514/8813556/d999dc06-3047-11e5-81c9-d54c70fc8ddf.png)

**Comment by advayDev1** [comment]
@alexmetcalfe - yes, the issue here is that the -L is pointing to the location of the j2objc binary, not the lib directory.  Can you find the .xcconfig file that specifies -L/Users/alex/dev/bin/j2objc and manually change it to -L/Users/alex/dev/bin/j2objc/lib ?  I'll try to see where we are generating the non-lib directory, if at all.

**Comment by alexmetcalfe** [comment]
Here is my local.properties

sdk.dir=/usr/local/Cellar/android-sdk/22.6.2
j2objc.home=/Users/alex/dev/bin/j2objc/

**Comment by advayDev1** [comment]
Ah, the bug is the double slash:
```
LIBRARY_SEARCH_PATHS = /Users/alex/dev/bin/j2objc//lib
```

I guess xcode cannot handle that.

**Comment by advayDev1** [comment]
@alexmetcalfe, Please change your local.properties to be:
```
sdk.dir=/usr/local/Cellar/android-sdk/22.6.2
j2objc.home=/Users/alex/dev/bin/j2objc
```
without the slash, and try regening your pod files and reopening the workspace, if that works I'll make a PR.

**Comment by alexmetcalfe** [comment]
Excellent I have found the issue!

The line:

LIBRARY_SEARCH_PATHS = /Users/alex/dev/bin/j2objc//lib /Users/alex/dev/projects/j2objc-contributors/shared/build/j2objcOutputs/lib/iosDebug

has two '/' before the lib directory which in effect commented the rest of the line... removing the extra / has allowed me to successfully run the project in xcode

**Comment by alexmetcalfe** [comment]
Thanks @advayDev1 that solves my issue

**Comment by advayDev1** [comment]
@alexmetcalfe comment race ;)  - please do try regening your pods with the modified local.properties.  if it works, we'll fix it for everyone

**Comment by brunobowden** [comment]
Excuse me @alexmetcalfe, this was a fix for CocoaPods but not the -lguava issue you were seeing.

**Comment by advayDev1** [comment]
sorry @brunobowden , made a new bug.  your PR did indeed fix the original issue on this bug.  @alexmetcalfe , see #304

**Comment by brunobowden** [comment]
I don't think I've ever seen as many nested race comments ;-)

**Comment by alexmetcalfe** [comment]
@advayDev1 can confirm after updating the path in the local.properties and rebuilding my project in xcode now compiles and build successfully.

**Comment by alexmetcalfe** [comment]
heh I had a feeling it was going to be something extremely simple :) thanks everyone for your help on this!
