### ISSUE TITLE
Consider @CompileStatic annotation for more type safety

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#283]
Would help us catch more errors at compile-time.  But for the specific classes that use this, we would lose some Groovy magic.

@brunobowden - thoughts?

**Comment by advayDev1** [comment]
This I think would have prevented nearly all of today's merge/build breaks.

**Comment by advayDev1** [comment]
(btw, I have done this conversion for all classes except the DSL definition of one of my internal plugins and it definitely helped me catch errors earlier with very little loss of Groovy convenience)

**Comment by brunobowden** [comment]
I'm very in favour of compile time checking. Reading the Groovy Lang docs, it states that ["...bypassing the Groovy meta object protocol"](http://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html). So I'd mainly check that it doesn't cause an issue with the MockProjectExec class which uses metaClass programming to intercept invokeMethod.

So as long as that still works (or can have an exception), then I'm all for this.

**Comment by advayDev1** [comment]
I think the rest of that Javadoc provides us a way to avoid that issue:
"By using TypeCheckingMode.SKIP, static compilation can be skipped on an element within a class or method otherwise marked with CompileStatic. For example a class can be annotated with CompileStatic, and a method within can be marked to skip static checking to use dynamic language features."
So we might need to pull the exec or project.with calls in J2objcConfig/NativeCompilation into so-marked methods (or skip CompileStatic on a subset).  I think applying CompileStatic on as many methods/classes as we can, even if not all, is still a win.

I'll take this on after doing some basic multi-project tests.

**Comment by brunobowden** [comment]
If possible, I'd prefer isolating the exceptions only to the test code.
Replacing project.with by explicit calls isn't that much of a burden.

**Comment by advayDev1** [comment]
project.with was an example for any delegate-based closure configuration which relies on dynamically resolving properties/methods to the delegate instead of the frame where the closure is compiled.
NativeCompilation, for example, is entirely based on using the DSL methods of the native plugin.

**Comment by advayDev1** [comment]
btw, @brunobowden - it is possible (not saying we should) to convert our production files to Java instead of Groovy (or even just same of them) - I think most of Gradle is actually pure Java.  Groovy can do a mixed compile.  The biggest downside I think is losing GString interpolation.

**Comment by brunobowden** [comment]
Interesting point. From GitHub, Gradle is 50:50 split. Unless we find a big
need for it, I tend to prefer to stay away from a complete rewrite like
that.

[image: Screen Shot 2015-07-15 at 7.01.57 PM.png]
Intermediate steps like @CompileStatic and a Java like style do seem a fit
to me.

**Comment by advayDev1** [comment]
i think:
if a file is .groovy i think it should follow Groovy style.
if a file is .groovy with @CompileStatic it should follow Groovy style but with static typing.
if a file is .java i think it should follow Java style.

i don't think the second implies the third.

either way, i'm all for staying Groovy but with static typing where possible.  i'll get started on that after #284

**Comment by brunobowden** [comment]
Agreed that it doesn't imply. Just looking at Utils.groovy, you could
easily assume that is was Java already ;-)

**Comment by advayDev1** [comment]
example of what we can't convert is project.copy { CLOSURE }.
the only conversion of that (that does not use gradle.internal classes) is:

                setProperty("includeEmptyDirs", false);
                invokeMethod("from", new Object[]{srcGenDir});
                invokeMethod("into", new Object[]{getDestSrcDir()});
                invokeMethod("exclude", new Object[]{"**/*Test.h"});
                return invokeMethod("exclude", new Object[]{"**/*Test.m"});

which is awful.  so i'm skipping such closures.

**Comment by advayDev1** [comment]
Reopening to cover copy and exec too.
