### ISSUE TITLE
NativeCompilation integration tests

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#286]
See #284 on how these will look.

**Comment by brunobowden** [comment]
Theses tests take substantially longer than the other tests. For me, they take 4 and 12 seconds each. I welcome adding additional tests but it would be nice to disable the slower tests during rapid dev test cycles. See timing info below:

![screen shot 2015-07-17 at 10 05 11 pm](https://cloud.githubusercontent.com/assets/679339/8761109/74a06988-2cf4-11e5-8029-296ecb83b489.png)

**Comment by advayDev1** [comment]
there's a call in there that realizes all build models/tasks.  basically it is doing a full gradle build inside the test.  will look into categorizing the tests though.  hopefully we can add a testUnit and testIntegration, so in normal dev cycles we just use testUnit.

**Comment by advayDev1** [comment]
We have the system and e2e tests.  For the process of native compilation, I think that is the best testing.

No point in testing the args to the compilers since that is hidden behind Gradle's native compile model and not our responsibility.
