### ISSUE TITLE
Building with j2objc-gradle within Xcode

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#298]
My internal setup has both a) the final iOS/OSX app build-able by Gradle (with https://github.com/madvay/mixc-build) and b) the Java code buildable in Xcode.  While (a) needs to be separate from this plugin, I think (b) would be more appropriate to put here.  When you change your Java (say manually or just by git pull-ing the latest changes), the next Debug run in Xcode will first run both j2objc translation and j2objc-gradle native compilation before building the Xcode part of the project (with all of our usual partial translation/compilation magic).

In addition to convenience, the key benefit is that errors in your j2obc-gradle setup are much easier to debug.  Since j2objc's error messages match Xcode's format (thanks @tomball !), Xcode lets you jump straight into the Java file (for j2objc errors) or the resulting .m/.h transpiled file (for j2objc-gradle native compilation errors).

Of course, I don't use cocoa pods, so I'm not sure how to make our pod configure the resulting xcproj to do what mine does (my projects all use hand-rolled xcconfig files).

@brunobowden @confile - I'm going to need some pointers about pods if we want to do this.

**Comment by brunobowden** [comment]
Advay - call me when you can as it would be helpful to talk this through. It appears that we only really use the xcconfig feature of Cocoapods. In b), you're suggesting you can edit the Java within Xcode and then build it? In general, I'm supportive of this.

Tracking a separate issue to not only do the build but also the compile within Xcode: #299

**Comment by confile** [comment]
@advayDev1 I do not depend on cocoapods. I just use it to integrate other pods in my project. If there is a better way to integrate the j2objc code then lets do it. For me, and I am still working with the old one file j2objc gradle plugin, is it the easiest way of doing it. There is no dogma that we must use it. We dumped integrate2xcode as we before.

**Comment by confile** [comment]
For me the only thing which is important is that incremental build are as fast as possible, because that is where I loose time.

**Comment by advayDev1** [comment]
Yeah that's the main benefit for me using j2objc-gradle within Xcode.  Our plugin does incremental translation & compile correctly.  Using j2objc directly does not get us incremental translation.

**Comment by advayDev1** [comment]
Per discussion with @brunobowden , putting this on hold.

**Comment by brunobowden** [comment]
It would also be helpful if this only built the targeted architecture needed for that debug/release and device/simulator instance. It appears that certain buildphase logic can be added to the build as is currently done with CocoaPods for example:

![screen shot 2015-08-30 at 11 21 05 am](https://cloud.githubusercontent.com/assets/679339/9587078/631d690a-4fd5-11e5-9cc7-bd1d947f5611.png)

**Comment by confile** [comment]
@brunobowden What do you suggest here?

**Comment by brunobowden** [comment]
Nothing for the moment. This is going to be a lot of work to support builds inside of Xcode. For now, I think we're better off with the speed improvements and suggestions in PR #444. My hope at some point though, is that we can get Xcode to kick off a very targeted plugin build that built the minimal set of what's needed.

@confile - if you'd like to look in to this, try and understand how the buildphase scripts in Xcode work. Then again the script needs to figure out if it's building debug / release and which architectures, e.g. armv7 for iPhone 5 and earlier, or arm64 for iPhone 5S and later. Then it can kick off a minimal build with the plugin that targets only what is needed.

**Comment by advayDev1** [comment]
Note it is already possible to have your 'run' button in Xcode also do the j2objc translation for you (I already do this). Just 1) create an 'External Build System' target in Xcode and have it run the appropriate Gradle command making sure that you do not check the box that shares environment variables with external command and 2) have your iOS app have a 'target dependency' on that External Build System target. Voila, each time you click build you get the latest Java code too. I think this is the best way to go because it gives the same bits as if you ran gradle yourself. We could expand it to for example just run the single architecture you want by passing some sort of argument (?).

Unfortunately limiting the plugin build to only one arch or debug vs. release may very well increase build time because that will be a different J2objcConfig setting, which will cause many tasks to be 'out of date'.

**Comment by brunobowden** [comment]
Can you just document this in the FAQ.

**Comment by brunobowden** [comment]
Maybe consider this bug closed after documenting it. I agree that doing
something better would be tricky.

**Comment by advayDev1** [comment]
sg
