### ISSUE TITLE
Resource loading within test executables

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#309]
Currently the podspec will copy the resources to Xcode using CocoaPods. I want to test out and make sure we support loading of resources within Xcode.

**Comment by brunobowden** [comment]
@advayDev1, @confile

I'm successfully loading a file in a JUnit test which fails to load after the j2objc translation. Advay, since I know you use resources heavily, I'm interested in your feedback on this. Likely we should also document what the preferred approach is.

Here's the method I'm using that works in the JUnit test:

    public String readResource() {
        InputStream inputStream = getClass().getResourceAsStream("/raw/resource.txt");
        log.severe(String.format("inputStream: %s", inputStream));
        Scanner scan = new Scanner(inputStream);
        log.severe(String.format("scanner: %s", scan));
        ArrayList<String> strings = new ArrayList<String>();
        while (scan.hasNextLine()) {
            strings.add(scan.nextLine());
        }
        log.severe("File: " + strings);
        return strings.get(0);
    }

When I run the j2objc translated version. It indicates that `inputStream` is null and gets an NPE.

```
$ /Users/brunobowden/dev/taptap/base/build/binaries/testJ2objcExecutable/debug/testJ2objc org.junit.runner.JUnitCore CsiPersonTest
JUnit version 4.10
........Jul 21 21:25:53 Brunos-Air.local main[37509] <Error>: inputStream: null
E
Time: 0.008
There was 1 failure:
1) resourceLoad(com.cambridgesoftwareinc.contacts.PersonTest)
java.lang.NullPointerException: src == null
	at 0x0000000103ea434f java.lang.Exception.<init>() + 39
	at 0x0000000103eb50b7 java.lang.RuntimeException.<init>() + 39
	at 0x0000000103eab29f java.lang.NullPointerException.<init>() + 39
	at 0x0000000103fdffb9 java.util.Scanner.initJavaUtilScanner() + 677
	at 0x0000000103aac379 com.cambridgesoftwareinc.contacts.Person.readResource() + 265
	at 0x0000000103a9e513 com.cambridgesoftwareinc.contacts.PersonTest.resourceLoad() + 99
```

From searching the build directory, I see the file has been copied to j2objcResources:

```
$ find base/build -name "resource.txt"
base/build/j2objcResources/raw/resource.txt
base/build/resources/main/raw/resource.txt
```

**Comment by advayDev1** [comment]
While the xcode project (via the pod for you, and via some manual soft links for me) incorporates the j2objcResources directory into the app's Bundle, the j2objc-gradle unit-test binary doesn't (and never has).  None of my unit-tests use resources (since that wouldn't be a unit-test AFAIAC).

When we use the NativeCompilation phase (or when we previously used the J2objCC task), we are not making a bundle, so the resources aren't included with the unit-tests at all.  see http://j2objc.org/docs/Java-Resources.html

Note that on the other hand the Xcode app-test target /does/ contain the Bundle's resources.

**Comment by brunobowden** [comment]
@advayDev1 - I should've been clearer. The resource is in main, not test... but is exercised from a unit test. In any case, your indicating that neither the main nor test resources are built in to the test executables.

How reasonable do you think it is to support this? If the java code works, my feeling is that the translated code *should* work as well. What would be involved?

**Comment by advayDev1** [comment]
There's a key difference between Java and native here though.
If you had a Java project A, it creates A.jar, which includes both its bytecode and its resources.
But native code A just creates library libA.a (nothing to do with j2objc/gradle/what have you).
When Android project B depends on A.jar, it gets A's resources too.  No such resource aggregation occurs with native code B that depends on libA.a.

So I don't think we should think of this in terms of fixing it for our test executable or in our plugin alone.  My preferred solution is to to add to j2objc resource-loading strategies other than 'assume main bundle'.  For example, we could add to:
https://github.com/google/j2objc/blob/a5b32a1fcfe6759bb5908ade5a4e6e94fbafcb26/jre_emul/android/libcore/luni/src/main/java/java/lang/ClassLoader.java#L696
an option that loads resources relative to the path of the executable binary, when a particular System property is set or command-line flag is set.  Thoughts?

I do not know however, whether the right solution is to add the code directly there.  Perhaps @tomball has some pointers for us.

**Comment by brunobowden** [comment]
I like the approach of modifying ClassLoader. We can easily supply supply a parameter on the command line and still use CocoaPods to bundle the resources within Xcode.

@tomball, @kstanger - Advay and I are interested in your thoughts on this?

**Comment by advayDev1** [comment]
@brunobowden, after we make add the functionality to j2objc (whatever it happens to be), we also need to do work on our plugin tasks to aggregate the resources from all possible sources, include:
- the project's own resources
- the projects added via dependsOnJ2objcLib's resources
- resources from jars that we're depending on

**Comment by brunobowden** [comment]
Always a lot to do!

**Comment by kstanger** [comment]
I will defer to Tom, who has more experience with how resource loading works.

**Comment by tomball** [comment]
Resource files just need to be copied to the app's resource bundle, or in
the case of OS X, the same directory the executable is in. In either case,
the relative path should be preserved, same as if it were in a jar file for
JVM use. So if foo.bar.Mumble loads a "data/mybits.dat" file, that is
copied as foo/bar/data/mybits.dat, either in the iOS app, OS X app
executable directory, or jar file.

**Comment by brunobowden** [comment]
Very helpful @tomball. I moved the executable in to the same directory as the resources and it worked. @advayDev1 and I will have to ponder on how best to make this work with the plugin.

**Comment by tomball** [comment]
The right solution is to copy the resource file into the test bundle where
the jre_emul runtime will find it. To see an example, cd to
j2objc/jre_emul, run "make -f tests.mk clean resources", then list them
using "ls -R build_result/tests". To see an iOS example, open
j2objc/jre_emul/JreEmulation.xcodeproj in Xcode, select the JRE JUnit Tests
target then review all the Copy Files build phases that create the same
resource tree that was listed on OS X.

**Comment by advayDev1** [comment]
Similar to j2objcc, We aren't creating a bundle at all for unit testing.
Although from your earlier post, it seems on OS X we can just put the
resources next to the binary.
