### ISSUE TITLE
Cycle Finder Task java_sources.mf not found anymore

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#31]
To use cycle finder I do:

```
cycleFinderFlags "--whitelist /Applications/J2Objc/j2objc-sorce/jre_emul/cycle_whitelist.txt --sourcefilelist /Applications/J2Objc/j2objc-sorce/jre_emul/build_result/java_sources.mf"
```

In the latest source I could not find 

```
j2objc-sorce/jre_emul/build_result/java_sources.mf
```
anymore. So I use an old version.

@brunobowden How do you handle this?

**Comment by brunobowden** [comment]
@tomball - was cyclefinder whitelist removed?

It used to be in the source tree:
j2objc-sorce/jre_emul/build_result/java_sources.mf

**Comment by tomball** [comment]
The whitelist is still there:
https://github.com/google/j2objc/blob/master/jre_emul/cycle_whitelist.txt

Everything in jre_emul/build_result is a build artifact, including the
directory (AFAIK, it was never in the source tree). The
build_result/java_sources.mf is created when building jre_emul, so run
'make dist' or, if you just want the minimum build, run 'make
java_sources_manifest'.

**Comment by confile** [comment]
@advayDev1 Do you have a good solution on this?

**Comment by advayDev1** [comment]
never used cycle finder yet, sorry.

**Comment by brunobowden** [comment]
When we do a plugin, I'll copy the file in manually for each version of
j2objc.

**Comment by confile** [comment]
@brunobowden That is great.

**Comment by confile** [comment]
@advayDev1 @brunobowden as Bruno suggested we can copy the two files into the plugin. Do you see a way of specifying the correct path to the files. It is easy when it is not in the plugin but in the plugin it is hard. 

Assume the files are in ``src/main/resources/file1.txt`` and ``src/main/resources/file2.txt``. Is it possible to get the paths to the files somehow?

**Comment by brunobowden** [comment]
You don't just need those two files... you also need the complete J2ObjC source and to do the local build. This is enough of a narrow case that I don't think there's a good way to solve it. There's many more other issues that are more pressing.

**Comment by MyCADDev** [comment]
Hi 
In j2objc-1.1 the jre_emul java_sources.mf is missing.

make dist is not generating this file

Could someone help?

thanks

**Comment by brunobowden** [comment]
I believe this requires a special build step to create this file:

https://groups.google.com/d/msg/j2objc-discuss/2fozbf6-liM/R83v7ffX5NMJ

**Comment by MyCADDev** [comment]
Thanks @brunobowden - that worked
