### ISSUE TITLE
Debug and release test binaries need distinct names

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#323]
When the binaries are copies to `build/j2objcTestContent`, they overwrite each other and cause the up-to-date checks to fail.

**Comment by advayDev1** [comment]
Xcode convention is not to generate 2 differently named apps (like say Android gradle does), but instead to put them in different directories.  i think we should probably follow the same convention.  keep debug and release completely separate, including their content directories.

**Comment by brunobowden** [comment]
In this case, it's only an internal implementation detail of the plugin, nothing that interacts with Xcode. I've checked and both plugins can be happily run from the same location without an issue. My concern comes down to the large amount of resource copying that we're doing, issue #313. By sharing the resources, this eliminates one set of copying.

**Comment by brunobowden** [comment]
Fixed by #326.
