### ISSUE TITLE
protobuf_runtime.a j2objc lib dependency

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#327]
Currently this isn't default included in the `translateJ2objcLibs`. Likely it should be added only if the associated `protobuf_runtime.jar` is a dependency.

**Comment by advayDev1** [comment]
protobuf is in fact included both for translation and linking

https://github.com/j2objc-contrib/j2objc-gradle/blob/459d2c70a8fbabc26a440cc3ad284d7d0bf7758e/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy#L288 

https://github.com/j2objc-contrib/j2objc-gradle/blob/459d2c70a8fbabc26a440cc3ad284d7d0bf7758e/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy#L301
