### ISSUE TITLE
Incremental Translation

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#33]
We should find a way to perform incremental translation. I.e., 

1. Check which Java files have changed.
2. Translate only the Java files which have changed.

**Comment by brunobowden** [comment]
There's a number of TODO's in the file about this. It mainly requires
careful setup of the @OutputFile / @OutputDir so that Gradle can watch for
the changes.

I'm also trying to figure out how to mark a task up to date when it has no
output:
http://stackoverflow.com/questions/29599011/up-to-date-gradle-task-status-when-it-has-no-output/29599370

**Comment by confile** [comment]
We also need to fix integratej2objc. If you run the command twice the generated folder is not replaced it is doubled. The code is in ruby so I cannot fix it. Since I did not see any response from the author I suppose we should take care of this. If you are familiar with ruby it would be great if you could fix this. 

I will research a bit on the other topic of how we can watch the changes.

**Comment by brunobowden** [comment]
I finally got the answer on how to do task updates when there's no outputs:

http://stackoverflow.com/questions/29599011/up-to-date-gradle-task-status-when-it-has-no-output/29736555?iemail=1&noredirect=1#29736555

**Comment by confile** [comment]
That is great. You could perhaps write the number of translated files in that output file which is then checked for up to date.

**Comment by confile** [comment]
Here is what I think``J2objcTranslateTask`` will work. From the current setup: 

```
    @InputFiles FileCollection srcFiles
    @OutputDirectory File destDir
```
Gradle still watches for changes. It only runs the task if either input or output files have changed. The problem is that it translates everything if you changed one input file.

Here is my idea to solve this:

1. Get the set of ``srcFiles`` and the ``srcFilesChanged`` since the last run of this task
2. If  ``srcFilesChanged`` is empty translate everything (the current case)
    - Else compute ``translatedSrcFiles =  srcFiles - srcFilesChanged`` and add ``translatedSrcFiles``to the classpath (we do not want them to be translated again, if that does not work we use their .class files) 
    - translate ``srcFilesChanged`` with ``j2obc``

**Comment by confile** [comment]
@brunobowden Please see my pull request: https://github.com/brunobowden/j2objc-gradle/pull/36

**Comment by confile** [comment]
@brunobowden Referring to your comment here: https://github.com/brunobowden/j2objc-gradle/pull/36#issuecomment-95607126 I still do not see how we could change this: https://github.com/brunobowden/j2objc-gradle/blob/master/j2objc.gradle#L871

```
"build/source/apt",
```

**Comment by brunobowden** [comment]
There's some more detail about this from an SO question I asked:
http://stackoverflow.com/questions/27075123/gradle-plugin-best-practices-for-tasks-that-depend-on-extension-objects

I've tested the following and it works for configuring the "j2objcTranslate"
task after it's created... but it looks ugly to me and this doesn't work
for shared config across multiple tasks. This could work better for config
that's only for a single task, e.g. command line flags or similar. Obviously
you could push the "build/source/apt" in to a separate arg to make it
cleaner but I'm still not completely convinced about this. My next commit
will have some changes along these lines.

apply from: 'j2objc.gradle'

j2objcConfig {
    j2objcHome "${projectDir}/../../j2objc-versions/j2objc-0.9.6.1"  // Dev
Version Selection
}

j2objcTranslate {
    srcFiles files(
                        fileTree(dir: projectDir,
                                include: "**/*.java",
                                exclude: project.relativePath(buildDir)) +
                        fileTree(dir: "build/source/apt",
                                include: "**/*.java")
                        )
}

**Comment by confile** [comment]
@brunobowden What about the ``-classpath``question? :-)

**Comment by brunobowden** [comment]
This sounds like it should work. If it does work, then send in the change. If it doesn't work, I think this is worth asking on the j2objc-discuss thread for suggestions.

**Comment by confile** [comment]
@brunobowden If you talk about the classpath problem this does not work. Do you see andy problem here: 

```
       if (!freshBuild) {
          println("translatedSrcFiles size: "+translatedSrcFiles.getFiles().size())
          
          def classFileNames = []
          translatedSrcFiles.each {File file ->
              def classFileName = file.name.toString().replaceFirst("java","class")
              classFileNames += "**/"+classFileName
          }
  
         println "classFileNames: "+classFileNames.size()
                    
             // find the .class files
             FileCollection classFiles = project.files(
              project.fileTree(dir: project.buildDir,
                      includes: classFileNames))

           def translatedClassFileArgPaths = []
           classFiles.each{File file ->
            translatedClassFileArgPaths += file.path.toString()
          }
                    
           if (translatedClassFileArgPaths.size() > 0) {
            if (classPathArg.size() > 0) {
              classPathArg += ':'
            }
            classPathArg += translatedClassFileArgPaths.join(':')
          }                    
        } 
```
Taken from here: https://github.com/confile/j2objc-gradle/commit/af138abd9a986c2c27b895d6193dfed0cbf79653#diff-cd56e928e1096973b671c75e5e0c6073R525

If you have no idea how to put the .classes on the classpath I post a question. Just give me a sign.

**Comment by brunobowden** [comment]
Sorry @confile, I don't know how this should work with the classpath. Best
to ask on the j2objc-discuss list.

**Comment by confile** [comment]
@brunobowden I did the post. Lets see what happens: https://groups.google.com/forum/#!topic/j2objc-discuss/juXn8G18Gw8

**Comment by brunobowden** [comment]
UP-TO-DATE now works for individual tasks. So tasks will only run if one of their inputs has changed or an output is out of date. Still needs a lot of work for incremental compilation.

**Comment by advayDev1** [comment]
@confile, does the current state of the plugin support what you need?
we have incremental translate, compile, and assemble (the first is only incremental if you don't have --build-closure).  also the translate task has many more input files so it should be up-to-date more accurately.

**Comment by confile** [comment]
@brunobowden @advayDev1 You did a great job the last days and a lot of pushes. I was not able to use the plugin so far in its last version due to a lot of other work I had to do. I will test it and give you feedback as soon as I can.

**Comment by brunobowden** [comment]
@Confile - I agree it's great work. Quite possibly it's broken right now -
I'll be Yeung it out myself later tonight.

**Comment by advayDev1** [comment]
since they aren't documented well anywhere yet, here are some things
different from before:
1. see README.md about how to use the new plugin jar.
2. any include/exclude patterns need to use PatternSets not regexes
3. name of destination directories has changed, see J2objcPluginExtension
4. non java-plugins will simply not work (including the Android plugins)
5. task j2objcCopy is now j2objcAssemble, and all j2objc tasks are
integrated into the standard project lifecycle (except xcode)

i've never run cycle finder or xcode tasks (because they've never worked
for me before anyway), but have moderately tested the other tasks.

**Comment by brunobowden** [comment]
@advayDev1 - what's still needed for this issue?

**Comment by advayDev1** [comment]
Nothing I fixed this long ago.  @confile is not yet able to verify the fix due to pod issues it seems.

Closing.
