### ISSUE TITLE
Update Plugin Gradle version to 2.5 

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#335]
Update Plugin Gradle version to 2.5

**Comment by advayDev1** [comment]
@confile  - Do you mean update the development gradle wrapper to 2.5?
Currently, the plugin is compatible with gradle *runtimes* 2.4 and 2.5 (i.e. our users can use gradle 2.4 or 2.5 in their development).  I've confirmed this as I use both.

**Comment by brunobowden** [comment]
@Confile, I believe this is working correctly. Please help us understand
what you're asking for.

**Comment by confile** [comment]
This is no bug. I just thought of updating the wrapper.

**Comment by brunobowden** [comment]
I'd recommend we keep the old wrapper as we don't need the new functionality. I'm not sure if it has much value in maintaining backwards compatibility but there's a slight benefit there. Closing for now.
