### ISSUE TITLE
Default value for cycleFinderExpectedCycles

### ISSUE THREAD

**Issue by gocursor** [j2objc-contrib/j2objc-gradle#346]
Default value for cycleFinderExpectedCycles is set to 40 (see https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#cycle-finder-basic-setup). But I am using the latest j2objc 0.9.7 and CycleFinder reports 34 cycles.

Did the expected number of erroneous matches with jre_emul library change in latest J2ObjC version? Is there a way to make the default value of "cycleFinderExpectedCycles" dependent on the J2ObjC version?

**Comment by advayDev1** [comment]
Please go ahead and try:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#cycle-finder-advanced-setup
using the 0.9.7 distribution.  If that works, you are fine.  It is the case that 40 is a 0.9.6.1-specific number.  

Until j2objc fixes https://github.com/google/j2objc/issues/546 we can't automate matching the number in the plugin with the expected number of cycles.

**Comment by advayDev1** [comment]
Due to how generics work, there will never be a default value that works for everyone.
(For example, every one of my types used in a Map causes a new cycle because Maps themselves have cycles).  Closing as  Cannot fix.

**Comment by gocursor** [comment]
It's OK, if it is not possible to fix it...

**Comment by advayDev1** [comment]
I don't believe in principle we can fix this (due to the generics issue listed above)
