### ISSUE TITLE
0.4.1 release?

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#362]
@brunobowden would you mind pushing out a 0.4.1 after we get the current set of PRs in?
we might as well have windows support tried out by users, and it looks like you are waiting for 0.5.0 for some other issues.

**Comment by brunobowden** [comment]
I'll be happy to do this.

**Comment by advayDev1** [comment]
looks like this is good to go.  thanks so much!

**Comment by advayDev1** [comment]
suggested Changelog from https://github.com/j2objc-contrib/j2objc-gradle/compare/v0.4.0-alpha...master :

Functionality:
- Translation-only mode (skips building Objective-C libraries)
- Support for Windows/Linux (in translation-only mode)
- Cycle finding moved from assembly phase to test phase.
- Automatic linking with related Xcode projects, like tests and WatchKit apps
- Environment-specific config can be provided via environment variables in addition to local.properties

Code quality:
- Additional test coverage
- Continuous integration via Travis
- Documentation fixes

**Comment by advayDev1** [comment]
danke!
