### ISSUE TITLE
publish plugin to repositories

### ISSUE THREAD

**Issue by iCarry** [j2objc-contrib/j2objc-gradle#363]
Hi,
Is there a plan to publish the plugin to any of the repositories ?  for example, maven central, jcenter, or even jitpack.

I tried jitpack, but it looks like there are some additional work needed for it to work: 
https://jitpack.io/com/github/j2objc-contrib/j2objc-gradle/v0.4.0-alpha/build.log

Thanks

**Comment by advayDev1** [comment]
The plugin is in fact published to the standard location for Gradle community plugins:
https://plugins.gradle.org/plugin/com.github.j2objccontrib.j2objcgradle

You can see that page for details on configuring the repository.  For most users, referencing the plugin as specified in the README.md file will suffice however.

**Comment by advayDev1** [comment]
namely:
```gradle
plugins {
    id 'java'
    id 'com.github.j2objccontrib.j2objcgradle' version '0.4.0-alpha'
}
```
will download the plugin from the Gradle community plugin repository.

**Comment by iCarry** [comment]
ohh, nice.
Thanks!!
