### ISSUE TITLE
Problem with translateClasspaths and translateSourcepaths

### ISSUE THREAD

**Issue by ph1lb4** [j2objc-contrib/j2objc-gradle#368]
When trying to use a custom translateClasspaths or translateSourcepaths variable the following error occurs:

Cannot cast object './libs/somelib.jar' with class 'java.lang.String' to class 'java.util.List'

We specify the variable as follows:

translateClasspaths = './libs/somelib.jar'

Is this specified correctly or are we making a mistake?

**Comment by advayDev1** [comment]
translateClasspaths is a list. and has a method to append to it.
do instead:
```gradle
translateClasspaths './libs/somelib.jar'
```

**Comment by ph1lb4** [comment]
Thank you very much, that was it.
Is there also already a tutorial on how to integrate gradle dependencies?

**Comment by brunobowden** [comment]
See the FAQ:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#how-do-i-setup-dependencies-with-j2objc
