### ISSUE TITLE
Android shared ios Sample Project

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#370]
Could someone @brunobowden @advayDev1 generate a sample app which contains an Android, Shared and ios project. I could not make it to run. Also,  it would help for others.

**Comment by advayDev1** [comment]
I do not use pods or that part of this plugin, and I imagine our sample project should use pods and not https://madvay.github.io/mixc-build/, so I can't take this on.

also, Didn't you @confile take on this project in #161  ?

**Comment by confile** [comment]
I was not able to run it with android studio.

**Comment by brunobowden** [comment]
I will do something for this but it may take me a few weeks.

**Comment by brunobowden** [comment]
My hope is that we can use a sample project like this for doing build testing as well. In that sense, we might be better off with a stable Gradle 2.6 but I'll evaluate that later on.

**Comment by confile** [comment]
Any one has an idea how to get it working with Android Studio?

**Comment by brunobowden** [comment]
Michael - I'd start with the very simplest thing you can imagine. No
annotation processors, no complexity. Then gradually make it closer and
closer to what you want. Create the shared Java project first. Get that
working in Android... then try adding the j2objc-gradle plugin and get that
working as well.

**Comment by confile** [comment]
@brunobowden I created a blank sample android project in Android Studio. I did not change anything my get the following error in LogCat. See here: 
http://stackoverflow.com/questions/32103169/android-sample-app-resource-was-acquired-at-attached-stack-trace-but-never-rele

The app runs but still I get the error I reported. Any idea?

**Comment by advayDev1** [comment]
Are you certain those errors are from your app?  Do you have your process
filter set?
I see a lot of such spam on my M preview emulator, none of it from my app.

**Comment by confile** [comment]
The Emulator Reports this I do not do anything. Why are there so many errors? It is confusing.

**Comment by advayDev1** [comment]
I'm not sure what you mean.  You control which logs you care about.  Check the pid of your app, then check the pid in the logs.  If they aren't from your pid, ignore them.  I'd suggest moving forward.

**Comment by confile** [comment]
Where do I see the pid?

**Comment by advayDev1** [comment]
please search around for this kind of assistance - it isn't related to j2objc gradle or the plugin.  ex: http://stackoverflow.com/questions/19931987/how-to-filter-logcat-in-android-studio

**Comment by confile** [comment]
Thank you @advayDev1

**Comment by confile** [comment]
@advayDev1 It would be very helpful if you put out some samples.

**Comment by advayDev1** [comment]
@confile, they aren't exactly samples, but I'm going with "simplest first" principle and have added #409 and #411.  Slowly we can add more projects there I think.

**Comment by advayDev1** [comment]
@brunobowden has added the 'allPlatforms' project which has android and ios working.
