### ISSUE TITLE
Setup Nemo code quality & code coverage

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#380]
If the sonarsource folks deem us acceptable.

We'll get something like:
http://nemo.sonarqube.org/dashboard/index?id=jquery

**Comment by brunobowden** [comment]
I'm fine for this. Not sure what the best value is we get out of it.

**Comment by advayDev1** [comment]
I can't find any Groovy-based code coverage that is online and automatic.
The best I could find is coveralls.io which has Java not Groovy.

If they say yes, we don't need to do anything.  If they so no, I'll just close it - not worth effort beyond that I think.

**Comment by brunobowden** [comment]
I was interested in tracking code coverage if we could do that.

**Comment by advayDev1** [comment]
done

**Comment by brunobowden** [comment]
@advayDev1 - can you add a link to the documentation?

**Comment by advayDev1** [comment]
http://nemo.sonarqube.org/dashboard/index?id=com.github.j2objccontrib.j2objcgradle
