### ISSUE TITLE
0.5.0-alpha release

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#382]
@brunobowden  - for discussing what should or shouldn't be in the eventual release.
there's a bunch of stuff marked in the milestone:

my personal goal is eliminate any code defects outside xcode/pods: https://github.com/j2objc-contrib/j2objc-gradle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Atype%3Abug+-label%3Acat%3Axcode

**Comment by brunobowden** [comment]
The automatic configuration will the big breakthrough. That'll make it so much easier for people to use. Not sure how difficult it is, but I'd like to solve #255 (download of j2objc version) but I think we should push that off to another release.

**Comment by advayDev1** [comment]
yeah i put the time into the auto config vs. the bugs.  i will not have time to do the bugs.

**Comment by advayDev1** [comment]
Blocker on release/tag: #549
