### ISSUE TITLE
Bad Release for v0.4.1-alpha ?

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#387]
@brunobowden ,

I have the 0.4.1-alpha dist jar and source jar from plugins.gradle.org and I'm seeing errors from missing functionality though.  For example the source for Utils.groovy is missing the lines regarding enabledArchs, and when using those in my build file they fail with an error message that is older than v0.4.1.

Are you sure you published the right revision to plugins.gradle.org?

**Comment by brunobowden** [comment]
@advayDev1 - you're correct. I checked the history and my old commit was built from commit #332 (0.4.0 version). My mistake for not updating the branch.

**Comment by brunobowden** [comment]
I've published 0.4.2 - so please check that this works for you.
