### ISSUE TITLE
Add into published metadata a commit SHA

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#394]
Whenever you publish the plugin it should create a file with the current git commit sha and an indication of whether you have an unclean working directory/index.

**Comment by brunobowden** [comment]
It shouldn't just be an indication but prevent you from publishing if you
aren't synced to a commit where it was merged in to master. Also for the
publish step, that could be an extended version of all the tests at some
point.

**Comment by advayDev1** [comment]
Yeah my internal plugin assert fails on publishPlugins when git is unclean.
I'm publishing that plugin to plugins.gradle.org to reuse it here
it will take a few more minutes =)

**Comment by brunobowden** [comment]
Good idea... I think it makes to have that as a separate plugin. Send me an
email afterwards describing this. I think it would be great to share this
with Gradle. This could become a blog post or event part of their
"plugin-publish" if that's ok for you. I think it has value for a wider
community that uses Git and GitHub.

**Comment by advayDev1** [comment]
Alright see #395 .

Plugin code is at https://github.com/madvay/git-build-info - it is standard Apache 2, so feel free.
I doubt Gradle will care though, I'm sure there's some swiss army knife-type plugin that does a billion things with this being one.  I just didn't look for one when it takes a hundred lines to write it and be certain what it does.
