### ISSUE TITLE
Setup Windows CI on Appveyor

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#400]
Looks simple enough.

**Comment by advayDev1** [comment]
@brunobowden - as before, I will do a direct commit via @madvayApiAccess with the initial config, and PR any config change.  please do post-review is as needed.  I will put the commit sha here for clarity.

**Comment by brunobowden** [comment]
Looks like Windows support on Travis has been an open issue for a long
time. This seems to be the current tracking issue - I'd suggest subscribing
to that: https://github.com/travis-ci/travis-ci/issues/2104

**Comment by advayDev1** [comment]
alright, you can do a post-review of #401 and LMK anything you want fixed.
I'll also get a normal PR out to put the README, etc.
The failing tests are in #402
