### ISSUE TITLE
Auto Resolve Dependencies

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#41]
When using:
 
```
translateClassPaths "json-20140107.jar", "javax.inject-1.jar",
translateSourcepaths "some-sources.jav"
```
the dependencies should be resolved automatically.

**Comment by confile** [comment]
@advayDev1 I suppose you know more about this?

**Comment by advayDev1** [comment]
Can you be more specific about what you mean by dependencies?  Are these transitive dependencies of the instant jars on other jars?

**Comment by confile** [comment]
@advayDev1 I mean transitive dependencies.

**Comment by confile** [comment]
I mean that they should be resolved like in: 

```
dependencies {
  compile ...
}
```

**Comment by advayDev1** [comment]
are you asking for:
1) compile dependencies named in the dependencies DSL block should be automatically converted into translate* flags?
or 
2) such dependencies, whether in the dependencies DSL block or mentioned in translate* flags, should have their transitive dependencies included automatically?

**Comment by confile** [comment]
No to make it simple. I want that our plugin auto resolves transitive dependencies. That's it.

**Comment by advayDev1** [comment]
I don't know if we should do that.  I know in my case it would actually be harmful, and I can imagine it would be for many people.  Consider that your projectA uses libB.  libB relies on Guava.  With this, we would use the public Guava jar as referenced in libB's pom file (for example), but that would be wrong, we should instead use the guava in the j2objc dist library.  This could happen for any library.  There is no way to map say a Maven pom file transitive dependency to the name in the j2objc lib directory (afaik).

I assume you want this to make --build-closure easier to manage, as it would be for me as well.  But as soon as I started doing something that wasn't simple (for example, in my case my projectA relies on libB which relies on libC which has some JNI components that I then had to create a libCModified version myself which stubs or replaces with OCNI those JNI components), it did not work to do it automatically.

**Comment by advayDev1** [comment]
So, the right way to do this is use:
project.sourceSets.main.compileClasspath.getAsPath()
project.sourceSets.test.compileClasspath.getAsPath()

they can just be added to translateClasspath.

Also, #112 does not need to be done to do this, only nice-to-have.

Need to solve #180 because otherwise the junit.jar for example we reference in the translateClasspath may be of a different version than the junit.jar in the j2objc dist.
