### ISSUE TITLE
Sample project on horizon?

### ISSUE THREAD

**Issue by jjroloff** [j2objc-contrib/j2objc-gradle#413]
Hi to all contributors - thanks for all the great work. I've been trying to build a project with j2objc-gradle, but haven't quite made it (but lots of hours reading and trying things). I'm just starting with something simple - using the Gson source to test everything out.

If anyone has a simple (or complex) project file that can just be opened in Android Studio or IntelliJ, that would be **so** useful as a starting point. Bruno mentioned something like this is on the roadmap in a Gradle conference video, and I'd just like to +1 (actually,+100) that idea. Thanks again for your great work this!

**Comment by advayDev1** [comment]
Hi @jjroloff,

#370 tracks a sample project (closing as dupe).

Also, I've added the simplest possible project now as a system test #409 and in #411 you can see an in-progress test for multiple projects.

If you can get the system tests passing on your machine, then we can see what is up with your project (I suspect re: gson, your issue will be very similar to #372).

Thanks!
