### ISSUE TITLE
Bridging header file not found error

### ISSUE THREAD

**Issue by ph1lb4** [j2objc-contrib/j2objc-gradle#418]
We have successfully translated, compiled and added (with j2objcXcode task) our Java Model to our Xcode Swift project.

However when we import certain classes (does not happen with all) in the bridging header the following error occurs:
```
Bridging-Header.h:6:9: note: in file included from Bridging-Header.h:6:
#import "Template.h"
        ^
Template.h:10:10: error: 'com/test/ReceiverIF.h' file not found
#include "com/test/ReceiverIF.h"
```

Interesting is that the class ReceiverIF was translated correctly and can be found in the generated sources.

**Comment by advayDev1** [comment]
i assume the bridging header is a switch thing?

i don't use Swift; perhaps @brunobowden knows what's up.

**Comment by ph1lb4** [comment]
The bridging header is a Swift thing. However, it is not directly related to Swift. I also happens when we create an Objective-C class and import the class "Template.h" there.

**Comment by advayDev1** [comment]
Check the auto-generated xcconfig files.
Is the `-I` include path set correct?
Does the file hierarchy in the include path indeed have `com/test/ReceiverIF.h`

**Comment by ph1lb4** [comment]
I just checked, there is no -I include path. Is there a documentation on how to set that?

**Comment by advayDev1** [comment]
Check `shared/build/j2objcOutputs/src/main/objc/`
is it flat or hierarchical?

If that directory itself is flat, then yes this is a bug in either j2objcTranslate or j2objcAssembleSource.
If that directory is hierarchical, then this is an issue possible with j2objcXcode.

Can you show your j2objcConfig here?  It can affect the flat vs. hierarchy.

**Comment by ph1lb4** [comment]
The hierarchy was a good hint. It was indeed flat but not a problem with j2objcXcode.
I found the solution here http://stackoverflow.com/questions/31292238/j2objc-xcode-build-rules-not-recognizing-imports
Simply adding --no-package-directories to the translateArgs did the trick!

**Comment by advayDev1** [comment]
Interesting... I'm able to import fully-pathed headers without any issue, and I do not use no-package-directories in my j2objcConfig.  But I also manually import the headers into Xcode as a folder reference not as a group as the j2objcXcode task does.  So it looks like this is by design.

**Comment by advayDev1** [comment]
Actually a FAQ might be useful.

**Comment by brunobowden** [comment]
Maybe even a warning on using `--no-package-directories` as that's the common case for most people.

**Comment by advayDev1** [comment]
Let's make the warning only if j2objxXcode is run though.  It is just fine if you don't use it, and it is an optional task.
