### ISSUE TITLE
Feature to convert an entire library jar via j2objc

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#429]
`translateAllSources=true` will cause all files in the translateSourcepaths to be compiled.  This should be a good step to solving #419 .  Namely, let's say you have 2 projects depending on GSON.   Instead of each project retranslating GSON, you can create a small gradle project that looks like:
```gradle
// third_party/gson/build.gradle
plugins {
  id 'java'
  id 'j2objc-gradle' // pseudocode
}

dependencies {
  compile "com.google.code.gson:gson:2.3.1"
}

j2objcConfig {
  translateAllSources true
  finalConfigure()
}
```

Then your other projects using gson, instead of directly depending on `com.google.code.gson:gson:2.3.1` would depend on `project(":third_party_gson").

@brunobowden, thoughts on this design?

**Comment by brunobowden** [comment]
This makes sense to me. How does it handle different versions of the same
library? That's a bit of a concern anyway...

**Comment by advayDev1** [comment]
I have no solution for that.  If your shared1 and shared2 use gsonA and gsonB, the above procedure would force you to pick gsonA or gsonB to put in the build.gradle above.  So you can't ignore the error, but you are forced to manually pick one

**Comment by brunobowden** [comment]
I think that's a reasonable request, particularly for now.

**Comment by advayDev1** [comment]
I don't think there is actually a solution anyway.  You can't actually have 2 versions of the same iOS class.  Gradle just picks one consistent version of a duplicate transitive dependency for you behind the scenes.
