### ISSUE TITLE
XcodeTask / Pods needs to handle dependencies

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#432]
j2objcXcode doesn't handle dependencies at all.  Need to configure the include paths, headers, static libraries etc.  Also need to figure out how one project's pod spec depends on another's.

**Comment by brunobowden** [comment]
Not sure how involved this is going to be. Once you get your Guava changes merged in, I'll take a look. If it's pretty involved, I may suggest release 0.5 before I go on my Sept 2-20 trip to Europe. Then fix this up on my return. I'll at least take a look at beforehand.

**Comment by advayDev1** [comment]
with xcode 7 support, I think this is the highest priority must have for 0.5.0 left.

**Comment by advayDev1** [comment]
The PR should succeed on https://github.com/j2objc-contrib/j2objc-gradle/tree/master/systemTests/multiProject1

**Comment by advayDev1** [comment]
task dependsOn https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/DependencyResolver.groovy#L164
