### ISSUE TITLE
import "JreEmulation.h" when develp with Swift

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#435]
Do I have to use the following in my BridgingHeader?  

```
#import "JreEmulation.h"
```

I found there [here](https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#how-do-i-develop-with-swift). 

So far I could work without it. Is this just an example or what?

**Comment by brunobowden** [comment]
Yes, that's needed. I thought it was necessary for initializing J2ObjC
objects within Swift. Attempt that with and without the header.
