### ISSUE TITLE
Include Header files in BridgingHeader without --no-package-directories 

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#436]
I use Swift and have a file translated as: 

![main](https://cloud.githubusercontent.com/assets/64265/9556512/847681ba-4dd5-11e5-8ea5-cdcea6e671e2.png)

I do not use this option: ``--no-package-directories``.

In my BridgingHeader I have to include the file as: 

``#import "BTimer.h"`` instead of ``#include "core/helper/timer/BTimer.h"``.

Why does the second version fail? The packages included with j2objc can also be included like: 

```
#import "java/util/List.h"
```

**Comment by advayDev1** [comment]
1.  Always use #import not #include.
2.  Follow the instructions regarding USER_HEADER_SEARCH_PATHS here:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#how-do-i-manually-configure-my-xcode-project-to-use-the-translated-libraries

There's no modification to the plugin required here.
