### ISSUE TITLE
Could not resolve all dependencies for configuration Could not find :jre_emul:.

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#437]
When I build my shared project I get the following error: 

```
gradle shared:build
j2objc-gradle plugin was built outside of an official release.
If you encounter issues, please use an official release from:
    https://github.com/j2objc-contrib/j2objc-gradle/releases
j2objc-gradle plugin was built outside of an official release.
If you encounter issues, please use an official release from:
    https://github.com/j2objc-contrib/j2objc-gradle/releases
Project 'shared' is missing finalConfigure():
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#How-do-I-call-finalConfigure

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mg/Downloads/Majestella/shared/build.gradle' line: 108

* What went wrong:
A problem occurred evaluating project ':shared'.
> Could not resolve all dependencies for configuration ':shared:j2objcTranslationClosure'.
   > Could not find :jre_emul:.
     Searched in the following locations:
         https://jcenter.bintray.com//jre_emul//jre_emul-.pom
         https://jcenter.bintray.com//jre_emul//jre_emul--sources.jar
         https://repo1.maven.org/maven2//jre_emul//jre_emul-.pom
         https://repo1.maven.org/maven2//jre_emul//jre_emul--sources.jar
         https://oss.sonatype.org/content/repositories/snapshots//jre_emul//jre_emul-.pom
         https://oss.sonatype.org/content/repositories/snapshots//jre_emul//jre_emul--sources.jar
         https://oss.sonatype.org/content/repositories/google-snapshots//jre_emul//jre_emul-.pom
         https://oss.sonatype.org/content/repositories/google-snapshots//jre_emul//jre_emul--sources.jar
         file:/Users/mg/Downloads/Majestella/shared/lib/jre_emul--sources.jar
         file:/Users/mg/Downloads/Majestella/shared/lib/jre_emul-sources.jar
     Required by:
         Majestella:shared:1.0
```

Not sure why the plugin searches for ``jre_emul--sources.jar`` this must not be translated so it could be skipped and taken from the already translated source in the j2objc package. 

Here is my build.gradle: 

```
apply plugin: 'java'
apply plugin: 'apt'
apply plugin: 'eclipse'
apply plugin: 'com.github.j2objccontrib.j2objcgradle'

sourceCompatibility = 1.7
version = '1.0'

eclipse {
  classpath {
     downloadSources=true
     downloadJavadoc=true
  }
}

buildscript {
  repositories {
    mavenCentral()
    jcenter()
    maven {
      url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
    maven {
      url uri('../../0Gradle-Repo')
    }
  }
  dependencies {
    classpath 'com.jimdo.gradle:gradle-apt-plugin:0.5-SNAPSHOT'
    classpath files('/Users/mg/Downloads/j2objc-gradle/build/libs/j2objc-gradle-0.4.3-alpha-SNAPSHOT.jar')
  }
}

repositories {
  mavenCentral()
  maven {
    name = "sonatype"
    url = "https://oss.sonatype.org/content/repositories/snapshots/"
  }
  maven {
    name = "sonatypeGoogle"
    url = "https://oss.sonatype.org/content/repositories/google-snapshots/"
  }
  flatDir {
    dirs 'lib'
  }
}

dependencies {
	apt (project(':base'))
  	apt 'com.google.auto.factory:auto-factory:1.0-beta2'
  	apt 'com.google.dagger:dagger:2.0.1'
  	apt 'com.google.dagger:dagger-producers:2.0-beta'
  	apt 'com.google.dagger:dagger-compiler:2.0.1'

    compile (project(':base'))
	compile 'com.google.guava:guava:18.0'
	compile 'javax.inject:javax.inject:1'
    compile 'org.json:json:20140107'

  	compile 'com.google.auto.factory:auto-factory:1.0-beta2'
  	compile 'com.google.auto.service:auto-service:1.0-rc2'
  	compile 'com.google.dagger:dagger:2.0.1'
    compile 'com.google.j2objc:j2objc-annotations:0.9.8'

    compile name: 'jre_emul'

}


task sourcesJar(type: Jar, dependsOn: classes) {
  description "Create source jar."
  classifier = 'sources'
  from(sourceSets.main.allSource) 
}

task javadocJar(type: Jar, dependsOn: javadoc) {
  description "Create javadocs."
  classifier = 'javadoc'
  from javadoc.destinationDir
}

artifacts {
  archives sourcesJar
//  archives sourcesProcessorJar
//  archives javadocJar
}
 

// J2ObjC Plugin settings:
j2objcConfig {
    xcodeProjectDir '../ios'  // Xcode workspace directory (suggested directory name)
    xcodeTarget 'Majestella'     // iOS app target name (replace with existing app name)

	autoConfigureDeps = true

  	translateArgs "--no-package-directories"
  	translateArgs "--prefixes", "prefixes.properties"
  	translateArgs "-use-arc"
  	translateArgs "--doc-comments"
  	translateArgs "--build-closure"
  	translateArgs "--generate-deprecated"

	extraObjcCompilerArgs '-fobjc-arc'

    testMinExpectedTests 0


    finalConfigure()          // Must be last call to configuration
}
```

**Comment by advayDev1** [comment]
Why are you compiling against the j2objc emulated JRE instead of a normal one?
```
 compile name: 'jre_emul'
```

**Comment by confile** [comment]
@advayDev1 Because I need to use things like. 

```
android/os/AsyncTask.java
```

How else would you include this?

**Comment by confile** [comment]
@advayDev1 What do you mean by:

> instead of a normal one?

**Comment by brunobowden** [comment]
The J2ObjC Gradle plugin currently requires a Java only project. If you
include something like "android/os/AsyncTask.java", that's Android only
code. Though j2objc can translate that, the java only build will fail. This
is a restriction that we may relax in the future but for now you can't use
AsyncTask in both the Android and J2ObjC Gradle plugin.

**Comment by advayDev1** [comment]
While @brunobowden is correct, @confile the issue you are having is trying to link in an Objective-C implementation of the Java Runtime into a Java library.  That simply can't work.  Take for example the AsyncTask you want to include:
https://github.com/google/j2objc/blob/master/jre_emul/android/frameworks/base/core/java/android/os/AsyncTask.java
That is an iOS implementation of AsyncTask, not one you could even use in Java.

Your Java project is compiled against the real JDK and run against the real JRE by default.  You can't manually link in your own non-Java "JDK".  That being said, if you find, for example, an Android support JAR implementing android.os with source and sufficiently licensed, you might try using the regular JDK and also adding such a JAR to your dependencies.

**Comment by confile** [comment]
Well I use AsyncTask with the old J2objc plugin in the shared project and it worked well on iOS and Android.

@advayDev1 Why do I need the source for AsyncTask. It for ios it is included in jre_emul und for android it is in the system lib. For my shared java project I now use: 

```
compile 'com.google.android:android:4.1.1.4'
```

AsyncTask and other android.os lib where introduced in j2objc to work in the shared project on both sides Android and ios.

**Comment by brunobowden** [comment]
We made a design decision with the plugin to only support Java projects for
now. There's an enhancement request to relax this restriction:

https://github.com/j2objc-contrib/j2objc-gradle/issues/181

**Comment by confile** [comment]
Whatever it still works for me with compile 'com.google.android:android:4.1.1.4'.

**Comment by advayDev1** [comment]
Btw, by adding 'com.google.android:android:4.1.1.4' you did exactly that: added Java source for android.os.*. 

Anyway, if this issue is not a problem anymore, please close.

Also, I do not think the project should recommend using this JAR.
Per the POM for this package:
https://repo1.maven.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.pom,
I'm guessing it isn't officially from AOSP or Google because:

1. The version number is many years out-of-date with no newer package available.
2. The POM comment states: 
     
    > While the EULA for the Android SDK restricts distribution of those binaries, the source code is licensed under Apache 2.0 which allows compiling binaries from source and then distributing those versions.

3. The SCM linked to is not the official one (https://android.googlesource.com/).

It's a shame that there isn't an easy way to verify who is putting these JARs online and whether they are trustworthy or not.

**Comment by advayDev1** [comment]
1.  jre_emul should never be a Java dependency of your Gradle project.  That simply won't work.
2.  We do not support Android-specific dependencies for now, especially not unofficial Android source code.
