### ISSUE TITLE
Best Practice to include generated sources?

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#438]
I have sources generated with the APT plugin. 

What is the best way to include them for j2objc translation?

Should I add them to the sourceSet: 

```
sourceSets {
  apt{
    java{
      srcDir 'build/source/apt'
    }
  }
}
```

or should I add them with: 

```
generatedSourceDirs "build/source/apt"
```

or should I do both?

**Comment by advayDev1** [comment]
Question: Does the APT plugin automatically add your generated sources to the main.java source set?
If yes, do neither of the above.

If not, use generatedSourceDirs.

**Comment by brunobowden** [comment]
APT requires the android plugin, so I don't believe it will work with
J2ObjC Gradle Plugin.

**Comment by advayDev1** [comment]
Actually @brunobowden , @confile is using a non-standard version of APT that claims to support Java-only:
https://github.com/Jimdo/gradle-apt-plugin/blob/master/src/main/groovy/com/jimdo/gradle/AptPlugin.groovy

Of course, Jimdo's version is not maintained so issues discovered may be a problem with APT.

**Comment by confile** [comment]
@brunobowden [APT](https://github.com/Jimdo/gradle-apt-plugin/blob/master/src/main/groovy/com/jimdo/gradle/AptPlugin.groovy) works great with Java and J2objc. I have used it with the old one file j2objc.gradle plugin. 

@advayDev1 No the APT plugin does not add the source to the source set as far as I see so I will use generatedSourceDirs.

**Comment by advayDev1** [comment]
Please see the new support for generated source and annotation processing here: https://github.com/j2objc-contrib/j2objc-gradle/issues/517

Please try to use the same method as andrewfunston documents there, as it seems to work end to end.
