### ISSUE TITLE
convert xcodeTarget to enumerated list

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#441]
PR #353 matches multiple Xcode targets based on substring matching. Proper support means enumerating the list of targets instead. Given that it's now multiple targets, it also means that the name changes: xcodeTarget => xcodeTargets. With a breaking change like this, I think it would be wise to provide error message for the old syntax explaining how to fix it. Then remove that old syntax (and error) on a future release.

Before:

    xcodeTarget 'IOS-APP'

After

    xcodeTargets 'IOS-APP', 'WatchKit App', 'WatchKit Extension'

**Comment by confile** [comment]
+1
