### ISSUE TITLE
Sources specified with generatedSourceDirs are not translated

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#442]
I tried to Copy some sources in ``build/source/base``. To be translated afterwards using the following task: 

```
task copyBaseSources(type: Copy) {
  description "Copy all source files from majestella-base into the current project."
  exclude '**/*processor*'  // Annotation Processors should not be copied and translated
  from project(":base").projectDir.toString() + "/src/main/java"
  into project.projectDir.toString() + "/build/source/base"
}

tasks.j2objcTranslate.dependsOn += copyBaseSources
```

When I do ``gradle shared:build`` only the source files in the ``src/main/java`` folder where translated.

I also tried: 

```
sourceSets {
  apt{
    java{
      srcDir 'build/source/apt'
      srcDir 'build/source/base'
    }
  }
}
```

The same result sources in "build/source/apt", "build/source/base" where not translated.

How can I fix that?

**Comment by advayDev1** [comment]
The plugin does not use custom sourcesets, it only uses `main.java` - it cannot know about apt.java. 

If you want the plugin to translate it, the files need to be in src/main/java, added to main.java sourceset or in the generated sources flag (pick exactly one).

**Comment by confile** [comment]
@advayDev1 I do not get your point so I try to make it more clear. I build a dependent project then I copied the java files of this project to into "build/source/base". Then I tried two things.

1. Add  build/source/base to the ``generatedSourceDirs`` flag
 
 ```
generatedSourceDirs "build/source/base"
```
This does not translate the java files in "build/source/base"
2.  The I added the files to the source set: 

  ```
sourceSets {
  src {
    main{
      java{
        srcDir 'build/source/apt'
      }
    }
  }
}
```
Adding the files to the source set worked.

Why does ``generatedSourceDirs`` not translate the java files in the folder I specify? What is this flag good for? Thanks for help @advayDev1

**Comment by advayDev1** [comment]
If shared depends on base, and you already have:
```
// in shared/build.gradle
dependencies {
   compile project(':base')
// others
}

j2objcConfig {
  autoConfigureDeps = true
// others
}
```

You should never be translating code that is a part of 'base' in 'shared's j2objcConfig.  Instead 'base' should translate its own source, and 'shared' should link to it.  That is how it is supposed to work.

**Comment by confile** [comment]
I know but I need this workaround since ``autoConfigureDeps = true`` does not work correctly as reported here: 
https://github.com/j2objc-contrib/j2objc-gradle/issues/440

**Comment by confile** [comment]
@advayDev1 Still, why do I need ``generatedSourceDirs``?

**Comment by advayDev1** [comment]
If autoConfigureDeps = true doesn't work, change the build to:
```gradle
// in shared/build.gradle
dependencies {
  compile project(':base')
  j2objcLinkage project(':base')
}
```

**Comment by confile** [comment]
@advayDev1 I tried this it also does not work see #440

**Comment by advayDev1** [comment]
Should be fixed.  Please see the new support for generated source and annotation processing here: https://github.com/j2objc-contrib/j2objc-gradle/issues/517

Please try to use the same method as andrewfunston documents there, as it seems to work end to end.
