### ISSUE TITLE
Correctly translate generatedSourceDirs (and document)

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#445]
I looked at the [Plugin Config](https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy#L122) but I could not figure out what ``generatedSourceDirs``. It does not change anything if I use it or not. The doc says when using Dagger. I use dagger and I do not need it. Although I use dagger annotations too.

Could you please be more specific on what it does and when to use it?

**Comment by brunobowden** [comment]
That may be out of date with the annotation processor support in j2objc. I don't have enough knowledge to know exactly what we should say about it instead.

**Comment by confile** [comment]
Could you delete it? I still don'T see what it does.

**Comment by advayDev1** [comment]
Actually this is in fact a code defect (well if this arg is to have much practical use, it is).

https://github.com/j2objc-contrib/j2objc-gradle/blob/69f77aab754a5d75e18a76b5788063fd2b266943/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TranslateTask.groovy#L227

Generated source files are only passed on the source path, not on the list of files to translate.  So they are only translated if 1) you change a normal src/main/java file 2) the generated source file is referenced by the non-generated normal file AND 3) you have --build-closure on.

I think the better solution is for TranslateTask, CycleFinderTask, and TestTask to treat generated source files no different from additional files in the source set (that doesn't mean the user adds them to the source set, we just treat them as if they had).

However, I don't use generatedSrcFiles, I don't remember who needed it or what for.

**Comment by advayDev1** [comment]
Please see the new support for generated source and annotation processing here: https://github.com/j2objc-contrib/j2objc-gradle/issues/517

Please try to use the same method as andrewfunston documents there, as it seems to work end to end.
