### ISSUE TITLE
XcodeTask must include references to existing referenced native libraries

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#446]
You can use the ``linkJ2objcLibs`` to link precompiled libs with j2objc-gradle. 

What I have a pre translated .m and .h files that are not part of .a library. How can I include them too?

As an example the following lib: https://github.com/vals-productions/sqlighter It has implementations written in objective-c which should not be translated from any Java source.

**Comment by brunobowden** [comment]
OCNI could be used but that's kind of a hassle: http://j2objc.org/docs/Writing-Native-Methods.html

If those files are already translated, then it would be best to have them be translated every time as part of the build.

**Comment by confile** [comment]
Correct me if I am wrong. When I use OCNI on the objective-c side you are forced to use JNI on the Android side. This is not what I want. Please take at: https://github.com/vals-productions/sqlighter

The lib has Java implementations for Android and implementations written in Objective-C for the ios side. 

This plugin should have a way to handle this as I suppose there will be more libs like this in future.

**Comment by brunobowden** [comment]
@advayDev1 - what's your opinion on this?

**Comment by advayDev1** [comment]
The correct thing is not to include the files in your gradle project, but instead to link/include them via a separate gradle project.  So create a separate gradle project following the instructions here:
https://docs.gradle.org/2.4/userguide/nativeBinaries.html
(unrelated to the plugin).

Then follow this FAQ (where the project you created above is called 'A'):
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#how-do-i-setup-a-dependency-on-a-native-library-project

Make sure your settings in j2objcConfig use a prefixes file as specified by that third-party library:
https://github.com/vals-productions/sqlighter#j2objc
Otherwise the class names won't match up.

**Comment by advayDev1** [comment]
BTW: The separate Gradle project 'A' is for the source and headers of the third-party project.

**Comment by confile** [comment]
@advayDev1 Thank you. I created a project for the native files and compiled the lib.
```
model {
    components {
        sqlighterlib(NativeLibrarySpec)
    }
}
```
The compilation works without problems.
I included the native lib in my shared project: 
```
extraNativeLib project: ':sqlighter', library: 'sqlighterlib', linkage: 'static'
```
Then I did ``gradle j2objcXcode`` and I get the following error: 

```
No static library binary available for library 'sqlighterlib' with [flavor: 'default', platform: 'x86_64', buildType: 'release']
```
Here are the native libs that are generated. 

<img width="370" alt="binaries" src="https://cloud.githubusercontent.com/assets/64265/9733115/1960fb74-5629-11e5-8e8c-2b4d10b4ab48.png">

It seems that the correct libs are generated but j2objc-gradle cannot link them.

**Comment by advayDev1** [comment]
Yes j2objcXcode and pods haven't been updated to support any of the dependency features I've added recently.  Someone (you?) who actually uses pods would need to implement it:
https://github.com/j2objc-contrib/j2objc-gradle/issues/432

**Comment by confile** [comment]
@advayDev1 I will try this. Any advices what to do?

**Comment by advayDev1** [comment]
Let's just solve the issue of an existing native library here, it is simpler than solving all dependencies.

Since I am definitely not a pod expert, here is a guess as to how this should work:
- Given an external library, I don't think the plugin should be responsible for _creating_ a podspec for that library.  So I'd manually create one for that other library and put it somewhere easy to find.
- Add an optional map argument to extraNativeLib pointing to the podspec for that library.
- Somehow reference that podspec in the the files that are created in XcodeTask.

There's more work for referencing other j2objc projects that the plugin itself makes, but first let's get the easier case of an existing library done.

**Comment by advayDev1** [comment]
thanks @confile  - assigned to you

**Comment by advayDev1** [comment]
@confile, while what I've stated above is an issue, you have a bigger issue :)
You haven't compiled that sql library with all the required ios architectures.

Start with this Gist for the sql library's build.gradle:
https://gist.github.com/advayDev1/2bdf04f05c2bafd7df25

Fix all the places it says "FIX THIS" and put the right library name everywhere it says __YOURLIBRARY__ (like `sqlighterlib`).

Then just do the build for that library, and do the `build` for your overall project.
Remember build skips the pod stuff, so let's just get your build working first.

**Comment by confile** [comment]
@advayDev1 Sure I use only x_86:

```
j2objc.release.enabled=false
j2objc.enabledArchs=ios_x86_64
```

**Comment by brunobowden** [comment]
That'll only build for the iOS simulator. You need ios_armv7 and ios_arm64
to also build for the iOS devices.

Should we add a warning for "j2objc.enabledArchs=ios_x86_64"? To explain
this issue?

**Comment by brunobowden** [comment]
The plugin will create the podspec for the translated code. it's not that
difficult - you can see an example copy below.

As a stop gap, we could add support for the plugin to reference extra
podspec's in the Podfile. The Podfile is what is loaded by the Xcode
Workspace and the leads to all the magic happening with CocoaPods. For now,
all these files can be manually edited but the Podfile will be overwritten
when j2objcXcode is run again.

```
Pod::Spec.new do |spec|
spec.name = 'j2objc-base-debug'
spec.version = '1.0'
spec.summary = 'Generated by the J2ObjC Gradle Plugin.'
spec.public_header_files = 'j2objcOutputs/src/main/objc/**/*.h'
spec.resources = 'j2objcOutputs/src/main/resources/**/*'
spec.requires_arc = true
spec.preserve_paths = 'j2objcOutputs/src/main/objc/**/*'
spec.libraries = 'ObjC', 'guava', 'javax_inject', 'jre_emul', 'jsr305',
'z', 'icucore', 'base-j2objc'
spec.xcconfig = {
    'HEADER_SEARCH_PATHS' =>
'/Users/brunobowden/dev/j2objc-versions/j2objc-0.9.8/include',
    'LIBRARY_SEARCH_PATHS' =>
'/Users/brunobowden/dev/j2objc-versions/j2objc-0.9.8/lib
/Users/brunobowden/dev/taptap/base/build/j2objcOutputs/lib/iosDebug'
}
end

```

**Comment by advayDev1** [comment]
@brunobowden @confile - there are 3 issues:
1. sql library needs to be built with proper architectures AND proper naming conventions AND be fat
2. your project overall needs to have the right set of architectures to support simulation (not technically required, but pretty useful)
3. the pod/podspec files need to list the dependency to the sql library.

let's start with the first issue first.
You need to setup the gradle file for the sql library correctly, otherwise your main project has no way of linking to it correctly.  The Gist above sets up your sql library gradle file in a way that matches the conventions of j2objc so that linking can be done correctly.

What does the sql build.gradle file look like right now?

**Comment by confile** [comment]
@brunobowden I used this ``j2objc.enabledArchs=ios_x86_64`` to build for the simulator only to get a faster translation and compile.

**Comment by confile** [comment]
@advayDev1 I tried what you said but I got this error: 

```
16:20:45.705 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.assemble' to state Mutated.
16:20:45.705 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.assemble' to state Finalized.
16:20:45.705 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.assemble' to state SelfClosed.
16:20:45.705 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.assemble' to state GraphClosed.
16:20:45.706 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Transitioning model element 'tasks.assemble' from state GraphClosed to GraphClosed
16:20:45.715 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 2.633 secs
16:20:45.721 [ERROR] [org.gradle.api.Project] Project 'sqlighter' is missing finalConfigure():
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/FAQ.md#How-do-I-call-finalConfigure
16:20:45.729 [ERROR] [org.gradle.BuildExceptionReporter] 
16:20:45.730 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:20:45.730 [ERROR] [org.gradle.BuildExceptionReporter] 
16:20:45.730 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
16:20:45.731 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/mg/Downloads/Majestella/sqlighter/build.gradle' line: 44
16:20:45.731 [ERROR] [org.gradle.BuildExceptionReporter] 
16:20:45.731 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
16:20:45.731 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating project ':sqlighter'.
16:20:45.732 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to apply plugin [class 'org.gradle.language.objectivec.plugins.ObjectiveCLangPlugin']
16:20:45.732 [ERROR] [org.gradle.BuildExceptionReporter]    > Cannot add rule org.gradle.language.objectivec.plugins.ObjectiveCLangPlugin$Rules#registerLanguage(org.gradle.platform.base.LanguageTypeBuilder<org.gradle.language.objectivec.ObjectiveCSourceSet>) for model element 'languages' at state Created as this element is already at state GraphClosed.
16:20:45.733 [ERROR] [org.gradle.BuildExceptionReporter] 
16:20:45.733 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
16:20:45.733 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
16:20:45.734 [LIFECYCLE] [org.gradle.BuildResultLogger] 
16:20:45.735 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

Here is my [build.gradle](https://gist.github.com/confile/b3f3b5eb0a17b9c42a66)

Here is [native.gradle](https://gist.github.com/confile/32c4817b4075b492123a)

**Comment by advayDev1** [comment]
No, your build.gradle for sqllighter can't have j2objc plugin applied - there's no Java to translate!

What you called 'native.gradle' should instead be your entire sqlighter/build.gradle file.

**Comment by confile** [comment]
@advayDev1 I did the change. Now I got the following after ``gradle build``:

```
:sqlighter:ios_arm64DebugSqlighterlibSharedLibrary SKIPPED
:sqlighter:compileIos_arm64DebugSqlighterlibStaticLibrarySqlighterlibObjcpp
/Users/mg/Downloads/Majestella/sqlighter/src/sqlighterlib/objc/SQLighterRsImpl.m:76:54: error: cannot initialize a parameter of type 'const jbyte *' (aka 'const signed char *') with an rvalue of type 'const void *'
    IOSByteArray *ba = [IOSByteArray arrayWithBytes: [ d bytes] count:(int)[d length]];
                                                     ^~~~~~~~~~
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:152:1: note: passing argument to parameter 'buf' here
PRIMITIVE_ARRAY_INTERFACE(byte, Byte, jbyte)
^
/Applications/J2Objc/j2objc-0.9.8b/include/IOSPrimitiveArray.h:61:54: note: expanded from macro 'PRIMITIVE_ARRAY_INTERFACE'
+ (instancetype)arrayWith##U_NAME##s:(const C_TYPE *)buf count:(NSUInteger)count; \
                                                     ^
1 error generated.

:sqlighter:compileIos_arm64DebugSqlighterlibStaticLibrarySqlighterlibObjcpp FAILED

FAILURE: Build failed with an exception.
```

**Comment by advayDev1** [comment]
that's something to take up with the sqlighter folks.  it has nothing to do with our plugin.  file a bug with them.

possibly check what version of j2objc they are using versus you.

**Comment by advayDev1** [comment]
any luck with this?   i don't currently see a bug re: the plugin here.

**Comment by confile** [comment]
When I compile the code in Xcode it works fine. With the gradle-j2objc plugin I still getting the error.

**Comment by advayDev1** [comment]
Can you please be more specific?  What did you build in Xcode?
If you make share a github of the exact xcproj and other files that you are building in Xcode we might be able to debug.

**Comment by confile** [comment]
I translated the interfaces with j2objc and included the .h and .m files of the implementations of these interfaces to my Xcode project.

**Comment by advayDev1** [comment]
@confile - Ok, please go into Xcode and do the following:
Menu View -> Navigators -> Show Report Navigator.
In the left pane, find a successful 'Build' and within the report for that Build find a message like:
'Compile SQLighterRsImpl.m' (if that is the file with an error).
Right click that line and click Copy and paste the clang command here (minus anything sensitive).

You may need to Clean then Build if that file hasn't changed recently.

**Comment by advayDev1** [comment]
I do not think we can generically implement this in the plugin anytime soon as there is no convention for distributing J2ObjC-enabled libraries that include both Java and separate Objective-C source (and build steps).

We already provide the tools for you to do this yourself, and many of my internal projects use it.  But I think at this point you are in power-user land, and it is acceptable that you have the user has to understand the Clang options themselves.  Providing abstractions over Clang is just complicating matters  - the gcc conventions have existed for years and we'd just be obfuscating them.
