### ISSUE TITLE
Translated Validation Api

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#456]
This is not really related to this project but what kind of validation api do you use in both Android and iOS projects?

Is there any java lib you translate? Something like hibernate-validation lib?

**Comment by advayDev1** [comment]
As you pointed out this is unrelated to this project.  Please try another resource (Google, Stackoverflow, etc.).

I'm also not certain what exactly you are asking about.

**Comment by confile** [comment]
The question is how do you do validation?

**Comment by advayDev1** [comment]
I don't use any validation api.  Whatever invariants I really care about enforcing are checked via preconditions and documented with comments.  I'd suggest asking this at https://forum.hibernate.org/

**Comment by confile** [comment]
@advayDev1 This has nothing to do with hibernate. The question is how do you check if the user input is valid? Which lib do you use?

**Comment by advayDev1** [comment]
I just write the code... 

Unless something super complicated is going on, I avoid adding dependencies on frameworks/libraries for what is (in my use case) pretty trivial logic.  Sometimes a few hundred lines of hand-written code is significantly easier to maintain in the long run than depending on libraries.   Java + Guava + Android/iOS SDK pretty much is all I need (minus some specialty graphics things).

**Comment by confile** [comment]
thanks
