### ISSUE TITLE
How to include pre translated implementations with j2objc-gradle?

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#457]
I have an interface 

```
interface MyInterface {
  void go();
}
```

For iOS I have an implementation in OCNI 

```
class MyIOSImpl {
   public void go() /*-[
     // do objective-c stuff
  ]-*/; 
}
```

For Android I have na android only implementation: 

```
class MyAndroidImpl {
   public void go()[
     // do java Android only stuff
  ] 
}
```

How do I get this in the j2objc-gradle eco system?

**Comment by advayDev1** [comment]
If you truly want 2 different class names for the Android and iOS versions (and also the requisite factory patterns, etc.), then just have 3 projects: the truly common code (with j2objc), the ios-specific code (with j2objc) and the android-specific code (an android project).

**Comment by advayDev1** [comment]
I don't think this depends on or needs plugin changes.  It is a orthogonal code design question.
