### ISSUE TITLE
Having Generated Sources in Xcode Project

### ISSUE THREAD

**Issue by MohammadHejazi** [j2objc-contrib/j2objc-gradle#459]
The attribute `source_files` is removed from the pod spec file in [this commit] (https://github.com/j2objc-contrib/j2objc-gradle/commit/3ba8cf5658702f8d12a1b81653e3c93d494cacb9). But I think it's useful sometimes (for debugging and doing on-the-fly fixes) to have the generated code inside Xcode project (instead of the static library).

Could you explain the reasoning behind removing it please?

And, it would be good if I have the decision to include the source code or the static library (via an option maybe).

**Comment by advayDev1** [comment]
The `source_files` attribute causes the files to be compiled again.  However, the output of j2objc is the compiled libraries themselves.  We do this to ensure that the library you run unit-tests against is identical to the library you link your iOS project to (to avoid any differences in a different Xcode build configuration vs. the clang command we run) and to allow multiple j2objc projects to be linked to each other directly from Gradle.

Providing the option to build in Pods in addition to Gradle is substantial work; I think we need to see some more user demand for it.

**Comment by brunobowden** [comment]
At the moment, we need to focus on correctness and ease of use. Over time,
we might support more but we're limited in our contributions. There is a
substantial complexity in trying to provide two different paths for builds,
the complexity of automated testing further makes it difficult to do this
well.

**Comment by advayDev1** [comment]
agreed @brunobowden , iceboxing for now.

**Comment by maxbritto** [comment]
FYI, I added only the .h files to the source_files so I could at least see the headers in XCode without triggering a new compilation on the XCode side :
```
  spec.source_files = 'j2objcOutputs/src/main/objc/**/*.h'
```
It works and I have the feeling that it has fixed the issues I had with code completion since I moved to the **use_frameworks!** flag in cocoapods. 
I can make a PR if you want me too
