### ISSUE TITLE
PodSpec should use vendored_libraries

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#460]
Compare:
https://guides.cocoapods.org/syntax/podspec.html#vendored_libraries
with what we use right now:
https://guides.cocoapods.org/syntax/podspec.html#libraries

Not sure if vendored_libraries should be used in addition to or instead of libraries, but our libraries do come with the pod, not with the system.

**Comment by brunobowden** [comment]
Likely this means two changes:

```
spec.ios.vendored_libraries = 'Libraries/z', 'Libraries/icucore'
spec.ios.vendored_frameworks = 'Frameworks/Security.framework'
```

At the moment, we're not linking in with Security.framework, not sure why it's not causing more issues.

**Comment by advayDev1** [comment]
Wait I don't think so.  Those are non-vendored libraries (in that they are system libraries).
I'm saying the j2objc library that gets built should be vendored instead of system.

**Comment by advayDev1** [comment]
also @brunobowden , I think no issues are being caused because Xcode doesn't actually build our pod - there are no source files, it just references the library built by gradle.

**Comment by brunobowden** [comment]
Those libraries are needed in the Link phase:
http://j2objc.org/docs/Xcode-Build-Rules.html

**Comment by advayDev1** [comment]
Yes but Security framework is (potentially) needed by your *app*'s project not the *pod*'s project.  I.e. the pod doesn't cause anything to build because Gradle already built it all, and did indeed reference Security framework: https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy#L310

Therefore, when your *app* is built, if you are already linking/using the Security Framework (or don't actually need it), nothing bad happens.

**Comment by brunobowden** [comment]
If that's the case, then is the spec.libraries line needed at all, except
for $libname?

spec.libraries = 'ObjC', 'guava', 'javax_inject', 'jre_emul', 'jsr305',
'z', 'icucore', '$libName'

Should become...

spec.libraries = '$libName'

**Comment by advayDev1** [comment]
No I think it should be similar to:
```ruby
# Libraries the final app needs to link against
# https://guides.cocoapods.org/syntax/podspec.html#libraries
spec.libraries = 'ObjC', 'guava', 'javax_inject', 'jre_emul', 'jsr305', 'z', 'icucore', '$libName'
# Frameworks the final app needs to link against
# https://guides.cocoapods.org/syntax/podspec.html#frameworks
spec.frameworks = 'Security'
# Libraries that are a part of the pod.
# https://guides.cocoapods.org/syntax/podspec.html#vendored_libraries
spec.vendored_libraries = 'lib${libName}.a'
```
I don't know the relationship between vendored_libraries and libraries though.  Libraries are the `-l` parameter, but vendored_libraries seem to be full file names.

Of course I cannot test my theories and the docs are pretty vague.

**Comment by advayDev1** [comment]
(My last 2 comments are consistent because for the earlier one you asked why it wasn't causing more issues.  But we should indeed make our spec correct.)

**Comment by advayDev1** [comment]
As a part of this change, you may want to make additional 'libraries' and 'frameworks' both params in j2objcConfig, and then support them in both NativeCompilation and XcodeTask.  Right now the user has no way of adding libraries to XcodeTask, and NativeCompilation does not understand that -l params for example are arguments (it just has a way of adding extra linker args for example).

**Comment by brunobowden** [comment]
When would they need other libraries? I thought this is only for adding the libraries needed for working with J2ObjC. For other libraries like GSON, you manage the dependencies separately.

**Comment by advayDev1** [comment]
Let's say I create code that relies on the OpenGL framework in my j2objc project.
How else would I specify that I need the OpenGLES.framework?

**Comment by advayDev1** [comment]
By the way, the current library dependencies created using DependencyResolver should also be added to the pod (that is #432)

**Comment by maxbritto** [comment]
I tried to apply this and it works well for me : 
```
  spec.vendored_libraries = 'j2objcOutputs/lib/iosDebug/librainbowapi-j2objc.a'
  spec.libraries = 'ObjC', 'guava', 'javax_inject', 'jre_emul', 'jsr305', 'z', 'icucore'
  spec.xcconfig = {
    'HEADER_SEARCH_PATHS' => '/j2objc/include',
    'LIBRARY_SEARCH_PATHS' => '/j2objc/lib'
  }
```
I removed the full path to the library in the LIBRARY_SEARCH_PATH and added it as relative in the **spec.vendored_library**
I removed the library form the **spec.libraries**
It works for me but I use the **use_frameworks!** in my project podfile so maybe someone with a project that don't use it could verify it works too.

Also, shouldn't the other libraries from j2objc be packed as vendored too ?

**Comment by advayDev1** [comment]
@maxbritto - if we want the j2objc libs to be vendored then we need to create a separate spec for those libraries alone (and then have your j2objc project spec depend on that spec).  consider the case where i have 2 j2objc projects my ios app depends on - if we did what you said, then each of those 2 projects would include the j2objc libraries and symbols

**Comment by maxbritto** [comment]
I see what you mean
