### ISSUE TITLE
Xcode 7 - build distinct simulator and OSX command line libraries

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#462]
With Xcode 7, the command line tests need to be built with the x86_64 architecture and MacOSX.platform. The existing iPhoneSimulator.platform and iPhoneOS.platform packed library can remain as is.

From @tomball:

*Both the Mac OS X and iPhone simulator use x86_64 archs, when the chosen simulated model is a 64-bit device (like iPhone 6). Prior to clang 7.0.0 (distributed with Xcode 7), an x86_64 arch could be used to link either a Mac command-line or a simulator build. So in our fat libraries we had the x86_64 build doing double duty.*

*With Xcode 7's clang, the SDK used to build the library is checked, and iPhone simulator builds are failing with 64-bit devices. We therefore need an x86_64 library built using a MacOSX.platform for command-line apps, and another x86_64 built with an iPhoneSimulator.platform. The lipo utility combines all the arch-specific libraries into a fat library, but it won't allow two builds with the same arch in the same fat binary.*

*Since j2objc's focus is on iOS while command-line apps are just for convenience (like running device-independent tests), it made the most sense to keep the iOS libraries together in the fat library, and split off the command-line ones.*

*Your plug-in can probably use the same trick j2objcc.sh does: check for an iOS -isysroot flag and if not found, append macosx to the library path:
No -isysroot flag: -L dist/lib/macosx
"MacOSX" in sys root path: : -L dist/lib/macosx
Otherwise, assume iOS: : -L dist/lib*

**Comment by advayDev1** [comment]
Fixed in #483
