### ISSUE TITLE
j2objc 0.9.8.2 and Xcode 7 not yet supported - "ld: library not found for -lj2objc_main"

### ISSUE THREAD

**Issue by andrewfunston** [j2objc-contrib/j2objc-gradle#466]
I've searched a bit and found nothing that seems similar. I've also checked my build environment vs the docs + FAQ and haven't found anything out of line. I'm new to j2objc and was trying to get a minimal build environment running. I followed the recommendations for build environment setup from the j2objc docs.

j2objc version was a pull/build from master from today (9/26/2015), but I tried with the release version ".9.8.2" with the same results.

Sorry for the image of my build.gradle, it kept failing when I had it converted to a .txt, etc. Very odd.

The error is as follows:

:java-core:x86_64DebugJava-core-j2objcStaticLibrary
:java-core:linkDebugTestJ2objcExecutable
ld: library not found for -lj2objc_main
clang: error: linker command failed with exit code 1 (use -v to see invocation)

:java-core:linkDebugTestJ2objcExecutable FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':java-core:linkDebugTestJ2objcExecutable'.
> A build operation failed.
      Linker failed while linking testJ2objc.
  See the complete log at: file:///Users/a/parati/java-core/build/tmp/linkDebugTestJ2objcExecutable/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

![screen shot 2015-09-26 at 10 27 56 pm](https://cloud.githubusercontent.com/assets/4275732/10121390/e2b7499c-649d-11e5-829e-8c368ed71945.png)

**Comment by advayDev1** [comment]
What are the full errors in:
file:///Users/a/parati/java-core/build/tmp/linkDebugTestJ2objcExecutable/output.txt ?

**Comment by andrewfunston** [comment]
I can't attach txt files so I'll have to plop them here, but it says essentially the same thing:

--------------------------------------------------------------------

See file:///Users/a/parati/java-core/build/tmp/linkDebugTestJ2objcExecutable/output.txt for all output for linkDebugTestJ2objcExecutable.
linking testJ2objc failed.
ld: library not found for -lj2objc_main
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Finished linkDebugTestJ2objcExecutable, see full log file:///Users/a/parati/java-core/build/tmp/linkDebugTestJ2objcExecutable/output.txt.

--------------------------------------------------------------------

Also in the directory is the "options.txt" that has this:

--------------------------------------------------------------------

 -o
/Users/a/parati/java-core/build/binaries/testJ2objcExecutable/debug/testJ2objc
/Users/a/parati/java-core/build/objs/testJ2objcExecutable/debug/testJ2objcObjc/551bb472kewcfrm35cmxbgh2t/EmptyTest.o
/Users/a/parati/java-core/build/objs/testJ2objcExecutable/debug/testJ2objcObjc/e8di3ks3a2jrkijz9l5wqcpvs/BaseTest.o
/Users/a/parati/java-core/build/binaries/java-core-j2objcStaticLibrary/x86_64Debug/libjava-core-j2objc.a
-ljunit
-lmockito
-ObjC
-lguava
-lj2objc_main
-ljavax_inject
-ljre_emul
-ljsr305
-L/Users/a/install/j2objc-master/dist/lib
-lc++
-licucore
-lz
-framework
foundation
-framework
Security
-framework
ExceptionHandling

--------------------------------------------------------------------

**Comment by advayDev1** [comment]
What is the output of
ls -al /Users/a/install/j2objc-master/dist/lib
?

**Comment by advayDev1** [comment]
@andrewfunston : please do answer the above, but I think I know the problem.

j2objc_main was moved into the Mac-only builds with 0.9.8.2 to support Xcode 7.  The plugin only supports j2objc 0.9.8.1 and Xcode 6 at the moment.  I've updated the title to reflect this.

**Comment by advayDev1** [comment]
This is going to be a non-trivial amount of work.  A lot of our tasks assume iOS and OSX use the same files.

Let's discuss on Wednesday @brunobowden

**Comment by advayDev1** [comment]
@andrewfunston - if you can use Xcode 6 / j2objc 0.9.8.1 you should try doing so; this will take a while to get working on Xcode 7 / j2objc 0.9.8.2.

**Comment by andrewfunston** [comment]
Sorry for the delay, as for the first request:

as-MacBook-Pro:~ a$ ls -al /Users/a/install/j2objc-master/dist/lib/
total 684872
drwxr-xr-x  21 a  staff        714 Sep 26 17:02 .
drwxr-xr-x   9 a  staff        306 Sep 26 17:02 ..
-rw-r--r--   1 a  staff   11108331 Sep 26 17:02 cycle_finder.jar
-rw-r--r--   1 a  staff      45024 Sep 26 16:33 hamcrest-core-1.3.jar
-rw-r--r--   1 a  staff   11084601 Sep 26 16:33 j2objc.jar
-rw-r--r--   1 a  staff       6540 Sep 26 16:28 j2objc_annotations.jar
-rw-r--r--   1 a  staff    1947757 Sep 26 16:54 j2objc_guava.jar
-rw-r--r--   1 a  staff     245039 Sep 26 16:33 j2objc_junit.jar
-rw-r--r--   1 a  staff       2497 Sep 26 16:33 javax.inject-1.jar
-rw-r--r--   1 a  staff    3186072 Sep 26 16:44 jre_emul-src.jar
-rw-r--r--   1 a  staff    2353625 Sep 26 16:33 jre_emul.jar
-rw-r--r--   1 a  staff      33031 Sep 26 16:33 jsr305-3.0.0.jar
-rw-r--r--   1 a  staff   93376320 Sep 26 16:54 libguava.a
-rw-r--r--   1 a  staff     341648 Sep 26 16:48 libjavax_inject.a
-rw-r--r--   1 a  staff  126732112 Sep 26 16:42 libjre_emul.a
-rw-r--r--   1 a  staff   65256752 Sep 26 16:42 libjre_emul_core.a
-rw-r--r--   1 a  staff    1986848 Sep 26 16:47 libjsr305.a
-rw-r--r--   1 a  staff   14253872 Sep 26 16:47 libjunit.a
-rw-r--r--   1 a  staff   17165496 Sep 26 17:00 libmockito.a
drwxr-xr-x  10 a  staff        340 Sep 26 17:01 macosx
-rw-r--r--   1 a  staff    1500011 Sep 26 16:33 mockito-core-1.9.5.jar

Right now I only have it generating the sources which works well enough for my exploratory purposes. (i.e. setting j2objc.translateOnlyMode=true). Thanks for your help.

**Comment by advayDev1** [comment]
Hello @andrewfunston  - I believe this is fixed.  Would you like to be a guinea pig for us? =)

Please ensure you have Xcode 7 and j2objc 0.9.8.2.1.  And please build the plugin directly from head (see https://github.com/j2objc-contrib/j2objc-gradle/blob/master/CONTRIBUTING.md sections "Local Development" and "Testing on your own Gradle project").  Let us know if you have any difficulties.

**Comment by advayDev1** [comment]
cc @kirkvogen

**Comment by advayDev1** [comment]
Verified against my own internal app that Xcode 7 support is now working for iOS device, iOS support, and OSX desktop apps.

**Comment by maxbritto** [comment]
Hi @advayDev1 , thanks for the work on XCode 7 version support!
Is there anythibng we should change in our configuration to be able to use it ?
With those changes all the gradle tasks now work but I can't build on XCode.
It ignores the library :
```
ld: warning: ignoring file /Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build/j2objcOutputs/lib/iosDebug/librainbowapi-j2objc.a, missing required architecture i386 in file /Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build/j2objcOutputs/lib/iosDebug/librainbowapi-j2objc.a (3 slices)
```
And as a result I have link errors for every j2objc class I use in the project.

**Comment by advayDev1** [comment]
maxbritto in your build.gradle's j2objcConfig section please add:
```
j2objcConfig {
supportedArchs += ['ios_i386']
}
```

I'm intrigued as to what OS versions you are building for that i386 is relevant (we thought it was just for 32-bit simulators so removed it from the default set).  This is unrelated to Xcode 7 though.

**Comment by maxbritto** [comment]
It was for the iPhone 5 simulator. I did some more tests and without adding the modifications to the gradle file I can build for a real iPhone or for the simulators starting at iPhone 5S. The iPhone 4S and iPhone 5 simulator have the link error.

**Comment by advayDev1** [comment]
To be clear:
- without the supportedArchs change it works on real iphones and iphone 5s and beyond
- with the supportedArchs change it works also on the simulator for 4s and the simulator for 5
did i read that right?

So @maxbritto everything is working for you overall?

**Comment by maxbritto** [comment]
That is exactly that and yes, everything is working for me know, thanks for your help :)

**Comment by advayDev1** [comment]
np - @maxbritto thanks for being a guinea pig.

**Comment by kirkvogen** [comment]
I built it and tried out the new version locally. I can build my project with the new plugin version, but in Xcode I get linker errors saying that it cannot find my classes that were translated from Java. Also, if I add the -mios-version-min=8.0 as extraObjcCompilerArgs, I get additional build errors (error: 'CSSM_SAMPLE' is unavailable: not available on iOS).

**Comment by andrewfunston** [comment]
Apologies: I'm afk until Wednesday, I'll run through it when I get back
into the office then. Thanks for the update, that was fast!

**Comment by advayDev1** [comment]
@kirkvogen, can you please paste the exact Xcode errors you get?

Does your linker log have anything like:
```
ld: warning: ignoring file /Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build/j2objcOutputs/lib/iosDebug/librainbowapi-j2objc.a, 
missing required architecture i386 in file /Users/mbritto/Documents/Dev2A/Rainbow/branches/mobile/android-ios-cocoapods/rainbowapi/build/j2objcOutputs/lib/iosDebug/librainbowapi-j2objc.a 
(3 slices)
```
If so add to the top of your build.gradle's j2objcConfig section: `supportedArchs += ['ios_i386']`

Also Instead of using -mios-version-min=8.0; you can now add to the top of your j2objcConfig: `minIosVersion = '8.0'`

**Comment by kirkvogen** [comment]
@advayDev1 Hey, success! I did need to add the `supportedArchs` bit to resolve the linker errors. And, the `minIosVersion` setting resolved the linker warnings. Thanks!

**Comment by kirkvogen** [comment]
@advayDev1 Also, I can now run the `build` task and run J2ObjC-translated unit tests. Previously, I was getting build errors with the earlier version of the plugin when I tried running the test. It works now!

**Comment by advayDev1** [comment]
Thanks @kirkvogen !  Good to know everything's working for you.  If any of you on this thread who have the basics working and need to try some of the more advanced stuff (multiple projects, custom external libraries, etc.), check out #490 and please provide any feedback directly on that PR regarding things that are unclear.

@brunobowden - any luck getting your project working again with Xcode 7?

**Comment by brunobowden** [comment]
It's working like a charm for me on Xcode 7. I've got it working for the
follwoing:

   - j2objc unit tests
   - iPhone 6 Plus (64 bit)
   - iPhone 6 Plus Simulator (x86_64)
   - iPhone 5 simulator (i386 through fix from the FAQ).

I was expecting the simulators to fail since it wasn't linking to the osx
library versions. What else needs to be fixed at this point?

**Comment by advayDev1** [comment]
No the simulators need the appropriate architecture on iOS sysroot, not the OSX sysroot.  I think the commit got that right.  The only thing left for Xcode 7 is your bug #488  - which is for OSX based unit tests and apps, not for simulators

**Comment by kirkvogen** [comment]
I have experienced a couple of issues that it get in the way a bit. Sometimes Xcode crashes while the Gradle plugin is running. Also, build time is a bit of an issue. If I don't change any Java files, the build is a second or two. If I change a Java file, it often stays at the `j2objcAssemble` showing 98% for two to three minutes. I've tried setting `J2OBJC_RELEASE_ENABLED=false`, but it doesn't seem to help much. I typically run the `j2objcXcode` task instead of `build` (because I've got some translated test failures I need to fix).

**Comment by kirkvogen** [comment]
I think my performance issue might be due to a source JAR that I'm translating and building (hamcrest). I shouldn't need to translate and build it anyway, since the J2ObjC comes with hamcrest pre-built, right?

**Comment by kirkvogen** [comment]
I corrected (I think) so that the project uses the built-in JUnit and Hamcrest. The performance issue appears to have gone away. I can make a Java source change, and a rebuild, including tests, takes about five seconds.

I added the following into `j2objcConfig` to include the built-in libraries. Is that the proper way to do it? I hope that doesn't result in my implementation (non-test) code being linked with those libraries.

`translateJ2objcLibs = ["j2objc_junit.jar", "hamcrest-core-1.3.jar"]`

**Comment by advayDev1** [comment]
Yeah you did everything right.  @kirkvogen , I've filed #492; we might as well add the new 0.9.8.2.1 libraries since we've made that a minimum requirement now.

**Comment by andrewfunston** [comment]
It works for me! I had to revert back (arbitrarily, I just chose the last commit on Oct - 4th) to b7f4aad to get it functioning, the current head fails unable to link to the protobuf_runtime, but I assume that's part of a WIP. 

Let me know if I need to run through anything else.

**Comment by advayDev1** [comment]
@andrewfunston - could you expand at #498?  Protobuf runtime is neither known to work nor known not to work, as neither Bruno or I use them at the moment.
