### ISSUE TITLE
Guava local build support for j2objc-0.9.8.2

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#472]
The 0.9.8.2 release of J2ObjC has removed the Guava jar and compiled library. This is something that the plugin needs to support end to end without special configuration. @advayDev1 - I know you've added a lot to support this, but we still need to verify everything.

@kstanger, @tomball - I know you mentioned that this was going away. We're not quite ready to handle it yet but will be soon.

**Comment by tomball** [comment]
It was dropped because of a build failure. I'm building a 0.9.8.2.1 that
corrects this, which should be posted in an hour or so.

**Comment by advayDev1** [comment]
btw: Until Guava 19 is officially released comes out, we are not yet ready to support Guava out of the box.

**Comment by advayDev1** [comment]
Closing this as Tom's already fixed j2objc.  We do in fact need to support the Guava 19 build, but that's already filed as a bug.
