### ISSUE TITLE
 object file was built for newer iOS version (8.3) than being linked (8.0).

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#482]
We arbitrarily chose 8.3 as the OS version for our native compilation step.  This should be configurable via j2objcConfig.

cc @kirkvogen

**Comment by ph1lb4** [comment]
how do you actually specify the minimum version in the build.gradle file?
Simply writing `minIosVersion = '8.0'` in the j2objcConfig method does not work

**Comment by brunobowden** [comment]
`minIosVersion` exists in the code but isn't a setting for j2objcConfig. I think you meant this instead:

    j2objcConfig {
        minVersionIos '8.0'
    }

You can see the name of the setting and the default value of "6.0" here:

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy#L636

**Comment by ph1lb4** [comment]
Thanks, that was the confusion!
