### ISSUE TITLE
XcodeTask must distinguish ios vs osx for Xcode 7

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#488]
@brunobowden - can the pod config specify:
- different j2objc library directories for ios vs. osx (j2objcDist/lib and j2objcDist/lib/macosx respectively)
- different project library directories for ios vs. osx (project/build/j2objcOutputs/lib/ios{Debug|Release} vs project/build/j2objcOutputs/lib/x86_64{Debug|Release})
- one additional framework for osx (ExceptionHandling)?

**Comment by brunobowden** [comment]
I believe this is how it could be done.

    spec.ios.xcconfig = { 'LIBRARY_SEARCH_PATHS' => '/J2OBJC_HOME/lib' }
    spec.osx.xcconfig = { 'LIBRARY_SEARCH_PATHS' => '/J2OBJC_HOME/lib/macosx' }

I'll experiment to make sure this works.

Podspec Documentation:
https://guides.cocoapods.org/syntax/podspec.html#group_multi_platform_support
