### ISSUE TITLE
Unable to link to protobuf runtime due to stale Gradle cache

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#498]
@andrewfunston - could you expound on your issue with protobufs?  I'm using only flatbuffers and they are working fine for me.

Could you provide error messages, which SHA you built the plugin at, etc.?

Thanks!

**Comment by advayDev1** [comment]
Any part of your build.gradle that you are willing to share publicly is also useful.

**Comment by advayDev1** [comment]
Also we are very close to releasing 0.5.0 which will hopefully be a beta, so getting protobuffers working would be nice.

**Comment by andrewfunston** [comment]
I'm not using protobufs in my project currently: it's during the build process using j2objc v0.9.8.2.1 and a locally build gradle plugin checked out to commit b3ed3f7. 

------------------------------------------------------------------------------------------------------------------------

java-core:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
:java-core:processTestResources UP-TO-DATE
:java-core:testClasses
:java-core:test
:java-core:j2objcPreBuild
:java-core:j2objcTranslate
:java-core:compileDebugTestJ2objcExecutableTestJ2objcObjc
:java-core:compileX86_64DebugJava-core-j2objcStaticLibraryJava-core-j2objcObjc
:java-core:createX86_64DebugJava-core-j2objcStaticLibrary
:java-core:x86_64DebugJava-core-j2objcStaticLibrary
:java-core:linkDebugTestJ2objcExecutable
ld: library not found for -lprotobuf_runtime
clang: error: linker command failed with exit code 1 (use -v to see invocation)

:java-core:linkDebugTestJ2objcExecutable FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':java-core:linkDebugTestJ2objcExecutable'.
> A build operation failed.
      Linker failed while linking testJ2objc.
  See the complete log at: file:///Users/a/parati/java-core/build/tmp/linkDebugTestJ2objcExecutable/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 1.629 secs

------------------------------------------------------------------------------------------------------------------------

The output.txt once again re-iterates the error message given while building. My build gradle looks like this (I'm having trouble uploading files):

------------------------------------------------------------------------------------------------------------------------

buildscript {
    dependencies {
        classpath files('/Users/a/workspace/j2objc-gradle/build/libs/j2objc-gradle-0.4.4-alpha-SNAPSHOT.jar')
    }
}

apply plugin: 'java'
apply plugin: 'com.github.j2objccontrib.j2objcgradle'
apply plugin: 'net.ltgt.apt'

sourceCompatibility = 1.7
targetCompatibility = 1.7

// Plugin settings:
j2objcConfig {
    translateArgs '--build-closure'

    translateSourcepaths '../libs/gson-2.3.1-sources.jar'
    translateSourcepaths '../libs/dagger-2.0.1-sources.jar'
    translateSourcepaths 'build/generated/source/apt/main/'
    translateSourcepaths 'build/generated/source/apt/test/'

    xcodeProjectDir '../ios-app'  // Xcode workspace directory (suggested directory name)

    finalConfigure()          // Must be last call to configuration
}

j2objcTest {
    enabled = false
}

version = '1.0'

jar {
    manifest {
        attributes 'Implementation-Title': 'Java-core',
                'Implementation-Version': version
    }
}

repositories {
    mavenCentral()

    flatDir {
        dirs '../libs'
    }
}

dependencies {
    apt name: 'guava-18.0'
    apt name: 'javax.inject-1'
    apt name: 'dagger-2.0.1'
    apt name: 'dagger-compiler-2.0.1'
    apt name: 'dagger-producers-2.0-beta'

    compile name: 'json'
    compile name: 'gson-2.3.1'
    compile name: 'hamcrest-core-1.3'
    compile name: 'guava-18.0'
    compile name: 'dagger-2.0.1'
    compile name: 'javax.inject-1'
    compile name: 'junit-4.12'

    testCompile name: 'junit-4.12'

    testApt name: 'guava-18.0'
    testApt name: 'javax.inject-1'
    testApt name: 'dagger-2.0.1'
    testApt name: 'dagger-compiler-2.0.1'
    testApt name: 'dagger-producers-2.0-beta'
}

test {

}

uploadArchives {
    repositories {
        flatDir {
            dirs 'repos'
        }
    }
}

**Comment by advayDev1** [comment]
@andrewfunston - can you confirm you are using j2objc 0.9.8.2.1, and also provide the result of:
```
ls -al /PATH_TO_J2OBJC_DISTRIBUTION/lib
ls -al /PATH_TO_J2OBJC_DISTRIBUTION/lib/macosx
```

**Comment by advayDev1** [comment]
@andrewfunston - also I sent you a Google Hangouts invite; would love to be able to chat with you in realtime and get the issue resolved if you have a few minutes.

**Comment by andrewfunston** [comment]
as-MacBook-Pro:parati a$ ls -al ~/install/j2objc/lib/
    total 692456
    drwxr-xr-x@ 23 a  staff        782 Sep 29 13:05 .
    drwxr-xr-x@ 11 a  staff        374 Sep 29 12:58 ..
    -rw-r--r--@  1 a  staff   11115069 Sep 29 12:58 cycle_finder.jar
    -rw-r--r--@  1 a  staff      45024 Sep 29 12:58 hamcrest-core-1.3.jar
    -rw-r--r--@  1 a  staff   11091339 Sep 29 12:58 j2objc.jar
    -rw-r--r--@  1 a  staff       6543 Sep 29 12:58 j2objc_annotations.jar
    -rw-r--r--@  1 a  staff    1947598 Sep 29 13:01 j2objc_guava.jar
    -rw-r--r--@  1 a  staff     245039 Sep 29 12:58 j2objc_junit.jar
    -rw-r--r--@  1 a  staff       2497 Sep 29 12:58 javax.inject-1.jar
    -rw-r--r--@  1 a  staff    3186075 Sep 29 12:58 jre_emul-src.jar
    -rw-r--r--@  1 a  staff    2353571 Sep 29 12:58 jre_emul.jar
    -rw-r--r--@  1 a  staff      33031 Sep 29 12:58 jsr305-3.0.0.jar
    -rw-r--r--@  1 a  staff   93376320 Sep 29 13:05 libguava.a
    -rw-r--r--@  1 a  staff     341648 Sep 29 13:01 libjavax_inject.a
    -rw-r--r--@  1 a  staff  126732088 Sep 29 13:01 libjre_emul.a
    -rw-r--r--@  1 a  staff   65256728 Sep 29 13:00 libjre_emul_core.a
    -rw-r--r--@  1 a  staff    1986848 Sep 29 13:01 libjsr305.a
    -rw-r--r--@  1 a  staff   14253872 Sep 29 13:02 libjunit.a
    -rw-r--r--@  1 a  staff   17165496 Sep 29 13:04 libmockito.a
    -rw-r--r--@  1 a  staff    3321176 Sep 29 13:01 libprotobuf_runtime.a
    drwxr-xr-x@ 11 a  staff        374 Sep 29 13:05 macosx
    -rw-r--r--@  1 a  staff    1500011 Sep 29 12:58 mockito-core-1.9.5.jar
    -rw-r--r--@  1 a  staff     545959 Sep 29 13:01 protobuf_runtime.jar

--------------------------------------------------------------------------------------------------------------------------------
    as-MacBook-Pro:parati a$ ls -al ~/install/j2objc/lib/macosx/
    total 126416
    drwxr-xr-x@ 11 a  staff       374 Sep 29 13:05 .
    drwxr-xr-x@ 23 a  staff       782 Sep 29 13:05 ..
    -rw-r--r--@  1 a  staff  18683688 Sep 29 13:05 libguava.a
    -rw-r--r--@  1 a  staff      6448 Sep 29 13:00 libj2objc_main.a
    -rw-r--r--@  1 a  staff     67784 Sep 29 13:01 libjavax_inject.a
    -rw-r--r--@  1 a  staff  25467904 Sep 29 13:00 libjre_emul.a
    -rw-r--r--@  1 a  staff  13103688 Sep 29 13:00 libjre_emul_core.a
    -rw-r--r--@  1 a  staff    393312 Sep 29 13:01 libjsr305.a
    -rw-r--r--@  1 a  staff   2876840 Sep 29 13:02 libjunit.a
    -rw-r--r--@  1 a  staff   3441752 Sep 29 13:04 libmockito.a
    -rw-r--r--@  1 a  staff    661752 Sep 29 13:01 libprotobuf_runtime.a
--------------------------------------------------------------------------------------------------------------------------------

**Comment by andrewfunston** [comment]
All is functioning now. This was my own fault; I left a reference pointing to the wrong j2objc distribution in my local.properties (in addition to my J2OBJC_HOME). Sorry for the false alarm!

**Comment by advayDev1** [comment]
Cool thanks!
