### ISSUE TITLE
Split j2objcPodspec task from j2objcXcode task

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#502]
@advayDev1 - I'm working through some design decisions that I'd like to run by you. There's a tricky issue when running the j2objcXcode task:

1) It needs to first create the podspecs on a per project basis and update the single Podfile multiple times (pointing to each spec). This doesn't have any dependencies except the project's j2objcAssemble task.

2) Once this is done. Then a single "pod install" must be done.

In my experimental code, by chaining the j2objcXcode dependencies, it will attempt to install the "pod install" multiple times. This is both inefficient and sometimes fails due to a missing podspec's that haven't been created yet.

After separating out these two tasks, I believe the top level j2objcPodspec task should depend on the j2objcPodspec task of all dependent projects. The j2objcXcode project depends on the j2objcPodspec... and should only be called once.

It's important that all the dependent project update the same Podfile. Either that can be done by enforcing that xcodeProjectDir is the same for all the dependent projects... or perhaps better yet, have the top project, configure the xcodeProjectDir of all the dependent projects. That'll allow xcodeProjectDir to be set in only one place. The same logic would apply to xcodeTargets as well.

**Comment by brunobowden** [comment]
I think this'll need to be slightly more complex again. Isolate the j2objcPodspec task to only creating the podspec and not updating the Podfile. When it resolves the j2objcPodspec dependencies, it should dependsOn the dependent projects (as described before).

When it comes to updating the Podfile and doing the "pod install". The j2objcXcode task can then walk all the dependencies of the same project's j2objcPodspec task. Then update and install the Podfile in a single pass.

@advayDev1 - your thoughts?

**Comment by advayDev1** [comment]
@brunobowden - I think this is quite reasonable, with one worry: how do you know which is the root project?  what if no (or equivalently, multiple) projects would be considered roots.

i have the following dependency tree for example:
myIosApp -> (ios-factories-j2objc; app-logic-j2objc) -> (various common j2objc libraries)

Which project, ios-factories, or app-logic, would be responsible for pod install?

**Comment by advayDev1** [comment]
@brunobowden - in my case, (without pods), i solve this by representing myIosApp itself as a Gradle project via https://github.com/madvay/mixc-build.  it then depends on all the other j2objc projects, and then i do in fact have a single "root" Gradle project per Xcode project; it is the only one that touches my xcproj files (which is my analog to the 'pod install')
