### ISSUE TITLE
e2e test for sqlighter

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#509]
@andrewfunston is going to be working on this. It should be based in the systemTests directory. Perhaps label it "sqlighter". Then people can use it as a working example that they build upon.

cc @vals-productions so you're aware of this

**Comment by advayDev1** [comment]
@brunobowden - why not put these in https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test

Having them in systemTests will make our plugin build take forever.

**Comment by advayDev1** [comment]
closed in favor of https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/53
