### ISSUE TITLE
Multiple java project translation and compilation

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#51]
I have two projects, say 2 java gradle projects libx and appx.  They live under one root gradle project, and therefore appx has a 'compile' dependency on libx.  Both libx and appx need to be converted to objc.

Ideally, libx's output directory for j2objcCopy would become an additional include directory for appx's j2objcCompile.  In addition, .a files from compiling libx, would be available for linking into appx's j2objcTest phase.  libx's jar file would be on the classpath for appx's translation.  All the tasks should have inter-project dependencies set correctly (I'm guessing I'm going to need to add a new flavor of dependency like 'j2objc').

This should be all done automatically, without --build-closure (a crutch that is getting less useful as my project graph gets more complicated), and in a hermetic environment (no copying files to j2objc's main /include and /lib directories).   Why doesn't this work out of the box and what needs fixing?
- no way to add additional include directories for j2objcCompile
- j2objc* tasks between projects do not have dependency edges (i.e. appx:j2objc* depends only on libx:compile not on libx:j2objcTranslate)
- no way to specify classpath libraries that are not either in $J2OBJC_HOME/lib or in $PROJECT/lib.  (gradle doesn't use $PROJECT/lib to save away a peer, dependent project's jar output)
- j2objc compile tasks don't create/save away .a objects anywhere permanently
- no way to specify objc .a objects to link that are not in $J2OBJC_HOME/lib
- input directories for appx's j2objc tasks need to be set so as to include the output directories of libx's j2objc tasks.  (this ensures gradle runs the right tasks on file update).

Thoughts?  I'm working on figuring this out on my own in my private codebase, if I succeed I'll try to issue a pull request as long as things haven't diverged too far by then.

**Comment by advayDev1** [comment]
(I'm aware the shortcut way of doing this is a single j2objc project that just accumulates the src/main/java directories of all possible source directories of all possible projects, but that prevents me from building/updating my many independent libraries separately).

**Comment by confile** [comment]
I have a similar setup. Just include lib in your main project and translate the main project. This issue is not related to this plugin.

**Comment by advayDev1** [comment]
Can you expound on 'include lib in your main project'?   You mean combine the sources of two different projects?

**Comment by confile** [comment]
I included the lib source in the main project.

**Comment by advayDev1** [comment]
Yeah I don't want to do that, and I shouldn't have to.  It should be possible to build 2 separate java source projects with gradle dependencies between them, and properly setup the j2objc tasks for that.  (in my case my codebase has many separate java libraries each of which can and should be independent objc libraries).

**Comment by confile** [comment]
Which type of MVP framework do you use?

**Comment by advayDev1** [comment]
None.  I'm not sure how that's relevant?

I have lots and lots of separate gradle subprojects, each of them used by different subsystems, and different parts of the organization.

**Comment by confile** [comment]
It is not! just for interest.

**Comment by advayDev1** [comment]
Sorry =)  I get overly adamant about preventing a bug thread from digressing.

**Comment by brunobowden** [comment]
This is still a productive conversation. I'm learning from both of you.

**Comment by advayDev1** [comment]
Almost have this done.  For me, this is the last major missing feature.
