### ISSUE TITLE
e2e test for dagger2

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#510]
@andrewfunston is going to be working on this. It should be based in the systemTests directory. Perhaps label it "dagger2".

**Comment by advayDev1** [comment]
@brunobowden - why not put these in https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test

Having them in systemTests will make our plugin build take forever.

**Comment by brunobowden** [comment]
@advayDev1 - fair point. @andrewfunston - can you close this bug and #509, moving them both to the e2e repo: https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/

**Comment by andrewfunston** [comment]
@brunobowden it won't let me close these two, but I have opened two new issues mirroring the two issues here:

https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/53

https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/52
