### ISSUE TITLE
Verify j2objc version; and provide out-of-box experience.

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#514]
If you specify a j2objc_home AND (`j2objc -version` returns `j2objc $j2objcVersion`), pass.
Otherwise, fast fail, and provide an exact command you can copy and paste, for example:
```
No matching version of j2objc could be found.  You can initiate a default installation of j2objc
by running the following from a Terminal:

  mkdir -p ~/j2objcDist && pushd ~/j2objcDist
  curl -L https://github.com/google/j2objc/releases/download/${j2objcVersion}/j2objc-${j2objcVersion}.zip > j2objc-${j2objcVersion}.zip
  unzip j2objc-${j2objcVersion}.zip
  echo j2objc.home=~/j2objcDist/j2objc-${j2objcVersion} >> ${rootProject.projectDir.absolutePath}/local.properties

Then rerun your Gradle build.

For advanced configuration of j2objc, please see http://j2objc.org/
```

Default j2objcConfig.j2objcVersion to 0.9.8.2.1.

**Comment by advayDev1** [comment]
@brunobowden - thoughts?  I think this is super easy for a developer to do.  First time they run ./gradlew build, they get instructions on what to do.

**Comment by brunobowden** [comment]
Sounds like a good intermediate step.

1. Prefix the instructions with J2OBJC_PATH=~/j2objcDist, so that someone can easily customize the directory before running the command.
2. Instead of appending j2objc.home, what about replacing an existing line in the file? That could be done with a simple perl script:

    perl -pi -e 's/^j2objc.home.*$/j2objc.home=~\/j2objcDist\/j2objc-${j2objcVersion}/' ${rootProject.projectDir.absolutePath}/local.properties

Though on second thoughts, can we assume that j2objc.home already exists?

**Comment by advayDev1** [comment]
the PR i've coded up shows these instructions in many cases:
- no j2objc home defined
- j2objc home directory doesn't exist
- j2objc binary does not exist
- j2objc binary fails on -version
- j2objc version mismatch

different preambles are given in each case.

I will do the J2OBJC_PATH change.
The sed + echo script I have works even if j2objc.home is not defined, so I think I'll stick with that.

**Comment by advayDev1** [comment]
As a followup, running that script on the behalf of the user could be something you could put in a task.  BUT I just don't think we should run a 100+MB download and start spewing files all over the disk in the case where one of those instructions fail for a simple reason like a typo.  Would be nice if Gradle task could prompt the user 'Would you like to start a default install of j2objc?' but I don't think we can

**Comment by brunobowden** [comment]
A build shouldn't have a prompt in it for user input. I think best thing is
to fail gracefully with instructions. So this seems like a workable
compromise.

**Comment by advayDev1** [comment]
So how would you distinguish between a simple forgotten configuration or typo vs. the user really wants to download a huge file?

**Comment by advayDev1** [comment]
We could also provide a single step in the future like `Please run :project:j2objcDownloadAndInstall` which executes those tasks.  Keeps it simple, but still makes sure the user really wanted to install j2objc and there wasn't a misconfig.

**Comment by brunobowden** [comment]
I think that's reasonable. We'll also see the user feedback on what that's
like.
