### ISSUE TITLE
Support for annotation processors' generated code (ex. dagger2)

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#517]
There are many assorted bugs regarding individual error messages when using annotation processors - but they haven't gone anywhere though.
This bug is instead for end-to-end support of dagger2, as opposed of hacking it into the plugin through various individual j2objc config properties.

While there may be many annotation processors and mechanisms for their integration into Gradle, success here will be measured by the ability to successfully use one of the most common: Dagger2 (https://github.com/google/dagger).

@andrewfunston - If you are willing, please document the process you are using to get dagger2 working right now.  I think it would be helpful to consider contributing a generalized version of that as a PR to the plugin itself instead of just the example project (see [here](https://github.com/j2objc-contrib/j2objc-gradle/blob/94e74ff3aee38435f0aaa80a864be2c28e5631de/CONTRIBUTING.md#conditions-for-accepting-pull-requests)).

**Comment by advayDev1** [comment]
Update per call with @andrewfunston - don't worry about doing a PR.

What Bruno and I need is:
- where, by default (with no additional plugins), Dagger puts the generated code using Gradle
- name of the Gradle task that does it (is it just `compileJava` or `classes` or something?)
- 2 editions of an example build.gradle before and after adding j2objc plugin, for a project which uses Dagger2
- your willingness to be a guinea pig when we update the plugin with what we *think* is a working support :)

Thank you!

**Comment by brunobowden** [comment]
@andrewfunston - we'd appreciate your insights on this

**Comment by andrewfunston** [comment]
Sorry for the delay, I started assembling this  information together
yesterday, I'll have the other parts together today!

**Comment by andrewfunston** [comment]
1) By default (using a [build.gradle](https://github.com/andrewfunston/j2objc-common-libs-e2e-test/blob/feature/dagger2-sample/sampleProjects/dagger2-noj2obc/shared/build.gradle#L10) that looks like this) the dagger files are placed like [this](https://gist.github.com/andrewfunston/cf097f237c5187fd6ddb). Note, it also adds the .java file. 

2) [Annotation Processing](http://hannesdorfmann.com/annotation-processing/annotationprocessing101/) It appears that any jar with a particular set of contents is treated as an annotation process and run during the compilation process. (From the link ->) "Furthermore you also have to pack a special file called javax.annotation.processing.Processor located in META-INF/services in your .jar file." 

I'm new to the internals of annotation processing, so I might be misrepresenting some of these details, but a [dump of the --debug](https://gist.github.com/andrewfunston/d30c587ca03484b6c190) info from the gradle process seems to indicate no special steps in java compilation.

3) [Build.gradle without j2objc](https://github.com/andrewfunston/j2objc-common-libs-e2e-test/blob/feature/dagger2-sample/sampleProjects/dagger2-noj2obc/shared/build.gradle#L15) Adding j2objc to the process doesn't change any steps, but if you attempt to use the generate files in the source code j2objc [fails to locate them](https://gist.github.com/andrewfunston/b01b1f4f24d7d7d15c81). 

I've commited a [simple dagger2 project](https://github.com/andrewfunston/j2objc-common-libs-e2e-test/tree/feature/dagger2-sample/sampleProjects/dagger2-noj2obc) with no j2objc included, it generates and uses a [generated class file](https://github.com/andrewfunston/j2objc-common-libs-e2e-test/blob/feature/dagger2-sample/sampleProjects/dagger2-noj2obc/shared/src/main/java/com/github/j2objccontrib/Test.java#L6). [The other project](https://github.com/andrewfunston/j2objc-common-libs-e2e-test/tree/feature/dagger2-sample/sampleProjects/dagger2-nocompile) will complete the java compilation and fail on the j2objc generation

I am trying to work on both a sample project for seeding and getting the e2e tests in, but it's a bit slow going. This should get you running though and I can easily test what you produce!

**Comment by advayDev1** [comment]
@andrewfunston - Thanks!

However, the failure in the log you linked to is unrelated to j2objc:
```
/Users/a/workspace/j2objc-common-libs-e2e-test/sampleProjects/dagger2-nocompile/shared/build/classes/main/com/github/j2objccontrib/DaggerSharedDaggerComponent.java:13: error: duplicate class: com.github.j2objccontrib.DaggerSharedDaggerComponent
public final class DaggerSharedDaggerComponent implements SharedDaggerComponent {
             ^
5 errors
:shared:compileJava FAILED
```
that's javac.

**Comment by andrewfunston** [comment]
Sorry, wrong gist. 

https://gist.github.com/andrewfunston/dc355b4086afb0a76fef

I accidently left in the plugin that makes a separate source set.

**Comment by advayDev1** [comment]
Cool.  So try out this patch:
https://github.com/j2objc-contrib/j2objc-gradle/commit/661f1e67d3e1d793f92d7c4671603ce0b129743e.patch

You can just make that one-line change locally, and then build the plugin, and see how it does.
If it works, please put the full build.gradles somewhere.  I need to see if you are using autoConfigureDeps, build-closure, etc.

**Comment by andrewfunston** [comment]
https://gist.github.com/andrewfunston/11e26dcd0471024560e2

Seems like now it's upset about the inner classes.

**Comment by andrewfunston** [comment]
as-MacBook-Pro:shared a$ find . -name "*Shared*"
./build/classes/main/com/github/j2objccontrib/DaggerSharedDaggerComponent$1.class
./build/classes/main/com/github/j2objccontrib/DaggerSharedDaggerComponent$Builder.class
./build/classes/main/com/github/j2objccontrib/DaggerSharedDaggerComponent.class
./build/classes/main/com/github/j2objccontrib/DaggerSharedDaggerComponent.java
./build/classes/main/com/github/j2objccontrib/SharedDaggerComponent.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideExecutorFactory.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideExecutorFactory.java
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideGsonFactory.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideGsonFactory.java
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvidesSimpleRestFactory.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvidesSimpleRestFactory.java
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideUrlProviderFactory.class
./build/classes/main/com/github/j2objccontrib/SharedDaggerModule_ProvideUrlProviderFactory.java

is the full list of generated classes

**Comment by advayDev1** [comment]
Ah no it is finding those classes, it just isn't understanding the package name correctly due to build/classes/main not being on the sourcepath as well.

Alright, here's another try.  Please revert the last one-line patch, and apply this larger one: 
https://github.com/madvay/j2objc-gradle/commit/08ae497c12263ce1795b2d31e757419d2464f9e2

note you can download a real .patch from:
`https://github.com/madvay/j2objc-gradle/commit/08ae497c12263ce1795b2d31e757419d2464f9e2.patch`

The gist of the failure is really helpful - it shows the full command line which is how I identified the sourcepath dirs as the problem.

**Comment by andrewfunston** [comment]
Success! I have a meeting before I can validate the build and unit tests as well, but it everything completed.

https://gist.github.com/andrewfunston/ab1eb65685c3b2d3d89a

**Comment by advayDev1** [comment]
Before we declare success:
1.  Please do a `./gradlew clean` and then rebuild to make sure we aren't succeeding due to running twice.
2.  Are you testing on this project?  https://github.com/andrewfunston/j2objc-common-libs-e2e-test/blob/feature/dagger2-sample/sampleProjects/dagger2-nocompile/shared/build.gradle  If so, please remove the line `compile 'com.google.dagger:dagger:2.0.1'` - if everything is working, that should be coming from the line `compile project(':daggerThirdParty')` (note, keep the compiler around).

**Comment by andrewfunston** [comment]
1) I run ./gradlew --stop, ./gradlew clean, ./gradlew assemb each run. I just re-ran it twice, same happy output. Also ran it several times in a row with small file modifications, so far as I can tell for now it's looking good.

2) I reran as mentioned with the additional compile statement removed (checked in the changes as well), sorry I was bouncing between so many projects that I was having trouble keeping everything perfectly straight.

**Comment by advayDev1** [comment]
Wonderful, we'll go ahead and check this in then and if we need further fixes make them as needed.

**Comment by andrewfunston** [comment]
I will attempt to migrate my larger project back to the correct path and report back. Thanks for the help!

**Comment by advayDev1** [comment]
thanks for the investigation and all the back and forth - very useful
