### ISSUE TITLE
Use idiomatic sourceSets for all listings of source files

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#52]
The idiomatic way in Gradle to specify what sources a project is using is to use source sets.  Usually 'main' for production code and 'test' for test code.

Currently, source files are found by aggregating globs of .java files, ex:
```
srcFiles = files(
                        fileTree(dir: projectDir,
                                include: "**/*.java",
                                exclude: project.relativePath(buildDir)) +
                        fileTree(dir: "build/source/apt",
                                include: "**/*.java")
                        )
```

Instead we should always be using the sourceSets in the project.  Currently, we will erroneously find files that are not part of the project build but just happen to be in the directory, miss files the user has added to the source set (specifically generated source directories, which have to be added manually but should not have to be), and causes special casing like the above for apt (this should also allow us to fix #45.).

In addition for test sources:
```
 // Doesn't use 'buildDir' as missing full path with --no-package-directories flag
                srcFiles = files(fileTree(dir: projectDir, includes: ["**/*Test.java"]))
```

we should be using the 'test' source set.

**Comment by confile** [comment]
Please make a pull request if you have any improvements!

**Comment by advayDev1** [comment]
Yep, I'm working on it (generally all the bugs I file I have in progress solutions for, but github prevents me from assigning the bug to myself like most workflows I'm used to).

My own gradle plugins use project afterEvaluation stage to configure the tasks' input directories to be equal to the projects' source sets.  Do y'all have a preference on when to configure the tasks?  It means some non-trivial changes to how the tasks and plugin get setup.

**Comment by confile** [comment]
@advayDev1 Any progress on that issue?

**Comment by advayDev1** [comment]
Now that I've got Bruno's opinion on #75 , I can get this done.  It'll be one pull request.

We'll be supporting sourceSets, a default hard-coded convention, and user overrides it looks like.

**Comment by brunobowden** [comment]
That sounds like a good balance.

**Comment by advayDev1** [comment]
Ok see pull #78  - we can't finish this until the transition to real plugin allows us to configure the inputs to certain tasks using source sets.
