### ISSUE TITLE
Alpha release acceptance testing

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#528]
We hope to have an alpha (0.5) release today/tomorrow, and we'd like some help testing it.
We're hoping to get at minimum successful builds on:
- @brunobowden - multi-project + full configuration via cocoapods
- @advayDev1 - multi-project + native libraries + other power features
- @andrewfunston - project using Dagger/dependency injection/annotation processors

When this bug is updated with a particular commit SHA, please try building (and running on an iOS device if possible) your project and update this thread with the results.

Thanks!

**Comment by brunobowden** [comment]
I also use cycleFinder as well.

**Comment by advayDev1** [comment]
me too; we should turn that on by default someday :)

**Comment by brunobowden** [comment]
Let's go with SHA 241b9df. That's PR #530 "minVersionOsx = 10.6 (new default)".

It's already working well for me.

@advayDev1 - did you run the overnight build like you talked about?

**Comment by advayDev1** [comment]
no, I was waiting for the SHA.
let me kick things off now, since i wont be on my machine again until ~4pm, perhaps it will finish quicker

**Comment by advayDev1** [comment]
Alright well in this span https://github.com/madvay/j2objc-gradle/compare/v0.4.9.4.0-alpha-fork...madvay:v0.4.9.9-alpha-fork we've broken something at least for me.  Investigating now, but I will have to be away in a bit.

**Comment by advayDev1** [comment]
So after clean building some and incrementally building others (for speed), everything is working except:

1.  pretty obscure issue re: translate mappings (actually an undocumented breaking change in the CHANGELOG - which caused all my other issues; filing a PR).
2.  @brunobowden you need to decide whether this is an issue or not:  With project B depending on A, when you run './gradlew build', B's j2objcBuild will succeed before A's j2objcPodSpec or j2objcXcode (but B's j2objcXcode will occur after A's j2objcXcode, just all at the very end of the build).  This occurs because while j2objcAssemble depends on j2objcXcode (and therefore j2objcPodSpec),  j2objcBuild does not depend on j2objcAssemble (which is correct) and instead j2objcBuildDebug and j2objcBuildRelease rely on j2objcAssembleDebug and j2objcAssembleRelease.  There is no easy solution here except adding yet another layer of indirect tasks.  You can't make j2objcAssembleDebug|Release rely on j2objcXcode.

**Comment by brunobowden** [comment]
Why can't you make `j2objcAssemble{Debug|Release}` rely on j2objcXcode?
Have a look at the PR I just posted. I don't think this causes a problem
either way but it feels as though j2objcAssemble{Debug|Release} should call
j2objcXcode.

**Comment by brunobowden** [comment]
@andrewfunston - can you give your blessing on the build, now SHA d590940? If you could write up a short note in the FAQ about working with dagger, that would be extremely useful but first thing is to bless the release.

**Comment by andrewfunston** [comment]
I won't be able to get to this until later tonight, I hope that will be ok?
I have a few overlapping meetings until the end of the day.

**Comment by brunobowden** [comment]
That's fine @andrewfunston - looking forward to your input.

**Comment by andrewfunston** [comment]
I'm running into a few problems that I'm attempting to debug. It seems like it's something with my code, my larger project is was so self-obfuscated by the end it's taking a bit to unwind. I might have a question or two if I can't fully grock my current issue.

I'll report back shortly.

**Comment by brunobowden** [comment]
Happy to help. I got the Android CI build working and Advay is close to
doing the same for the Xcode build.

**Comment by andrewfunston** [comment]
I stripped down my project to the minimum parts to test the plugin (just the shared/ios-app) for this migration to mitigate cross chatter.

I have things going, but it got a little hacky and I'm not sure why. It uses the same structure as the sample project, but it's unable to find the gson/dagger2 sources for translating my classes unless I add the [translateSourcepaths](https://gist.github.com/andrewfunston/65b0f160aa4622ac6340#file-larger-project-build-failure-L8) to the j2objcConfig and manually add the sources jars.

The [Pod install](https://gist.github.com/andrewfunston/148ba4203da59b7c62aa) was also failing because of the '-' (minus sign) in my shared project (it was name 'java-core'). Most certainly not a major issue as the error report was clear, just a note. 

Lastly [this test is failing](https://gist.github.com/andrewfunston/d7590ada8e06df78f4bd), I have not investigated it at all, I just disabled the test for now. 

I can create issues for anything noted here, I'm currently just fiddling with the build.

**Comment by andrewfunston** [comment]
Besides the noted issues I managed to get my monolithic build acting like it should!

I still have a bit more clean up to do before I can consider it a good example when stripped of the proprietary stuff, but it's getting there.

**Comment by brunobowden** [comment]
That's great Andrew. We'd definitely be interested in adding this to the build.

@advayDev1 - you'd agree on adding this to the e2e build?

**Comment by brunobowden** [comment]
Thanks for all the testing. I'm running some of the systemTests manually (e.g. allPlatforms) as they aren't run automatically. After that, I'll post the version bump and we can get this out the door.

**Comment by advayDev1** [comment]
All SGTM
