### ISSUE TITLE
FYI: new urls

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#547]
http://j2objc-contrib.org and http://j2objccontrib.org now point to https://github.com/j2objc-contrib
http://gradle.j2objc-contrib.org ang http://gradle.j2objccontrib.org now point to https://github.com/j2objc-contrib/j2objc-gradle

question: @brunobowden , what do you think of changing the plugin ID - for the beta:
```
com.github.j2objccontrib.j2objcgradle -> org.j2objccontrib.j2objcgradle
```

Shorter to type, and we'd control the namespace at that point.

**Comment by brunobowden** [comment]
Give me a call when you can, so we can discuss this. I'm not convinced yet.... but if we do it, then we should do it for the 0.5 release.

**Comment by advayDev1** [comment]
urls are fine.
we won't change the id itself.
