### ISSUE TITLE
Build checks split for appveyor

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#569]
Note how the AppVeyer CI builds are split in two. Looking at the screenshot below, the first row has the "Required" tag but not "Details". This is reversed for the second row. The Travis build seems to be working correctly.

![screen shot 2015-11-09 at 11 01 42 pm](https://cloud.githubusercontent.com/assets/679339/11056381/2b8a66e4-8736-11e5-9d16-43ecfc3eeb02.png)

**Comment by advayDev1** [comment]
at first glance this is a feature:
http://help.appveyor.com/discussions/suggestions/798-split-build-status-on-github-pr
https://github.com/appveyor/ci/issues/384

let me see if i can alter the config
