### ISSUE TITLE
Improving include and exclude patterns

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#57]
Per discussion from @brunobowden  and @advayDev1, consider changing our include and exclusion patterns to something resembling:
http://gradle.org/docs/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html

See discussion at #54

**Comment by brunobowden** [comment]
Are we going to use sourceSets for this instead?

**Comment by advayDev1** [comment]
we are using sourceSets instead.  i think you want to assign this to me therefore

**Comment by brunobowden** [comment]
Reassigned to @advayDev1
