### ISSUE TITLE
"make frameworks" fails for macosx only J2OBJC_ARCHS

### ISSUE THREAD

**Issue by astrotuna201** [j2objc-contrib/j2objc-gradle#571]
the generation of frameworks (not static libraries) fails using the new "make frameworks" option ...

When J2OBJC_ARCHS is set to the default 
"J2OBJC_ARCHS = macosx iphone iphone64 iphonev7s simulator simulator64" (in common.mk),

the frameworks are assembled, but only include non- maxosx architectures

if J2OBJC_ARCHS is set to 
J2OBJC_ARCHS = macosx

the frameworks are not assembled at all (because presumably the Makefile is looking for the iOS & Simulator static libs.

**Comment by advayDev1** [comment]
Can you please provide full command lines, build.gradle files, and error messages?
Are you sure this is a j2objc-gradle issue, as opposed to j2objc itself?

**Comment by astrotuna201** [comment]
oh yes, sorry: this was meant for the j2objc main site. Please close issue here ...
