### ISSUE TITLE
Podfile configurations customization

### ISSUE THREAD

**Issue by danieldickison** [j2objc-contrib/j2objc-gradle#588]
Instead of the current hardcoded `:configuration => ['Debug']` and `:configuration => ['Release']`, it would be nice if these configuration names were customizable. We have a separate configuration for beta releases on HockeyApp and my current workaround is to edit the Podfile so the j2objc method includes `:configuration => ['Release', 'Preview']`

I think this would go somewhere around here (but I'm not very familiar with groovy):
https://github.com/j2objc-contrib/j2objc-gradle/blob/459d2c70a8fbabc26a440cc3ad284d7d0bf7758e/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy#L487

**Comment by brunobowden** [comment]
@danieldickison - this sounds reasonable. Your pointing to an old version of the code from October so best to use something more current. For example:

https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy#L669

To do this, you'll need to add something to J2objcConfig.groovy to allow someone to specify the configurations:

    List<String> podfileDebugConfigurations = ['Debug']
    List<String> podfileReleaseConfigurations = ['Release']

Please add the following example to both the J2objcConfig.groovy comments AND the FAQ:

    j2objcConfig {
        podfileReleaseConfigurations += ['Preview']
        ...
    }

Within XcodeTask.groovy, you need to add reading of the config around line 91 (see prior lines). Then at line 669, print the array with "[${podfileReleaseConfigurations.join(',')}]" and update the unit tests.

Send me the PR and I'll take a look. This should be pretty straight forward.

Bruno

**Comment by brunobowden** [comment]
Add the configuration to line 728 in J2objcConfig.groovy.

**Comment by danieldickison** [comment]
Thanks for the pointers. Just created pull request #590 with your suggested changes.

**Comment by danieldickison** [comment]
Fixed in #590
