### ISSUE TITLE
Support generated-from-java and hand-migrated ObjC together

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#59]
@brunobowden  continuing our discussion from #56 

how have you been tackling it?

btw, the way I'm doing this right now (until we can finish #51), is:
1. j2objc plugin attached to each of my individual Java projects (let this be JP), each with --build-closure.
  a) translateExcludeClass for entire classes that just don't make any sense in ObjC land and no one depends on.
  b) for libraries I don't control or want to muck too much with, I create a sparse parallel Java source tree which stubs out the methods not compatible with ObjC land.  then I add this sparse source tree to the translateSourcepath, while also keeping the original library's jar on the classpath.  (or if I have both the original and mine as sources, put them both in the sourcepath, with my overlay first)
2. a seperate gradle build project (that depends on all of the above ones) with a single task that copies all of the j2objcCopy output directories from projects in list JP into a single output directory.  They are copied in reverse order of the gradle project dependencies (i.e. if :appx depends on :libx, :appx's j2objcCopy destDir is copied into the final objc directory, and then :libx's destDir is copied on top of it.  this prevents any ill effect from '--build-closure', since the project that 'owns' that source is guaranteed to have the final overwrite for its translated ObjC files).
3. finally I overlay hand-written objc files in a sparse source tree on top of the output of (2).

I find this to be a somewhat cleaner approach than putting a bunch of OCNI in my code, and it isn't possible for libraries I don't control anyway.

**Comment by brunobowden** [comment]
You're ahead of me right now. I've deliberately limited myself to J2ObjC
standard libraries and what I've built myself. I'd quite welcome a design
doc around this and I'm planning to write a design doc for some other areas
myself. In general, I would like to make it easy to import a number of
standard libraries, e.g. okhttp and others.

**Comment by advayDev1** [comment]
Heh looks like I fixed this in #158

**Comment by confile** [comment]
@advayDev1 Awesome!

**Comment by advayDev1** [comment]
@confile, you can try it out by using extraObjcSrcDirs in j2objcConfig

**Comment by confile** [comment]
@advayDev1 Okay I will check it

**Comment by confile** [comment]
@advayDev1 Shouldn't this be named ``extraJavaSrcDirs`` because it specifies additional Java sources?

**Comment by confile** [comment]
@advayDev1 I check this out when it gets merged or do you want me to checkout your pull request?

**Comment by advayDev1** [comment]
No.  Extra java directories should be added to your main SourceSet.  Remember we aren't using anything but sourceSets for Java now.

This is .m or .h files that you have written that should be used in addition to translated ones in order to compile your library.  This occurs for example when you want to provide a native ObjC implementation of a given function.

**Comment by confile** [comment]
@advayDev1 Yes, got it. I add additional source dir with this 

```
sourceSets {
  main {
    java {
      srcDir 'build/source/apt'
      srcDir 'build/source/base'
    }
  }
}
```

Why do we need  ``generatedSourceDirs``anymore? Why do I need ``extraObjcSrcDirs``?

**Comment by advayDev1** [comment]
extraObjcSrcDirs is needed when, for example, you have JNI methods that need objective-c replacements.  (I use this at the moment, there is no way to replace it with Java).

I don't know about generatedSourceDirs, I don't use it myself, as I do what you do above.  If you feel we can remove it, please file a separate issue.
