### ISSUE TITLE
Does not convert app android to Ios

### ISSUE THREAD

**Issue by jhownfs** [j2objc-contrib/j2objc-gradle#608]
Hi, someone help me

I configured j2objc-gradle in my android studio on windows, create the project called Shared, My android app (already existing) and folder IOS, and called Shared in my Android app project, but when I run my project in android studio does not work the conversion.

My grandle sync:

Error:Unable to find module with Gradle path ':Shared' (needed by module 'app'.)

My grandle Build:

:app:preBuild
:Shared:j2objcTranslatedMainLibraryExtraction UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:Shared:compileJava UP-TO-DATE
:Shared:processResources
:app:preReleaseBuild UP-TO-DATE
:Shared:processResources UP-TO-DATE
:app:generateDebugBuildConfig
:Shared:classes UP-TO-DATE
:Shared:jar UP-TO-DATE

Someone help me?

Thank you!

**Comment by brunobowden** [comment]
To do cross platform development, you must use a Mac. Though part of
j2objc-gradle can be run on Windows, the initial version should be done on
a Mac to make sure it works end to end. The tool itself is pretty complex
to use. I would do searches online for "Unable to find module with Gradle
path" as that appears to be a separate error from using j2objc-gradle.
Also, make sure that the Java only build works correctly first.

https://github.com/j2objc-contrib/j2objc-gradle#quick-start-guide

**Comment by jhownfs** [comment]
Hi Bruno,

Thank for your reply, my app android was building in android studio on windows and now i'm using Mac for development apps, so this app android already work very well, I need recreate this app on Mac? or I can only convert?

**Comment by brunobowden** [comment]
J2ObjC requires full source code access for every library that you want to
share on both platforms and a possibly extensive refactoring of the
codebase. You need to separate out all the shared so that it only have Java
and no Android dependencies.

**Comment by jhownfs** [comment]
Ok, thanks.

That is really complex to do hahha....

**Comment by jhownfs** [comment]
I tried to convert inside on Mac, using 

$ j2objec Hello.java

and me response: j2object: command not fond

I Already download the last version and unzip, try run inside folder it not work. =(
