### ISSUE TITLE
Translation fails on use of hamcrest libraries

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#61]
```
error: /SOMETHING/SomethingTest.java:75: The type org.hamcrest.Matcher cannot be resolved. It is indirectly referenced from required .class files
```

Easy to fix just in my project, but since hamcrest is part of the default set of jars in the j2objc/lib directory, I was thinking of adding it to both translateJ2objcLibs and compileFlags.  Thoughts?

**Comment by advayDev1** [comment]
(Also, my project doesn't directly use hamcrest, it is Junit which is now using it under the hood).

**Comment by brunobowden** [comment]
What's causing this issue?

**Comment by advayDev1** [comment]
The test you see there is a Junit 4 test and I'm using the ExpectedException feature.

While I neither import nor use org.hamcrest.Matcher, Junit 4 does use it under the covers:
https://github.com/junit-team/junit/blob/817ea24f69a040d4161525e600b73d7037a3222f/src/main/java/org/junit/rules/ExpectedException.java#L172

(And since this is a standard j2objc library, I'd argue we should add it to the default list like all other j2objc libraries).

**Comment by advayDev1** [comment]
One more thing, with the upcoming release of j2objc, we're going to have to deal with versioning (I'm using the master build if j2objc myself because I need some of the latest features).

Namely we will have with (updated) version numbers:
guava-18.0.jar
hamcrest-core-1.3.jar

So either automatic discovery of the right paths is needed, or we need no default and demand the developer tell us, or some kind of setting per j2objc release (or, couple j2objc-gradle releases with specific releases of j2objc).
