### ISSUE TITLE
Need to add Guava headers to native compile header search path

### ISSUE THREAD

**Issue by gchoza** [j2objc-contrib/j2objc-gradle#612]
When compiling objective c generated code I get the following error:

    GcatMobile/shared/build/j2objcSrcGenMain/com/gcatconsult/shared/remote/NetworkBase.m:14:10: fatal error:
    'com/google/common/io/BaseEncoding.h' file not found

    #include "com/google/common/io/BaseEncoding.h"

The reason is that the guava objective c headers have been moved to /include/guava which I need to add to the header search path. I have looked carefully at the available documentation and FAQ but cannot figure out a way to add a directory to the compile header search path.

Please refer to this stackoverflow issue where tball explains the issue:
[http://stackoverflow.com/questions/36440984/j2ojbc-native-compile-guava-headers-missing](url)

Here are parts of the build.gradle file:

        id "com.github.j2objccontrib.j2objcgradle" version "0.6.0-alpha"

    // Plugin settings; put these at the bottom of the file.
    j2objcConfig {
        // Sets up libraries you depend on
        autoConfigureDeps true
        skipJ2objcVerification true
        translateClasspaths = ["../../SoftwareDev/NgCalDev/External/j2objc-1.0-2.2/lib/guava-19.0.jar"]
        translateArgs '--prefixes', 'src/main/resources/prefixes.properties'
    //    testMinExpectedTests 0

        // Omit these two lines if you don't configure your Xcode project with CocoaPods
    //    xcodeProjectDir '../../NGCalDev/AuthTouchId'  //  suggested directory name
    //    xcodeTargetsIos 'IOS-APP', 'IOS-APPTests'  // replace with your iOS targets

        finalConfigure()          // Must be last call to configuration
    }

We are using J2objc 1.0-2.2,

**Comment by gchoza** [comment]
Found the solution in pull request #603 for the plugin's j2objcConfig:

>  extraObjcCompilerArgs += "-I/Users/developer/SoftwareDev/External/j2objc-1.0-2.2/include/guava"

**Comment by aaronSig** [comment]
A similar approach, again added in the `j2objcConfig` block:

```
// get the location of the j2objc distribution
Properties localProperties = new Properties()
localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
def j2objcHome = localProperties.getProperty('j2objc.home')

translateJ2objcLibs += ["guava-19.0.jar"]
extraObjcCompilerArgs += "-I" + j2objcHome + "/include/guava"
```
