### ISSUE TITLE
Auto generated BridgingHeader with Pod task

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#92]
I found, asking the guys from cocoapods, that you can only have one BridgingHeader pre tXcode target. 

Thus we should and cannot generate a bridging header in our pod file because a use might want to control his bridging header. 

I check if there is another solution for header import but for now there is none.

**Comment by brunobowden** [comment]
Can we modify the existing bridging header? Possibly using the convention:

### J2ObjC Gradle Plugin Generated ###
### Do not modify below this line ###

Our imports here...

**Comment by confile** [comment]
No chance. The existing bridging header is in your project. Our pod has no access to that.

**Comment by confile** [comment]
What did you mean by the task:
```
Confile: Cocoapods integration
  - libmain.a
```

**Comment by brunobowden** [comment]
It's a file, so we can always write to it. Worst case scenario, we ask
someone to specify the location and then manipulate it outside of Cocoapods.

libmain is part of a plan than Advay and I are exploring to building a
library and linking that in rather than the source files.

**Comment by confile** [comment]
Okay that was what you and Advay explained to me in the Skype call from yesterday. If you need any more input or you need a review on your slides just give me a hint.

**Comment by advayDev1** [comment]
So what's the plan here, are we still doing a bridging header or no?  @confile @brunobowden

**Comment by confile** [comment]
No we do not generate a bridging header. If I find another solution I will push it.

**Comment by advayDev1** [comment]
The last message on this thread says that we aren't doing this.

**Comment by brunobowden** [comment]
I'll add a note to the "pod init" command about setting up the bridging header. That's where the advice will likely be most helpful.
