### ISSUE TITLE
Native Build - for library and header files for Xcode

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#94]
Several steps needed for this:
- checking that you can debug and break in to Xcode library with the source code
- using gradle native services for j2objcc and clang build

**Comment by advayDev1** [comment]
How I got my XCode project to work using native gradle building:
- Library search paths includes j2objc lib/ dist for Debug and Release
- For debug, library search path additionally includes GRADLEPROJECT/build/binaries/mainStaticLibrary/iosDebug
- For release, library search path additionally includes GRADLEPROJECT/build/binaries/mainStaticLibrary/iosRelease
- User header search paths includes the plugin extension's destDir
- plugin extensions's destDir also is added as a 'folder reference' to the Xcode project.  This allows easy auto completion and Command-Click hyperlinks.

@confile, the above should be what is needed to generate the appropriate pod spec, but let me know if that description is incomplete.

@brunobowden - I've figured out and tested the changes to the native build that allow debug symbols, step-into, and good call stacks to be generated.

Main issue now is subproject vs. additional build tasks.  It is going to get pretty complicated either way, so I'll ping when that's ready.

**Comment by brunobowden** [comment]
Very exciting. I'm looking forward to trying this myself.

**Comment by confile** [comment]
@advayDev1 What exactly is native build? Sorry for the stupid question.

**Comment by advayDev1** [comment]
Compilation and linking of objective c in gradle using the native build
plugins.

**Comment by advayDev1** [comment]
Since #92 indicates we have no bridging header, I will instead just finish up the 'assemble' work in this task.

**Comment by advayDev1** [comment]
touch
