### ISSUE TITLE
Unit Testing for Plugin

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-gradle#98]
This is going to be needed for more external contributors.

@advayDev1 - please set up initial example test, then reassign to me and I'll build out the tests for all the other tasks

**Comment by advayDev1** [comment]
I will not get a chance to do this

**Comment by brunobowden** [comment]
There isn't as much of a rush on this. I hope to work on this later next
week.

**Comment by brunobowden** [comment]
Marking as fixed as the unit testing framework is in place and covers a consider amount of functionality. I'll add something to the style guidelines about requiring tests for future changes.
